set(LLVM_TARGET_DEFINITIONS ScheduleEnums.td)
mlir_tablegen(ScheduleEnums.h.inc -gen-enum-decls)
mlir_tablegen(ScheduleEnums.cpp.inc -gen-enum-defs)
add_public_tablegen_target(ObeliskScheduleEnumsIncGen)
set(LLVM_TARGET_DEFINITIONS ScheduleDialect.td)
mlir_tablegen(ScheduleDialect.h.inc -gen-dialect-decls -dialect=schedule)
mlir_tablegen(ScheduleDialect.cpp.inc -gen-dialect-defs -dialect=schedule)
add_public_tablegen_target(ObeliskScheduleDialectIncGen)
set(LLVM_TARGET_DEFINITIONS ScheduleAttrs.td)
mlir_tablegen(ScheduleAttrs.h.inc -gen-attrdef-decls -attrdefs-dialect=schedule)
mlir_tablegen(ScheduleAttrs.cpp.inc -gen-attrdef-defs -attrdefs-dialect=schedule)
add_public_tablegen_target(ObeliskScheduleAttrsIncGen)
add_subdirectory(Transforms)
