// RUN: not obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' -o /dev/null 2>&1 | FileCheck %s

// Outer temporal negation still requires one antecedent result channel. The
// mixed current/next-clock coalescer is rejected until its aggregate result
// can be inverted with exact strength and vacuity at live and final phase.
// CHECK: error: temporal property 'not' over implication/followed-by currently requires one nonvacuous Boolean or guaranteed empty antecedent without first_match, case guards, or match items

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 3, 10, "">, source_end_column = 10 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 3, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 4, 1, "">, source_end_column = 1 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 4, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 8, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 8, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 3, 10, "">, source_end_column = 10 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 3, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 27, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 27, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.a", name = "a", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 30, "">, sym_name = "s7.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a", lifetime = 1 : i32, name = "a", node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 30, "">, sym_name = "s8.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.b", name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 33, "">, sym_name = "s9.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b", lifetime = 1 : i32, name = "b", node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 1, 33, "">, sym_name = "s10.b"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 56, "">, procedure_kind = 2 : i32, source_end_column = 56 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 56, "">, sym_name = "s11", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 56, "">, source_end_column = 56 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 56, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 20, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 54, "">, source_end_column = 54 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 20, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 54, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 22, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 33, "">, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 22, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 30, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 33, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 30, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 33, "">} {
                }
              }
              obelisk.sv.assertion.unary attributes {has_range = false, node_id = 16 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 35, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 54, "">, range_is_unbounded = false, source_end_column = 54 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 35, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 54, "">} {
                obelisk.sv.assertion.binary attributes {node_id = 17 : i64, operator_kind = 12 : i32, operator_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 48, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 51, "">, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 39, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 54, "">, source_end_column = 54 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 39, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 54, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 40, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 47, "">, repetition_is_unbounded = false, repetition_kind = 0 : i32, repetition_max = 1 : i64, repetition_min = 0 : i64, source_end_column = 47 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 40, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 47, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 19 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 40, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 41, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 41 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 40, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 41, "">} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 20 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 52, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 53, "">, repetition_is_unbounded = false, source_end_column = 53 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 52, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 53, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 21 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 52, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 53, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 53 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 52, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 53, "">} {
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.empty attributes {node_id = 22 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 55, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 56, "">, source_end_column = 56 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-invalid.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 55, "../../../../tmp/obelisk-mixed-empty-invalid.sv", 2, 56, "">} {
            }
          }
        }
      }
    }
  }
}
