// RUN: obelisk-opt %s --lower-obelisk-to-sim | FileCheck %s

// IEEE 1800-2017 21.4.3: lower unpacked dimensions always advance from
// their numerical low bound to high bound, while start/finish and @ records
// address only the highest remaining dimension.

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 1, "../../../../tmp/readmem_multidim.sv", 4, 10, "">, source_end_column = 10 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 1, "../../../../tmp/readmem_multidim.sv", 4, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 1, "../../../../tmp/readmem_multidim.sv", 5, 1, "">, source_end_column = 1 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 1, "../../../../tmp/readmem_multidim.sv", 5, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 8, "../../../../tmp/readmem_multidim.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 8, "../../../../tmp/readmem_multidim.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 1, "../../../../tmp/readmem_multidim.sv", 4, 10, "">, source_end_column = 10 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 1, 1, "../../../../tmp/readmem_multidim.sv", 4, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.memory", lifetime = 1 : i32, name = "memory", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 2, 15, "../../../../tmp/readmem_multidim.sv", 2, 32, "">, semantic_type = !obelisk.ranged_unpacked_array<2 : 0 x !obelisk.ranged_unpacked_array<8 : 5 x !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 32 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 2, 15, "../../../../tmp/readmem_multidim.sv", 2, 32, "">, sym_name = "s5.memory"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 3, "../../../../tmp/readmem_multidim.sv", 3, 48, "">, procedure_kind = 0 : i32, source_end_column = 48 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 3, "../../../../tmp/readmem_multidim.sv", 3, 48, "">, sym_name = "s6", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.expression_statement attributes {node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 11, "../../../../tmp/readmem_multidim.sv", 3, 48, "">, source_end_column = 48 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 11, "../../../../tmp/readmem_multidim.sv", 3, 48, "">} {
            obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$readmemh", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = true, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 11, "../../../../tmp/readmem_multidim.sv", 3, 47, "">, semantic_type = !obelisk.void, source_end_column = 47 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 11, "../../../../tmp/readmem_multidim.sv", 3, 47, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
              obelisk.sv.expression.string_literal attributes {constant_value = "multi.mem", is_signed = false, node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 21, "../../../../tmp/readmem_multidim.sv", 3, 32, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 32 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 21, "../../../../tmp/readmem_multidim.sv", 3, 32, "">} {
              }
              obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 34, "../../../../tmp/readmem_multidim.sv", 3, 40, "">, semantic_type = !obelisk.ranged_unpacked_array<2 : 0 x !obelisk.ranged_unpacked_array<8 : 5 x !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 40 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 34, "../../../../tmp/readmem_multidim.sv", 3, 40, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 34, "../../../../tmp/readmem_multidim.sv", 3, 40, "">, referenced_path = "top.memory", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s5.memory, semantic_type = !obelisk.ranged_unpacked_array<2 : 0 x !obelisk.ranged_unpacked_array<8 : 5 x !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 40 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 34, "../../../../tmp/readmem_multidim.sv", 3, 40, "">} {
                }
                obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 34, "../../../../tmp/readmem_multidim.sv", 3, 40, "">, semantic_type = !obelisk.ranged_unpacked_array<2 : 0 x !obelisk.ranged_unpacked_array<8 : 5 x !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 40 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 34, "../../../../tmp/readmem_multidim.sv", 3, 40, "">} {
                }
              }
              obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 42, "../../../../tmp/readmem_multidim.sv", 3, 43, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 43 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 42, "../../../../tmp/readmem_multidim.sv", 3, 43, "">} {
              }
              obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 45, "../../../../tmp/readmem_multidim.sv", 3, 46, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_multidim.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_multidim.sv", 3, 45, "../../../../tmp/readmem_multidim.sv", 3, 46, "">} {
              }
            }
          }
        }
      }
    }
  }
}

// CHECK: ^{{bb[0-9]+}}(%[[TOP:.*]]: i64, {{.*}}, %[[COUNT:.*]]: i64, %[[SUBWORD:.*]]: i64, {{.*}}: i1):
// CHECK: %[[DATA:.*]], %[[KIND:.*]], %[[FILE_ADDRESS:.*]] = obelisk_sim.file.readmem_token {{.*}} {radix = 16 : i32}
// CHECK: cf.cond_br {{.*}}, ^{{bb[0-9]+}}(%[[FILE_ADDRESS]], {{.*}}, %[[COUNT]], {{.*}} : i64, i1, i64, i64, i1),
// CHECK: %[[OUTER_REF:.*]] = obelisk_sim.ref.array_element {{.*}}[%[[TOP]]]
// CHECK: %[[INNER_ORDINAL:.*]] = arith.remui %[[SUBWORD]],
// CHECK: %[[INNER_INDEX:.*]] = arith.addi %[[INNER_ORDINAL]], {{.*}} : i64
// CHECK: %[[INNER_REF:.*]] = obelisk_sim.ref.array_element %[[OUTER_REF]][%[[INNER_INDEX]]]
// CHECK: obelisk_sim.ref.store {{.*}} to %[[INNER_REF]]
// CHECK: %[[NEXT_SUBWORD:.*]] = arith.addi %[[SUBWORD]],
// CHECK: %[[ROW_COMPLETE:.*]] = arith.cmpi eq, %[[NEXT_SUBWORD]],
// CHECK: arith.select %[[ROW_COMPLETE]], {{.*}}, %[[TOP]] : i64
// CHECK: arith.select %[[ROW_COMPLETE]], {{.*}}, %[[NEXT_SUBWORD]] : i64
