// RUN: obelisk-opt %s --lower-obelisk-to-sim | FileCheck %s

// MLIR-level coverage for integral associative memories. The default range is
// the signed key domain; explicit unsigned bounds retain unsigned comparisons.

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 1, "../../../../tmp/readmem_assoc.sv", 8, 10, "">, source_end_column = 10 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 1, "../../../../tmp/readmem_assoc.sv", 8, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 1, "../../../../tmp/readmem_assoc.sv", 9, 1, "">, source_end_column = 1 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 1, "../../../../tmp/readmem_assoc.sv", 9, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 8, "../../../../tmp/readmem_assoc.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 8, "../../../../tmp/readmem_assoc.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 1, "../../../../tmp/readmem_assoc.sv", 8, 10, "">, source_end_column = 10 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 1, 1, "../../../../tmp/readmem_assoc.sv", 8, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.signed_memory", lifetime = 1 : i32, name = "signed_memory", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 2, 15, "../../../../tmp/readmem_assoc.sv", 2, 33, "">, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, false>, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 2, 15, "../../../../tmp/readmem_assoc.sv", 2, 33, "">, sym_name = "s5.signed_memory"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.unsigned_memory", lifetime = 1 : i32, name = "unsigned_memory", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 3, 13, "../../../../tmp/readmem_assoc.sv", 3, 43, "">, semantic_type = !obelisk.assoc<!obelisk.integral<8, false, false, 7 : 0, byte>, !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, false>, source_end_column = 43 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 3, 13, "../../../../tmp/readmem_assoc.sv", 3, 43, "">, sym_name = "s6.unsigned_memory"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 4, 3, "../../../../tmp/readmem_assoc.sv", 7, 6, "">, procedure_kind = 0 : i32, source_end_column = 6 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 4, 3, "../../../../tmp/readmem_assoc.sv", 7, 6, "">, sym_name = "s7", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 4, 11, "../../../../tmp/readmem_assoc.sv", 7, 6, "">, source_end_column = 6 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 4, 11, "../../../../tmp/readmem_assoc.sv", 7, 6, "">} {
            obelisk.sv.statement.list attributes {node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 4, 11, "../../../../tmp/readmem_assoc.sv", 7, 6, "">, source_end_column = 6 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 4, 11, "../../../../tmp/readmem_assoc.sv", 7, 6, "">} {
              obelisk.sv.statement.expression_statement attributes {node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 5, "../../../../tmp/readmem_assoc.sv", 5, 44, "">, source_end_column = 44 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 5, "../../../../tmp/readmem_assoc.sv", 5, 44, "">} {
                obelisk.sv.expression.call attributes {argument_count = 2 : i64, callee_name = "$readmemh", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = true, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 5, "../../../../tmp/readmem_assoc.sv", 5, 43, "">, semantic_type = !obelisk.void, source_end_column = 43 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 5, "../../../../tmp/readmem_assoc.sv", 5, 43, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "signed.mem", is_signed = false, node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 15, "../../../../tmp/readmem_assoc.sv", 5, 27, "">, semantic_type = !obelisk.ranged_packed_array<79 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 27 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 15, "../../../../tmp/readmem_assoc.sv", 5, 27, "">} {
                  }
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 29, "../../../../tmp/readmem_assoc.sv", 5, 42, "">, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, false>, source_end_column = 42 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 29, "../../../../tmp/readmem_assoc.sv", 5, 42, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 29, "../../../../tmp/readmem_assoc.sv", 5, 42, "">, referenced_path = "top.signed_memory", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s5.signed_memory, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, false>, source_end_column = 42 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 29, "../../../../tmp/readmem_assoc.sv", 5, 42, "">} {
                    }
                    obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 29, "../../../../tmp/readmem_assoc.sv", 5, 42, "">, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.ranged_packed_array<7 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, false>, source_end_column = 42 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 5, 29, "../../../../tmp/readmem_assoc.sv", 5, 42, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 16 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 5, "../../../../tmp/readmem_assoc.sv", 6, 54, "">, source_end_column = 54 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 5, "../../../../tmp/readmem_assoc.sv", 6, 54, "">} {
                obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$readmemb", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = true, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 17 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 5, "../../../../tmp/readmem_assoc.sv", 6, 53, "">, semantic_type = !obelisk.void, source_end_column = 53 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 5, "../../../../tmp/readmem_assoc.sv", 6, 53, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "unsigned.mem", is_signed = false, node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 15, "../../../../tmp/readmem_assoc.sv", 6, 29, "">, semantic_type = !obelisk.ranged_packed_array<95 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 29 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 15, "../../../../tmp/readmem_assoc.sv", 6, 29, "">} {
                  }
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 19 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 31, "../../../../tmp/readmem_assoc.sv", 6, 46, "">, semantic_type = !obelisk.assoc<!obelisk.integral<8, false, false, 7 : 0, byte>, !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, false>, source_end_column = 46 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 31, "../../../../tmp/readmem_assoc.sv", 6, 46, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 20 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 31, "../../../../tmp/readmem_assoc.sv", 6, 46, "">, referenced_path = "top.unsigned_memory", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.unsigned_memory, semantic_type = !obelisk.assoc<!obelisk.integral<8, false, false, 7 : 0, byte>, !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, false>, source_end_column = 46 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 31, "../../../../tmp/readmem_assoc.sv", 6, 46, "">} {
                    }
                    obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 21 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 31, "../../../../tmp/readmem_assoc.sv", 6, 46, "">, semantic_type = !obelisk.assoc<!obelisk.integral<8, false, false, 7 : 0, byte>, !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, false>, source_end_column = 46 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 31, "../../../../tmp/readmem_assoc.sv", 6, 46, "">} {
                    }
                  }
                  obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 22 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 48, "../../../../tmp/readmem_assoc.sv", 6, 49, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 48, "../../../../tmp/readmem_assoc.sv", 6, 49, "">} {
                  }
                  obelisk.sv.expression.integer_literal attributes {constant_value = "7", is_declared_unsized = true, is_signed = true, node_id = 23 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 51, "../../../../tmp/readmem_assoc.sv", 6, 52, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 52 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_assoc.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_assoc.sv", 6, 51, "../../../../tmp/readmem_assoc.sv", 6, 52, "">} {
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


// CHECK: obelisk_sim.container.clone
// CHECK: obelisk_sim.assoc.create {{.*}}key_kind = 2 : i32, key_width = 32
// CHECK: obelisk_sim.file.readmem_token {{.*}} {radix = 16 : i32}
// CHECK: arith.cmpi sge, {{.*}}, %{{.*-2147483648.*}} : i64
// CHECK: arith.cmpi sle, {{.*}}, %{{.*2147483647.*}} : i64
// CHECK: obelisk_sim.assoc.write {{.*}} : (!obelisk_sim.assoc_array<i32,
// CHECK: obelisk_sim.assoc.create {{.*}}key_kind = 1 : i32, key_width = 8
// CHECK: obelisk_sim.file.readmem_token {{.*}} {radix = 2 : i32}
// CHECK: arith.cmpi uge
// CHECK: arith.cmpi ule
// CHECK: obelisk_sim.assoc.write {{.*}} : (!obelisk_sim.assoc_array<i8,
