// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' '--encode-obelisk-sim-to-bytecode=vpi=off' -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' --convert-obelisk-sim-processes-to-llvm-coroutines -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' -o %t.threaded
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' --mlir-disable-threading -o %t.serial
// RUN: diff %t.threaded %t.serial

module attributes {llvm.data_layout = "e-m:e-p:64:64-i64:64-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 1, "../../../../tmp/sva_unbounded_delay.sv", 5, 10, "">, source_end_column = 10 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 1, "../../../../tmp/sva_unbounded_delay.sv", 5, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 1, "../../../../tmp/sva_unbounded_delay.sv", 6, 1, "">, source_end_column = 1 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 1, "../../../../tmp/sva_unbounded_delay.sv", 6, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 8, "../../../../tmp/sva_unbounded_delay.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 8, "../../../../tmp/sva_unbounded_delay.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 1, "../../../../tmp/sva_unbounded_delay.sv", 5, 10, "">, source_end_column = 10 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 1, "../../../../tmp/sva_unbounded_delay.sv", 5, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 24, "../../../../tmp/sva_unbounded_delay.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 24, "../../../../tmp/sva_unbounded_delay.sv", 1, 27, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 24, "../../../../tmp/sva_unbounded_delay.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 24, "../../../../tmp/sva_unbounded_delay.sv", 1, 27, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.a", name = "a", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 29, "../../../../tmp/sva_unbounded_delay.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 29, "../../../../tmp/sva_unbounded_delay.sv", 1, 30, "">, sym_name = "s7.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a", lifetime = 1 : i32, name = "a", node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 29, "../../../../tmp/sva_unbounded_delay.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 29, "../../../../tmp/sva_unbounded_delay.sv", 1, 30, "">, sym_name = "s8.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.b", name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 32, "../../../../tmp/sva_unbounded_delay.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 32, "../../../../tmp/sva_unbounded_delay.sv", 1, 33, "">, sym_name = "s9.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b", lifetime = 1 : i32, name = "b", node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 32, "../../../../tmp/sva_unbounded_delay.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 32, "../../../../tmp/sva_unbounded_delay.sv", 1, 33, "">, sym_name = "s10.b"} {
        }
        obelisk.sv.symbol.port attributes {direction = 1 : i32, hierarchical_name = "top.hit", name = "hit", node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 48, "../../../../tmp/sva_unbounded_delay.sv", 1, 51, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 51 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 48, "../../../../tmp/sva_unbounded_delay.sv", 1, 51, "">, sym_name = "s11.hit"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.hit", lifetime = 1 : i32, name = "hit", node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 48, "../../../../tmp/sva_unbounded_delay.sv", 1, 51, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 51 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 1, 48, "../../../../tmp/sva_unbounded_delay.sv", 1, 51, "">, sym_name = "s12.hit"} {
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.ap", name = "ap", node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, source_end_column = 74 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, sym_name = "s13.ap"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, procedure_kind = 2 : i32, source_end_column = 74 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, sym_name = "s14", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.ap", block_symbol = @s1.$root::@s3.top::@s4.top::@s13.ap, node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, source_end_column = 74 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 16 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, source_end_column = 74 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 3, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 17 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 24, "../../../../tmp/sva_unbounded_delay.sv", 2, 50, "">, source_end_column = 50 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 24, "../../../../tmp/sva_unbounded_delay.sv", 2, 50, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 26, "../../../../tmp/sva_unbounded_delay.sv", 2, 37, "">, source_end_column = 37 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 26, "../../../../tmp/sva_unbounded_delay.sv", 2, 37, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 19 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 34, "../../../../tmp/sva_unbounded_delay.sv", 2, 37, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 34, "../../../../tmp/sva_unbounded_delay.sv", 2, 37, "">} {
                  }
                }
                // a ##1 a ##[2:$] b exercises both bounded-prefix and warm-up
                // live-token bitsets in the compact monitor.
                obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64}, {is_unbounded = true, min = 2 : i64}], node_id = 20 : i64} {
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 21 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 39, "../../../../tmp/sva_unbounded_delay.sv", 2, 40, "">, repetition_is_unbounded = false, source_end_column = 40 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 39, "../../../../tmp/sva_unbounded_delay.sv", 2, 40, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 22 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 39, "../../../../tmp/sva_unbounded_delay.sv", 2, 40, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 40 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 39, "../../../../tmp/sva_unbounded_delay.sv", 2, 40, "">} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 200 : i64, repetition_is_unbounded = false} {
                    obelisk.sv.expression.named_value attributes {node_id = 201 : i64, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 49, "../../../../tmp/sva_unbounded_delay.sv", 2, 50, "">, repetition_is_unbounded = false, source_end_column = 50 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 49, "../../../../tmp/sva_unbounded_delay.sv", 2, 50, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 24 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 49, "../../../../tmp/sva_unbounded_delay.sv", 2, 50, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 50 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 49, "../../../../tmp/sva_unbounded_delay.sv", 2, 50, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 25 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 52, "../../../../tmp/sva_unbounded_delay.sv", 2, 60, "">, source_end_column = 60 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 52, "../../../../tmp/sva_unbounded_delay.sv", 2, 60, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 26 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 52, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 59 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 52, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 27 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 52, "../../../../tmp/sva_unbounded_delay.sv", 2, 55, "">, referenced_path = "top.hit", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.hit, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 55 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 52, "../../../../tmp/sva_unbounded_delay.sv", 2, 55, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b1", is_signed = false, node_id = 28 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 58, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 59 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 58, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "1", is_signed = true, node_id = 29 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 58, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_end_column = 59 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 58, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 30 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 58, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 59 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 58, "../../../../tmp/sva_unbounded_delay.sv", 2, 59, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 31 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 66, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">, source_end_column = 74 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 66, "../../../../tmp/sva_unbounded_delay.sv", 2, 74, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 32 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 66, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 73 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 66, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 33 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 66, "../../../../tmp/sva_unbounded_delay.sv", 2, 69, "">, referenced_path = "top.hit", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.hit, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 69 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 66, "../../../../tmp/sva_unbounded_delay.sv", 2, 69, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b0", is_signed = false, node_id = 34 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 72, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 73 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 72, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "0", is_signed = true, node_id = 35 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 72, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_end_column = 73 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 72, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 36 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 72, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 73 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 2, 72, "../../../../tmp/sva_unbounded_delay.sv", 2, 73, "">} {
                      }
                    }
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.sp", name = "sp", node_id = 37 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, source_end_column = 82 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, sym_name = "s15.sp"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 38 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, procedure_kind = 2 : i32, source_end_column = 82 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, sym_name = "s16", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.sp", block_symbol = @s1.$root::@s3.top::@s4.top::@s15.sp, node_id = 39 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, source_end_column = 82 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 40 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, source_end_column = 82 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 3, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 41 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 24, "../../../../tmp/sva_unbounded_delay.sv", 3, 58, "">, source_end_column = 58 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 24, "../../../../tmp/sva_unbounded_delay.sv", 3, 58, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 42 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 26, "../../../../tmp/sva_unbounded_delay.sv", 3, 37, "">, source_end_column = 37 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 26, "../../../../tmp/sva_unbounded_delay.sv", 3, 37, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 43 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 34, "../../../../tmp/sva_unbounded_delay.sv", 3, 37, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 34, "../../../../tmp/sva_unbounded_delay.sv", 3, 37, "">} {
                  }
                }
                obelisk.sv.assertion.strong_weak attributes {node_id = 44 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 39, "../../../../tmp/sva_unbounded_delay.sv", 3, 58, "">, source_end_column = 58 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 39, "../../../../tmp/sva_unbounded_delay.sv", 3, 58, "">, strength = 0 : i32} {
                  obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = true, min = 0 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 51, "../../../../tmp/sva_unbounded_delay.sv", 3, 54, "">}], node_id = 45 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 46, "../../../../tmp/sva_unbounded_delay.sv", 3, 57, "">, source_end_column = 57 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 46, "../../../../tmp/sva_unbounded_delay.sv", 3, 57, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 46 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 46, "../../../../tmp/sva_unbounded_delay.sv", 3, 47, "">, repetition_is_unbounded = false, source_end_column = 47 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 46, "../../../../tmp/sva_unbounded_delay.sv", 3, 47, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 47 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 46, "../../../../tmp/sva_unbounded_delay.sv", 3, 47, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 47 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 46, "../../../../tmp/sva_unbounded_delay.sv", 3, 47, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 48 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 56, "../../../../tmp/sva_unbounded_delay.sv", 3, 57, "">, repetition_is_unbounded = false, source_end_column = 57 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 56, "../../../../tmp/sva_unbounded_delay.sv", 3, 57, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 49 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 56, "../../../../tmp/sva_unbounded_delay.sv", 3, 57, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 57 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 56, "../../../../tmp/sva_unbounded_delay.sv", 3, 57, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 50 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 60, "../../../../tmp/sva_unbounded_delay.sv", 3, 68, "">, source_end_column = 68 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 60, "../../../../tmp/sva_unbounded_delay.sv", 3, 68, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 51 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 60, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 67 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 60, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 52 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 60, "../../../../tmp/sva_unbounded_delay.sv", 3, 63, "">, referenced_path = "top.hit", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.hit, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 63 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 60, "../../../../tmp/sva_unbounded_delay.sv", 3, 63, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b1", is_signed = false, node_id = 53 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 66, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 67 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 66, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "1", is_signed = true, node_id = 54 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 66, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_end_column = 67 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 66, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 55 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 66, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 67 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 66, "../../../../tmp/sva_unbounded_delay.sv", 3, 67, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 56 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 74, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">, source_end_column = 82 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 74, "../../../../tmp/sva_unbounded_delay.sv", 3, 82, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 57 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 74, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 81 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 74, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 58 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 74, "../../../../tmp/sva_unbounded_delay.sv", 3, 77, "">, referenced_path = "top.hit", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.hit, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 77 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 74, "../../../../tmp/sva_unbounded_delay.sv", 3, 77, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b0", is_signed = false, node_id = 59 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 80, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 81 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 80, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "0", is_signed = true, node_id = 60 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 80, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_end_column = 81 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 80, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 61 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 80, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 81 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 3, 80, "../../../../tmp/sva_unbounded_delay.sv", 3, 81, "">} {
                      }
                    }
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.cs", name = "cs", node_id = 62 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, source_end_column = 59 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, sym_name = "s17.cs"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 63 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, procedure_kind = 2 : i32, source_end_column = 59 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, sym_name = "s18", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.cs", block_symbol = @s1.$root::@s3.top::@s4.top::@s17.cs, node_id = 64 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, source_end_column = 59 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 3 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 65 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, source_end_column = 59 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 3, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 66 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 23, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 23, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 67 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 25, "../../../../tmp/sva_unbounded_delay.sv", 4, 36, "">, source_end_column = 36 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 25, "../../../../tmp/sva_unbounded_delay.sv", 4, 36, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 68 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 33, "../../../../tmp/sva_unbounded_delay.sv", 4, 36, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 33, "../../../../tmp/sva_unbounded_delay.sv", 4, 36, "">} {
                  }
                }
                obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = true, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 43, "../../../../tmp/sva_unbounded_delay.sv", 4, 46, "">}], node_id = 69 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 38, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 38, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 70 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 38, "../../../../tmp/sva_unbounded_delay.sv", 4, 39, "">, repetition_is_unbounded = false, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 38, "../../../../tmp/sva_unbounded_delay.sv", 4, 39, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 71 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 38, "../../../../tmp/sva_unbounded_delay.sv", 4, 39, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 38, "../../../../tmp/sva_unbounded_delay.sv", 4, 39, "">} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 72 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 48, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">, repetition_is_unbounded = false, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 48, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 73 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 48, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 48, "../../../../tmp/sva_unbounded_delay.sv", 4, 49, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 74 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 51, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">, source_end_column = 59 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 51, "../../../../tmp/sva_unbounded_delay.sv", 4, 59, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 75 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 51, "../../../../tmp/sva_unbounded_delay.sv", 4, 58, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 58 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 51, "../../../../tmp/sva_unbounded_delay.sv", 4, 58, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 76 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 51, "../../../../tmp/sva_unbounded_delay.sv", 4, 54, "">, referenced_path = "top.hit", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.hit, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 54 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 51, "../../../../tmp/sva_unbounded_delay.sv", 4, 54, "">} {
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 77 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 57, "../../../../tmp/sva_unbounded_delay.sv", 4, 58, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 58 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/sva_unbounded_delay.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_unbounded_delay.sv", 4, 57, "../../../../tmp/sva_unbounded_delay.sv", 4, 58, "">} {
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


// The ordinary assert sequence is weak at finite end of simulation. Its
// warm-up queue is counted by a compact bits &= bits - 1 loop and eligible
// tokens by an integer load; this uses the same SSA in native and bytecode.
// CHECK-LABEL: obelisk_sim.func private @unit_0.$concurrent_eos_count.16.delay_weak(
// CHECK-SAME: obelisk_sim.concurrent_eos_counted
// CHECK: obelisk_sim.ref.load
// CHECK: arith.subi
// CHECK: arith.andi
// CHECK: arith.addi
// CHECK: obelisk_sim.spawn @unit_0.fork.16.0.0
// CHECK-LABEL: obelisk_sim.func private @unit_0(
// CHECK-SAME: obelisk_sim.persistent_delay_aggregate_tokens
// CHECK-SAME: obelisk_sim.persistent_delay_minimum = 2 : i64
// CHECK-SAME: obelisk_sim.persistent_delay_prefix_horizon = 2 : i64
// CHECK: obelisk_sim.spawn @unit_0.$concurrent_eos_count.16.delay_weak
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: arith.shli
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: arith.select
// CHECK: arith.subi

// Explicit strong qualification fails every still-pending token at EOS.
// M=0 needs no warm-up queue, so the coordinator captures one count.
// CHECK-LABEL: obelisk_sim.func private @unit_1.$concurrent_eos_count.40.delay_strong(
// CHECK-SAME: obelisk_sim.concurrent_eos_counted
// CHECK-COUNT-1: obelisk_sim.ref.load
// CHECK: obelisk_sim.spawn @unit_1.fork.40.1.1
// CHECK-LABEL: obelisk_sim.func private @unit_1(
// CHECK-SAME: obelisk_sim.end_of_simulation_strength = "strong"
// CHECK-SAME: obelisk_sim.persistent_delay_minimum = 0 : i64
// CHECK-SAME: obelisk_sim.strong_weak_monitor
// CHECK: obelisk_sim.spawn @unit_1.$concurrent_eos_count.40.delay_strong
// CHECK-COUNT-2: obelisk_sim.assert.sampled_read

// Cover sequence keeps eligible tokens after a match so every later true
// terminal preserves the LRM's per-endpoint match multiplicity. It has no EOS
// coordinator because an incomplete sequence is not a cover hit.
// CHECK-LABEL: obelisk_sim.func private @unit_2(
// CHECK-SAME: obelisk_sim.persistent_delay_aggregate_tokens
// CHECK-SAME: obelisk_sim.persistent_delay_all_matches
// CHECK-SAME: obelisk_sim.persistent_delay_minimum = 1 : i64
// CHECK-NOT: concurrent_eos_count
// CHECK-COUNT-2: obelisk_sim.assert.sampled_read
// CHECK: arith.select
// CHECK: arith.subi
