// RUN: obelisk-opt %s --lower-obelisk-to-sim | FileCheck %s

// Enum data is checked against the frontend-frozen numeric inventory before
// any memory write. An invalid word follows the LRM error-and-stop path.

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 1, "../../../../tmp/readmem_enum.sv", 5, 10, "">, source_end_column = 10 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 1, "../../../../tmp/readmem_enum.sv", 5, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 1, "../../../../tmp/readmem_enum.sv", 6, 1, "">, source_end_column = 1 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 1, "../../../../tmp/readmem_enum.sv", 6, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 8, "../../../../tmp/readmem_enum.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 8, "../../../../tmp/readmem_enum.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 1, "../../../../tmp/readmem_enum.sv", 5, 10, "">, source_end_column = 10 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 1, 1, "../../../../tmp/readmem_enum.sv", 5, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.transparent_member attributes {hierarchical_name = "top.IDLE", name = "IDLE", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 30, "../../../../tmp/readmem_enum.sv", 2, 30, "">, source_end_column = 30 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 30, "../../../../tmp/readmem_enum.sv", 2, 30, "">, sym_name = "s5.IDLE"} {
        }
        obelisk.sv.symbol.transparent_member attributes {hierarchical_name = "top.RUN", name = "RUN", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 40, "../../../../tmp/readmem_enum.sv", 2, 40, "">, source_end_column = 40 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 40, "../../../../tmp/readmem_enum.sv", 2, 40, "">, sym_name = "s6.RUN"} {
        }
        obelisk.sv.symbol.transparent_member attributes {hierarchical_name = "top.DONE", name = "DONE", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 49, "../../../../tmp/readmem_enum.sv", 2, 49, "">, source_end_column = 49 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 49, "../../../../tmp/readmem_enum.sv", 2, 49, "">, sym_name = "s7.DONE"} {
        }
        obelisk.sv.type.type_alias attributes {hierarchical_name = "top.state_t", name = "state_t", node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 3, "../../../../tmp/readmem_enum.sv", 2, 68, "">, semantic_type = !obelisk.enum<"top.state_t", !obelisk.ranged_packed_array<2 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>, source_end_column = 68 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 2, 3, "../../../../tmp/readmem_enum.sv", 2, 68, "">, sym_name = "s8.state_t"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.memory", lifetime = 1 : i32, name = "memory", node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 3, 11, "../../../../tmp/readmem_enum.sv", 3, 22, "">, semantic_type = !obelisk.ranged_unpacked_array<0 : 3 x !obelisk.enum<"top.state_t", !obelisk.ranged_packed_array<2 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 22 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 3, 11, "../../../../tmp/readmem_enum.sv", 3, 22, "">, sym_name = "s9.memory"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 3, "../../../../tmp/readmem_enum.sv", 4, 47, "">, procedure_kind = 0 : i32, source_end_column = 47 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 3, "../../../../tmp/readmem_enum.sv", 4, 47, "">, sym_name = "s10", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.expression_statement attributes {node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 11, "../../../../tmp/readmem_enum.sv", 4, 47, "">, source_end_column = 47 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 11, "../../../../tmp/readmem_enum.sv", 4, 47, "">} {
            obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$readmemb", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = true, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 11, "../../../../tmp/readmem_enum.sv", 4, 46, "">, readmem_enum_element_values = ["3'b0", "3'b11", "3'b111"], semantic_type = !obelisk.void, source_end_column = 46 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 11, "../../../../tmp/readmem_enum.sv", 4, 46, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
              obelisk.sv.expression.string_literal attributes {constant_value = "enum.mem", is_signed = false, node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 21, "../../../../tmp/readmem_enum.sv", 4, 31, "">, semantic_type = !obelisk.ranged_packed_array<63 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 31 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 21, "../../../../tmp/readmem_enum.sv", 4, 31, "">} {
              }
              obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 33, "../../../../tmp/readmem_enum.sv", 4, 39, "">, semantic_type = !obelisk.ranged_unpacked_array<0 : 3 x !obelisk.enum<"top.state_t", !obelisk.ranged_packed_array<2 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 33, "../../../../tmp/readmem_enum.sv", 4, 39, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 33, "../../../../tmp/readmem_enum.sv", 4, 39, "">, referenced_path = "top.memory", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s9.memory, semantic_type = !obelisk.ranged_unpacked_array<0 : 3 x !obelisk.enum<"top.state_t", !obelisk.ranged_packed_array<2 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 33, "../../../../tmp/readmem_enum.sv", 4, 39, "">} {
                }
                obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 16 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 33, "../../../../tmp/readmem_enum.sv", 4, 39, "">, semantic_type = !obelisk.ranged_unpacked_array<0 : 3 x !obelisk.enum<"top.state_t", !obelisk.ranged_packed_array<2 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 33, "../../../../tmp/readmem_enum.sv", 4, 39, "">} {
                }
              }
              obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 17 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 41, "../../../../tmp/readmem_enum.sv", 4, 42, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 42 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 41, "../../../../tmp/readmem_enum.sv", 4, 42, "">} {
              }
              obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 44, "../../../../tmp/readmem_enum.sv", 4, 45, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 45 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/readmem_enum.sv", source_range = !obelisk.source_range<"../../../../tmp/readmem_enum.sv", 4, 44, "../../../../tmp/readmem_enum.sv", 4, 45, "">} {
              }
            }
          }
        }
      }
    }
  }
}


// CHECK-DAG: obelisk_sim.bytes.constant "ERROR: $readmemb: data value is outside the enumerated type"
// CHECK: %[[DATA:.*]], %[[KIND:.*]], %[[ADDRESS:.*]] = obelisk_sim.file.readmem_token {{.*}} {radix = 2 : i32}
// CHECK: obelisk_sim.logic.constant 0 : i3, 0 : i3
// CHECK: obelisk_sim.logic.compare case_eq %[[DATA]],
// CHECK: obelisk_sim.logic.constant 3 : i3, 0 : i3
// CHECK: obelisk_sim.logic.compare case_eq %[[DATA]],
// CHECK: obelisk_sim.logic.constant -1 : i3, 0 : i3
// CHECK: obelisk_sim.logic.compare case_eq %[[DATA]],
// CHECK: cf.cond_br {{.*}}, ^[[WRITE:bb[0-9]+]], ^[[ENUM_ERROR:bb[0-9]+]]
// CHECK: ^[[WRITE]]:
// CHECK: obelisk_sim.ref.store %[[DATA]]
// CHECK: ^[[ENUM_ERROR]]:
// CHECK: obelisk_sim.display
