// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' '--encode-obelisk-sim-to-bytecode=vpi=off' -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' -o %t.threaded
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' --mlir-disable-threading -o %t.serial
// RUN: diff %t.threaded %t.serial

module attributes {llvm.data_layout = "e-m:e-p:64:64-i64:64-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 1, "tmp_sva_formal.sv", 9, 10, "">, source_end_column = 10 : i64, source_end_line = 9 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 1, "tmp_sva_formal.sv", 9, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 1, "tmp_sva_formal.sv", 10, 1, "">, source_end_column = 1 : i64, source_end_line = 10 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 1, "tmp_sva_formal.sv", 10, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 8, "tmp_sva_formal.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 8, "tmp_sva_formal.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 1, "tmp_sva_formal.sv", 9, 10, "">, source_end_column = 10 : i64, source_end_line = 9 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 1, "tmp_sva_formal.sv", 9, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 24, "tmp_sva_formal.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 24, "tmp_sva_formal.sv", 1, 27, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 24, "tmp_sva_formal.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 24, "tmp_sva_formal.sv", 1, 27, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.a", name = "a", node_id = 7 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 29, "tmp_sva_formal.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 29, "tmp_sva_formal.sv", 1, 30, "">, sym_name = "s7.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a", lifetime = 1 : i32, name = "a", node_id = 8 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 29, "tmp_sva_formal.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 29, "tmp_sva_formal.sv", 1, 30, "">, sym_name = "s8.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.b", name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 32, "tmp_sva_formal.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 32, "tmp_sva_formal.sv", 1, 33, "">, sym_name = "s9.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b", lifetime = 1 : i32, name = "b", node_id = 10 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 32, "tmp_sva_formal.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 32, "tmp_sva_formal.sv", 1, 33, "">, sym_name = "s10.b"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.c", name = "c", node_id = 11 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 35, "tmp_sva_formal.sv", 1, 36, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 35, "tmp_sva_formal.sv", 1, 36, "">, sym_name = "s11.c"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.c", lifetime = 1 : i32, name = "c", node_id = 12 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 35, "tmp_sva_formal.sv", 1, 36, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 1 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 1, 35, "tmp_sva_formal.sv", 1, 36, "">, sym_name = "s12.c"} {
        }
        obelisk.sv.symbol.sequence attributes {has_default_instance = false, hierarchical_name = "top.s", name = "s", node_id = 13 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 3, "tmp_sva_formal.sv", 4, 14, "">, port_count = 2 : i64, port_paths = ["top.s.x", "top.s.y"], port_symbols = [@s1.$root::@s3.top::@s4.top::@s13.s::@s14.x, @s1.$root::@s3.top::@s4.top::@s13.s::@s15.y], source_end_column = 14 : i64, source_end_line = 4 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 3, "tmp_sva_formal.sv", 4, 14, "">, sym_name = "s13.s"} {
          obelisk.sv.symbol.assertion_port attributes {has_default_value = false, hierarchical_name = "top.s.x", is_local_variable = false, name = "x", node_id = 14 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 14, "tmp_sva_formal.sv", 2, 21, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 21 : i64, source_end_line = 2 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 14, "tmp_sva_formal.sv", 2, 21, "">, sym_name = "s14.x"} {
          }
          obelisk.sv.symbol.assertion_port attributes {has_default_value = true, hierarchical_name = "top.s.y", is_local_variable = false, name = "y", node_id = 15 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 23, "tmp_sva_formal.sv", 2, 34, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 34 : i64, source_end_line = 2 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 23, "tmp_sva_formal.sv", 2, 34, "">, sym_name = "s15.y"} {
          }
        }
        obelisk.sv.symbol.property attributes {has_default_instance = false, hierarchical_name = "top.p", name = "p", node_id = 16 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 3, "tmp_sva_formal.sv", 7, 14, "">, port_count = 2 : i64, port_paths = ["top.p.x", "top.p.y"], port_symbols = [@s1.$root::@s3.top::@s4.top::@s16.p::@s17.x, @s1.$root::@s3.top::@s4.top::@s16.p::@s18.y], source_end_column = 14 : i64, source_end_line = 7 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 3, "tmp_sva_formal.sv", 7, 14, "">, sym_name = "s16.p"} {
          obelisk.sv.symbol.assertion_port attributes {has_default_value = false, hierarchical_name = "top.p.x", is_local_variable = false, name = "x", node_id = 17 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 14, "tmp_sva_formal.sv", 5, 21, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 21 : i64, source_end_line = 5 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 14, "tmp_sva_formal.sv", 5, 21, "">, sym_name = "s17.x"} {
          }
          obelisk.sv.symbol.assertion_port attributes {has_default_value = true, hierarchical_name = "top.p.y", is_local_variable = false, name = "y", node_id = 18 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 23, "tmp_sva_formal.sv", 5, 34, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 34 : i64, source_end_line = 5 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 23, "tmp_sva_formal.sv", 5, 34, "">, sym_name = "s18.y"} {
          }
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.ap", name = "ap", node_id = 19 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">, source_end_column = 45 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">, sym_name = "s19.ap"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 20 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">, procedure_kind = 2 : i32, source_end_column = 45 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">, sym_name = "s20", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.ap", block_symbol = @s1.$root::@s3.top::@s4.top::@s19.ap, node_id = 21 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">, source_end_column = 45 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 22 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">, source_end_column = 45 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 3, "tmp_sva_formal.sv", 8, 45, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 23 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 24, "tmp_sva_formal.sv", 8, 43, "">, source_end_column = 43 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 24, "tmp_sva_formal.sv", 8, 43, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 24 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 26, "tmp_sva_formal.sv", 8, 37, "">, source_end_column = 37 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 26, "tmp_sva_formal.sv", 8, 37, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 25 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 34, "tmp_sva_formal.sv", 8, 37, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 34, "tmp_sva_formal.sv", 8, 37, "">} {
                  }
                }
                obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 26 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 39, "tmp_sva_formal.sv", 8, 43, "">, repetition_is_unbounded = false, source_end_column = 43 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 39, "tmp_sva_formal.sv", 8, 43, "">} {
                  obelisk.sv.expression.assertion_instance attributes {argument_count = 2 : i64, argument_formal_paths = ["top.p.x", "top.p.y"], argument_formal_symbols = [@s1.$root::@s3.top::@s4.top::@s16.p::@s17.x, @s1.$root::@s3.top::@s4.top::@s16.p::@s18.y], argument_kinds = array<i64: 0, 0>, has_expanded_body = true, is_recursive_property = false, is_signed = false, local_variable_count = 0 : i64, local_variable_has_initializer = array<i64>, local_variable_paths = [], local_variable_symbols = [], node_id = 27 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 39, "tmp_sva_formal.sv", 8, 40, "">, referenced_path = "top.p", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s16.p, semantic_type = !obelisk.property, source_end_column = 40 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 39, "tmp_sva_formal.sv", 8, 40, "">} {
                    obelisk.sv.assertion.binary attributes {node_id = 28 : i64, operator_kind = 12 : i32, operator_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 7, "tmp_sva_formal.sv", 6, 10, "">, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 5, "tmp_sva_formal.sv", 6, 15, "">, source_end_column = 15 : i64, source_end_line = 6 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 5, "tmp_sva_formal.sv", 6, 15, "">} {
                      obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 29 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 5, "tmp_sva_formal.sv", 6, 6, "">, repetition_is_unbounded = false, source_end_column = 6 : i64, source_end_line = 6 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 5, "tmp_sva_formal.sv", 6, 6, "">} {
                        obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 30 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 5, "tmp_sva_formal.sv", 6, 6, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 6 : i64, source_end_line = 6 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 5, "tmp_sva_formal.sv", 6, 6, "">} {
                        }
                      }
                      obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 31 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 11, "tmp_sva_formal.sv", 6, 15, "">, repetition_is_unbounded = false, source_end_column = 15 : i64, source_end_line = 6 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 11, "tmp_sva_formal.sv", 6, 15, "">} {
                        obelisk.sv.expression.assertion_instance attributes {argument_count = 2 : i64, argument_formal_paths = ["top.s.x", "top.s.y"], argument_formal_symbols = [@s1.$root::@s3.top::@s4.top::@s13.s::@s14.x, @s1.$root::@s3.top::@s4.top::@s13.s::@s15.y], argument_kinds = array<i64: 0, 0>, has_expanded_body = true, is_recursive_property = false, is_signed = false, local_variable_count = 0 : i64, local_variable_has_initializer = array<i64>, local_variable_paths = [], local_variable_symbols = [], node_id = 32 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 11, "tmp_sva_formal.sv", 6, 12, "">, referenced_path = "top.s", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s13.s, semantic_type = !obelisk.sequence, source_end_column = 12 : i64, source_end_line = 6 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 11, "tmp_sva_formal.sv", 6, 12, "">} {
                          obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 9, "tmp_sva_formal.sv", 3, 10, "">}], node_id = 33 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 5, "tmp_sva_formal.sv", 3, 12, "">, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 5, "tmp_sva_formal.sv", 3, 12, "">} {
                            obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 34 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 5, "tmp_sva_formal.sv", 3, 6, "">, repetition_is_unbounded = false, source_end_column = 6 : i64, source_end_line = 3 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 5, "tmp_sva_formal.sv", 3, 6, "">} {
                              obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 35 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 5, "tmp_sva_formal.sv", 3, 6, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 6 : i64, source_end_line = 3 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 5, "tmp_sva_formal.sv", 3, 6, "">} {
                              }
                            }
                            obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 36 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 11, "tmp_sva_formal.sv", 3, 12, "">, repetition_is_unbounded = false, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 11, "tmp_sva_formal.sv", 3, 12, "">} {
                              obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 37 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 11, "tmp_sva_formal.sv", 3, 12, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 3, 11, "tmp_sva_formal.sv", 3, 12, "">} {
                              }
                            }
                          }
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 38 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 13, "tmp_sva_formal.sv", 6, 14, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 14 : i64, source_end_line = 6 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 6, 13, "tmp_sva_formal.sv", 6, 14, "">} {
                          }
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 39 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 33, "tmp_sva_formal.sv", 2, 34, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 34 : i64, source_end_line = 2 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 2, 33, "tmp_sva_formal.sv", 2, 34, "">} {
                          }
                        }
                      }
                    }
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 40 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 41, "tmp_sva_formal.sv", 8, 42, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 42 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 41, "tmp_sva_formal.sv", 8, 42, "">} {
                    }
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 41 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 33, "tmp_sva_formal.sv", 5, 34, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 34 : i64, source_end_line = 5 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 5, 33, "tmp_sva_formal.sv", 5, 34, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.empty attributes {node_id = 42 : i64, original_source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 44, "tmp_sva_formal.sv", 8, 45, "">, source_end_column = 45 : i64, source_end_line = 8 : i64, source_file = "tmp_sva_formal.sv", source_range = !obelisk.source_range<"tmp_sva_formal.sv", 8, 44, "tmp_sva_formal.sv", 8, 45, "">} {
              }
            }
          }
        }
      }
    }
  }
}


// The expanded property body substitutes p(a)'s explicit a/default c, then
// the nested s(c)'s explicit c/default b. Retained actual/default children are
// semantic inventory and must not be evaluated again.
// CHECK-LABEL: obelisk_sim.func private @unit_0(
// CHECK-SAME: %[[CLK:[^:]+]]: !obelisk_sim.ref<!obelisk_sim.logic<1>>
// CHECK-SAME: %[[A:[^:]+]]: !obelisk_sim.ref<!obelisk_sim.logic<1>>
// CHECK-SAME: %[[B:[^:]+]]: !obelisk_sim.ref<!obelisk_sim.logic<1>>
// CHECK-SAME: %[[C:[^:]+]]: !obelisk_sim.ref<!obelisk_sim.logic<1>>
// CHECK: obelisk_sim.assert.sampled_read {{.*}} from %[[C]]
// CHECK: obelisk_sim.assert.sampled_read {{.*}} from %[[B]]
// CHECK: obelisk_sim.assert.sampled_read {{.*}} from %[[A]]
// CHECK-NOT: obelisk_sim.assert.sampled_read
