// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' --encode-obelisk-sim-to-bytecode='vpi=off' | FileCheck %s --check-prefix=BYTECODE
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' --convert-obelisk-sim-processes-to-llvm-coroutines | FileCheck %s --check-prefix=NATIVE

module attributes {llvm.data_layout = "e-m:e-p:64:64-i64:64-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  obelisk.sv.symbol.definition attributes {definition_kind = 1 : i32, hierarchical_name = "bus_if", name = "bus_if", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 3, 13, "">, source_end_column = 13 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 3, 13, "">, sym_name = "s0.bus_if"} {
  }
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 1 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 4, 1, "../../../../tmp/vif_containers.sv", 27, 10, "">, source_end_column = 10 : i64, source_end_line = 27 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 4, 1, "../../../../tmp/vif_containers.sv", 27, 10, "">, sym_name = "s1.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 2 : i64, sym_name = "s2.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 28, 1, "">, source_end_column = 1 : i64, source_end_line = 28 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 28, 1, "">, sym_name = "s3"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 4, 8, "../../../../tmp/vif_containers.sv", 4, 8, "">, referenced_path = "top", referenced_symbol = @s1.top, source_end_column = 8 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 4, 8, "../../../../tmp/vif_containers.sv", 4, 8, "">, sym_name = "s4.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 4, 1, "../../../../tmp/vif_containers.sv", 27, 10, "">, source_end_column = 10 : i64, source_end_line = 27 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 4, 1, "../../../../tmp/vif_containers.sv", 27, 10, "">, sym_name = "s5.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.instance attributes {hierarchical_name = "top.a", is_uninstantiated = false, name = "a", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 5, 10, "../../../../tmp/vif_containers.sv", 5, 13, "">, referenced_path = "bus_if", referenced_symbol = @s0.bus_if, source_end_column = 13 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 5, 10, "../../../../tmp/vif_containers.sv", 5, 13, "">, sym_name = "s6.a"} {
          obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.a", name = "bus_if", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 3, 13, "">, source_end_column = 13 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 3, 13, "">, sym_name = "s7.bus_if", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64, virtual_interface_identity = @s2.$root::@s5.top::@s6.a} {
            obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a.x", lifetime = 1 : i32, name = "x", node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 2, 7, "../../../../tmp/vif_containers.sv", 2, 8, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 8 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 2, 7, "../../../../tmp/vif_containers.sv", 2, 8, "">, sym_name = "s8.x"} {
            }
          }
        }
        obelisk.sv.symbol.instance attributes {hierarchical_name = "top.b", is_uninstantiated = false, name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 5, 15, "../../../../tmp/vif_containers.sv", 5, 18, "">, referenced_path = "bus_if", referenced_symbol = @s0.bus_if, source_end_column = 18 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 5, 15, "../../../../tmp/vif_containers.sv", 5, 18, "">, sym_name = "s9.b"} {
          obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.b", name = "bus_if", node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 3, 13, "">, source_end_column = 13 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 1, 1, "../../../../tmp/vif_containers.sv", 3, 13, "">, sym_name = "s10.bus_if", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64, virtual_interface_identity = @s2.$root::@s5.top::@s6.a} {
            obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b.x", lifetime = 1 : i32, name = "x", node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 2, 7, "../../../../tmp/vif_containers.sv", 2, 8, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 8 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 2, 7, "../../../../tmp/vif_containers.sv", 2, 8, "">, sym_name = "s11.x"} {
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.fixed", lifetime = 1 : i32, name = "fixed", node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 6, 18, "../../../../tmp/vif_containers.sv", 6, 26, "">, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 26 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 6, 18, "../../../../tmp/vif_containers.sv", 6, 26, "">, sym_name = "s12.fixed"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.dyn", lifetime = 1 : i32, name = "dyn", node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 7, 18, "../../../../tmp/vif_containers.sv", 7, 23, "">, semantic_type = !obelisk.dynarray<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 23 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 7, 18, "../../../../tmp/vif_containers.sv", 7, 23, "">, sym_name = "s13.dyn"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.queue", lifetime = 1 : i32, name = "queue", node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 8, 18, "../../../../tmp/vif_containers.sv", 8, 26, "">, semantic_type = !obelisk.queue<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, 0>, source_end_column = 26 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 8, 18, "../../../../tmp/vif_containers.sv", 8, 26, "">, sym_name = "s14.queue"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.assoc", lifetime = 1 : i32, name = "assoc", node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 9, 18, "../../../../tmp/vif_containers.sv", 9, 28, "">, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, false>, source_end_column = 28 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 9, 18, "../../../../tmp/vif_containers.sv", 9, 28, "">, sym_name = "s15.assoc"} {
        }
        obelisk.sv.symbol.subroutine attributes {hierarchical_name = "top.exchange", name = "exchange", node_id = 16 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 10, 3, "../../../../tmp/vif_containers.sv", 17, 10, "">, semantic_type = !obelisk.subroutine<(!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">) -> (), true>, source_end_column = 10 : i64, source_end_line = 17 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 10, 3, "../../../../tmp/vif_containers.sv", 17, 10, "">, subroutine_kind = 1 : i32, sym_name = "s16.exchange", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.list attributes {node_id = 17 : i64} {
            obelisk.sv.statement.expression_statement attributes {node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 5, "../../../../tmp/vif_containers.sv", 14, 11, "">, source_end_column = 11 : i64, source_end_line = 14 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 5, "../../../../tmp/vif_containers.sv", 14, 11, "">} {
              obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 19 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 5, "../../../../tmp/vif_containers.sv", 14, 10, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 10 : i64, source_end_line = 14 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 5, "../../../../tmp/vif_containers.sv", 14, 10, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 20 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 5, "../../../../tmp/vif_containers.sv", 14, 6, "">, referenced_path = "top.exchange.o", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange::@s18.o, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 6 : i64, source_end_line = 14 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 5, "../../../../tmp/vif_containers.sv", 14, 6, "">} {
                }
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 21 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 9, "../../../../tmp/vif_containers.sv", 14, 10, "">, referenced_path = "top.exchange.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange::@s17.i, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 10 : i64, source_end_line = 14 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 14, 9, "../../../../tmp/vif_containers.sv", 14, 10, "">} {
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 22 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 5, "../../../../tmp/vif_containers.sv", 15, 12, "">, source_end_column = 12 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 5, "../../../../tmp/vif_containers.sv", 15, 12, "">} {
              obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 5, "../../../../tmp/vif_containers.sv", 15, 11, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 11 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 5, "../../../../tmp/vif_containers.sv", 15, 11, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 24 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 5, "../../../../tmp/vif_containers.sv", 15, 7, "">, referenced_path = "top.exchange.io", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange::@s19.io, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 7 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 5, "../../../../tmp/vif_containers.sv", 15, 7, "">} {
                }
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 25 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 10, "../../../../tmp/vif_containers.sv", 15, 11, "">, referenced_path = "top.exchange.r", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange::@s20.r, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 11 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 15, 10, "../../../../tmp/vif_containers.sv", 15, 11, "">} {
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 26 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 5, "../../../../tmp/vif_containers.sv", 16, 11, "">, source_end_column = 11 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 5, "../../../../tmp/vif_containers.sv", 16, 11, "">} {
              obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 27 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 5, "../../../../tmp/vif_containers.sv", 16, 10, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 10 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 5, "../../../../tmp/vif_containers.sv", 16, 10, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 28 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 5, "../../../../tmp/vif_containers.sv", 16, 6, "">, referenced_path = "top.exchange.r", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange::@s20.r, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 6 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 5, "../../../../tmp/vif_containers.sv", 16, 6, "">} {
                }
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 29 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 9, "../../../../tmp/vif_containers.sv", 16, 10, "">, referenced_path = "top.exchange.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange::@s17.i, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 10 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 16, 9, "../../../../tmp/vif_containers.sv", 16, 10, "">} {
                }
              }
            }
          }
          obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.exchange.i", name = "i", node_id = 30 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 10, 48, "../../../../tmp/vif_containers.sv", 10, 49, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 49 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 10, 48, "../../../../tmp/vif_containers.sv", 10, 49, "">, sym_name = "s17.i"} {
          }
          obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.exchange.o", name = "o", node_id = 31 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 11, 49, "../../../../tmp/vif_containers.sv", 11, 50, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 50 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 11, 49, "../../../../tmp/vif_containers.sv", 11, 50, "">, sym_name = "s18.o"} {
          }
          obelisk.sv.symbol.formal_argument attributes {direction = 2 : i32, hierarchical_name = "top.exchange.io", name = "io", node_id = 32 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 12, 48, "../../../../tmp/vif_containers.sv", 12, 50, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 50 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 12, 48, "../../../../tmp/vif_containers.sv", 12, 50, "">, sym_name = "s19.io"} {
          }
          obelisk.sv.symbol.formal_argument attributes {direction = 3 : i32, hierarchical_name = "top.exchange.r", name = "r", node_id = 33 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 13, 46, "../../../../tmp/vif_containers.sv", 13, 47, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 47 : i64, source_end_line = 13 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 13, 46, "../../../../tmp/vif_containers.sv", 13, 47, "">, sym_name = "s20.r"} {
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 34 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 18, 3, "../../../../tmp/vif_containers.sv", 26, 6, "">, procedure_kind = 0 : i32, source_end_column = 6 : i64, source_end_line = 26 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 18, 3, "../../../../tmp/vif_containers.sv", 26, 6, "">, sym_name = "s21", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {node_id = 35 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 18, 11, "../../../../tmp/vif_containers.sv", 26, 6, "">, source_end_column = 6 : i64, source_end_line = 26 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 18, 11, "../../../../tmp/vif_containers.sv", 26, 6, "">} {
            obelisk.sv.statement.list attributes {node_id = 36 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 18, 11, "../../../../tmp/vif_containers.sv", 26, 6, "">, source_end_column = 6 : i64, source_end_line = 26 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 18, 11, "../../../../tmp/vif_containers.sv", 26, 6, "">} {
              obelisk.sv.statement.expression_statement attributes {node_id = 37 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 18, "">, source_end_column = 18 : i64, source_end_line = 19 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 18, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 38 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 17, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 17 : i64, source_end_line = 19 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 17, "">} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 39 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 13, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 13 : i64, source_end_line = 19 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 13, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 40 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 10, "">, referenced_path = "top.fixed", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s12.fixed, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 10 : i64, source_end_line = 19 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 5, "../../../../tmp/vif_containers.sv", 19, 10, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 41 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 11, "../../../../tmp/vif_containers.sv", 19, 12, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 12 : i64, source_end_line = 19 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 11, "../../../../tmp/vif_containers.sv", 19, 12, "">} {
                    }
                  }
                  obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 42 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 16, "../../../../tmp/vif_containers.sv", 19, 17, "">, referenced_path = "top.a", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 17 : i64, source_end_line = 19 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 19, 16, "../../../../tmp/vif_containers.sv", 19, 17, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 43 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 18, "">, source_end_column = 18 : i64, source_end_line = 20 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 18, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 44 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 17, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 17 : i64, source_end_line = 20 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 17, "">} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 45 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 13, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 13 : i64, source_end_line = 20 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 13, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 46 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 10, "">, referenced_path = "top.fixed", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s12.fixed, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 10 : i64, source_end_line = 20 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 5, "../../../../tmp/vif_containers.sv", 20, 10, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 47 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 11, "../../../../tmp/vif_containers.sv", 20, 12, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 12 : i64, source_end_line = 20 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 11, "../../../../tmp/vif_containers.sv", 20, 12, "">} {
                    }
                  }
                  obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 48 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 16, "../../../../tmp/vif_containers.sv", 20, 17, "">, referenced_path = "top.b", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s9.b, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 17 : i64, source_end_line = 20 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 20, 16, "../../../../tmp/vif_containers.sv", 20, 17, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 49 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 5, "../../../../tmp/vif_containers.sv", 21, 18, "">, source_end_column = 18 : i64, source_end_line = 21 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 5, "../../../../tmp/vif_containers.sv", 21, 18, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 50 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 5, "../../../../tmp/vif_containers.sv", 21, 17, "">, semantic_type = !obelisk.dynarray<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 17 : i64, source_end_line = 21 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 5, "../../../../tmp/vif_containers.sv", 21, 17, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 51 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 5, "../../../../tmp/vif_containers.sv", 21, 8, "">, referenced_path = "top.dyn", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s13.dyn, semantic_type = !obelisk.dynarray<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 8 : i64, source_end_line = 21 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 5, "../../../../tmp/vif_containers.sv", 21, 8, "">} {
                  }
                  obelisk.sv.expression.new_array attributes {is_signed = false, node_id = 52 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 11, "../../../../tmp/vif_containers.sv", 21, 17, "">, semantic_type = !obelisk.dynarray<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 17 : i64, source_end_line = 21 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 11, "../../../../tmp/vif_containers.sv", 21, 17, "">} {
                    obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 53 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 15, "../../../../tmp/vif_containers.sv", 21, 16, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 16 : i64, source_end_line = 21 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 21, 15, "../../../../tmp/vif_containers.sv", 21, 16, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 54 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 23, "">, source_end_column = 23 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 23, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 55 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 22, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 22 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 22, "">} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 56 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 11, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 11 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 11, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 57 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 8, "">, referenced_path = "top.dyn", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s13.dyn, semantic_type = !obelisk.dynarray<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 8 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 5, "../../../../tmp/vif_containers.sv", 22, 8, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 58 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 9, "../../../../tmp/vif_containers.sv", 22, 10, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 9, "../../../../tmp/vif_containers.sv", 22, 10, "">} {
                    }
                  }
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 59 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 14, "../../../../tmp/vif_containers.sv", 22, 22, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 22 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 14, "../../../../tmp/vif_containers.sv", 22, 22, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 60 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 14, "../../../../tmp/vif_containers.sv", 22, 19, "">, referenced_path = "top.fixed", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s12.fixed, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 19 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 14, "../../../../tmp/vif_containers.sv", 22, 19, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 61 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 20, "../../../../tmp/vif_containers.sv", 22, 21, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 21 : i64, source_end_line = 22 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 22, 20, "../../../../tmp/vif_containers.sv", 22, 21, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 62 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 5, "../../../../tmp/vif_containers.sv", 23, 24, "">, source_end_column = 24 : i64, source_end_line = 23 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 5, "../../../../tmp/vif_containers.sv", 23, 24, "">} {
                obelisk.sv.expression.call attributes {argument_count = 2 : i64, callee_name = "push_back", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 63 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 5, "../../../../tmp/vif_containers.sv", 23, 23, "">, semantic_type = !obelisk.void, source_end_column = 23 : i64, source_end_line = 23 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 5, "../../../../tmp/vif_containers.sv", 23, 23, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 64 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 5, "../../../../tmp/vif_containers.sv", 23, 10, "">, referenced_path = "top.queue", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s14.queue, semantic_type = !obelisk.queue<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, 0>, source_end_column = 10 : i64, source_end_line = 23 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 5, "../../../../tmp/vif_containers.sv", 23, 10, "">} {
                  }
                  obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 65 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 21, "../../../../tmp/vif_containers.sv", 23, 22, "">, referenced_path = "top.a", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 22 : i64, source_end_line = 23 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 23, 21, "../../../../tmp/vif_containers.sv", 23, 22, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 66 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 18, "">, source_end_column = 18 : i64, source_end_line = 24 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 18, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 67 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 17, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 17 : i64, source_end_line = 24 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 17, "">} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 68 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 13, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 13 : i64, source_end_line = 24 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 13, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 69 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 10, "">, referenced_path = "top.assoc", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s15.assoc, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, false>, source_end_column = 10 : i64, source_end_line = 24 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 5, "../../../../tmp/vif_containers.sv", 24, 10, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, node_id = 70 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 11, "../../../../tmp/vif_containers.sv", 24, 12, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 12 : i64, source_end_line = 24 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 11, "../../../../tmp/vif_containers.sv", 24, 12, "">} {
                    }
                  }
                  obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 71 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 16, "../../../../tmp/vif_containers.sv", 24, 17, "">, referenced_path = "top.b", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s9.b, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 17 : i64, source_end_line = 24 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 24, 16, "../../../../tmp/vif_containers.sv", 24, 17, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 72 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 5, "../../../../tmp/vif_containers.sv", 25, 52, "">, source_end_column = 52 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 5, "../../../../tmp/vif_containers.sv", 25, 52, "">} {
                obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "exchange", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = true, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = false, node_id = 73 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 5, "../../../../tmp/vif_containers.sv", 25, 51, "">, referenced_path = "top.exchange", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s16.exchange, semantic_type = !obelisk.void, source_end_column = 51 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 5, "../../../../tmp/vif_containers.sv", 25, 51, "">, subroutine_kind = 1 : i32} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 74 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 14, "../../../../tmp/vif_containers.sv", 25, 22, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 22 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 14, "../../../../tmp/vif_containers.sv", 25, 22, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 75 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 14, "../../../../tmp/vif_containers.sv", 25, 19, "">, referenced_path = "top.fixed", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s12.fixed, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 19 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 14, "../../../../tmp/vif_containers.sv", 25, 19, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 76 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 20, "../../../../tmp/vif_containers.sv", 25, 21, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 21 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 20, "../../../../tmp/vif_containers.sv", 25, 21, "">} {
                    }
                  }
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 77 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 32, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 32 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 32, "">} {
                    obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 78 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 32, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 32 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 32, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 79 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 29, "">, referenced_path = "top.fixed", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s12.fixed, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 29 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 29, "">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 80 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 30, "../../../../tmp/vif_containers.sv", 25, 31, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 30, "../../../../tmp/vif_containers.sv", 25, 31, "">} {
                      }
                    }
                    obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 81 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 32, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 32 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 24, "../../../../tmp/vif_containers.sv", 25, 32, "">} {
                    }
                  }
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 82 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 40, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 40 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 40, "">} {
                    obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 83 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 40, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 40 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 40, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 84 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 37, "">, referenced_path = "top.dyn", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s13.dyn, semantic_type = !obelisk.dynarray<!obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">>, source_end_column = 37 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 37, "">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 85 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 38, "../../../../tmp/vif_containers.sv", 25, 39, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 39 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 38, "../../../../tmp/vif_containers.sv", 25, 39, "">} {
                      }
                    }
                    obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 86 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 40, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 40 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 34, "../../../../tmp/vif_containers.sv", 25, 40, "">} {
                    }
                  }
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 87 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 42, "../../../../tmp/vif_containers.sv", 25, 50, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 50 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 42, "../../../../tmp/vif_containers.sv", 25, 50, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 88 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 42, "../../../../tmp/vif_containers.sv", 25, 47, "">, referenced_path = "top.assoc", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s15.assoc, semantic_type = !obelisk.assoc<!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, false>, source_end_column = 47 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 42, "../../../../tmp/vif_containers.sv", 25, 47, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, node_id = 89 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 48, "../../../../tmp/vif_containers.sv", 25, 49, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 25 : i64, source_file = "../../../../tmp/vif_containers.sv", source_range = !obelisk.source_range<"../../../../tmp/vif_containers.sv", 25, 48, "../../../../tmp/vif_containers.sv", 25, 49, "">} {
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


// CHECK-DAG: !obelisk_sim.dynamic_array<!obelisk_sim.virtual_interface
// CHECK-DAG: !obelisk_sim.queue<!obelisk_sim.virtual_interface
// CHECK-DAG: !obelisk_sim.assoc_array<i32, !obelisk_sim.virtual_interface
// CHECK-DAG: !obelisk_sim.unpacked_array<0 : 1 x !obelisk_sim.virtual_interface
// CHECK-LABEL: obelisk_sim.func private @unit_0(
// Input is a value, output is default-initialized and copied out, inout uses
// an isolated copy-in/out temporary, and ref remains a live argument reference
// to the selected container element.
// CHECK-SAME: %arg1: !obelisk_sim.virtual_interface
// CHECK-SAME: %arg3: !obelisk_sim.ref<!obelisk_sim.virtual_interface
// CHECK-SAME: %arg5: !obelisk_sim.ref<!obelisk_sim.virtual_interface
// CHECK-SAME: %arg6: !obelisk_sim.argument_ref<!obelisk_sim.virtual_interface
// CHECK: [[REF:%.*]] = obelisk_sim.argument_ref.load %arg6
// CHECK: obelisk_sim.argument_ref.store %arg1 to %arg6
// CHECK: obelisk_sim.ref.store %arg1 to %arg3
// CHECK: obelisk_sim.ref.store [[REF]] to %arg5
// CHECK-LABEL: obelisk_sim.func private @unit_1(
// Distinct elaborated instances and the output formal's null default must not
// be commoned merely because bind/null are pure handle constants.
// CHECK: obelisk_sim.virtual_interface.null
// CHECK: obelisk_sim.virtual_interface.bind 2
// CHECK: obelisk_sim.virtual_interface.bind 3
// CHECK: obelisk_sim.container.create {{.*}}bit_width = 64 : i64{{.*}}element_kind = 1 : i32
// CHECK: obelisk_sim.container.write
// CHECK: obelisk_sim.assoc.write
// CHECK: obelisk_sim.reference_path.index
// CHECK: obelisk_sim.reference_path.assoc
// CHECK: [[OUTNULL:%.*]] = obelisk_sim.virtual_interface.null
// CHECK: obelisk_sim.task.call @unit_0({{.*}}, [[OUTNULL]], {{.*}})
// CHECK: obelisk_sim.argument_ref.store
// CHECK-NOT: obelisk.sv.
// BYTECODE: obelisk.bytecode.image = array<i8:
// BYTECODE: obelisk.execution.state_bits = 384 : i64
// NATIVE: llvm.func
// NATIVE-NOT: obelisk_sim.virtual_interface
