// RUN: not obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' -o /dev/null 2>&1 | FileCheck %s

// A combined bounded consequent may branch temporally, but a nested
// first_match needs per-obligation priority state and remains diagnosed.
// CHECK: error: combined branching implication/followed-by currently requires bounded consequent alternatives without retained nested first_match boundaries, vacuous alternatives, or match items and at most 256 antecedent/consequent alternative pairs

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "combined_temporal_invalid", name = "combined_temporal_invalid", node_id = 0 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 1, "combined-temporal-invalid.sv", 4, 10, "">, source_end_column = 10 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 1, "combined-temporal-invalid.sv", 4, 10, "">, sym_name = "s0.combined_temporal_invalid"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 1, "combined-temporal-invalid.sv", 5, 1, "">, source_end_column = 1 : i64, source_end_line = 5 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 1, "combined-temporal-invalid.sv", 5, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "combined_temporal_invalid", is_uninstantiated = false, name = "combined_temporal_invalid", node_id = 3 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 8, "combined-temporal-invalid.sv", 1, 8, "">, referenced_path = "combined_temporal_invalid", referenced_symbol = @s0.combined_temporal_invalid, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 8, "combined-temporal-invalid.sv", 1, 8, "">, sym_name = "s3.combined_temporal_invalid"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "combined_temporal_invalid", name = "combined_temporal_invalid", node_id = 4 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 1, "combined-temporal-invalid.sv", 4, 10, "">, source_end_column = 10 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 1, "combined-temporal-invalid.sv", 4, 10, "">, sym_name = "s4.combined_temporal_invalid", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_invalid.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 46, "combined-temporal-invalid.sv", 1, 49, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 49 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 46, "combined-temporal-invalid.sv", 1, 49, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_invalid.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 46, "combined-temporal-invalid.sv", 1, 49, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 49 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 46, "combined-temporal-invalid.sv", 1, 49, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_invalid.a", name = "a", node_id = 7 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 51, "combined-temporal-invalid.sv", 1, 52, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 52 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 51, "combined-temporal-invalid.sv", 1, 52, "">, sym_name = "s7.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_invalid.a", lifetime = 1 : i32, name = "a", node_id = 8 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 51, "combined-temporal-invalid.sv", 1, 52, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 52 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 51, "combined-temporal-invalid.sv", 1, 52, "">, sym_name = "s8.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_invalid.b", name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 54, "combined-temporal-invalid.sv", 1, 55, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 55 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 54, "combined-temporal-invalid.sv", 1, 55, "">, sym_name = "s9.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_invalid.b", lifetime = 1 : i32, name = "b", node_id = 10 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 54, "combined-temporal-invalid.sv", 1, 55, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 55 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 54, "combined-temporal-invalid.sv", 1, 55, "">, sym_name = "s10.b"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_invalid.c", name = "c", node_id = 11 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 57, "combined-temporal-invalid.sv", 1, 58, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 58 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 57, "combined-temporal-invalid.sv", 1, 58, "">, sym_name = "s11.c"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_invalid.c", lifetime = 1 : i32, name = "c", node_id = 12 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 57, "combined-temporal-invalid.sv", 1, 58, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 58 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 57, "combined-temporal-invalid.sv", 1, 58, "">, sym_name = "s12.c"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_invalid.d", name = "d", node_id = 13 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 60, "combined-temporal-invalid.sv", 1, 61, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 61 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 60, "combined-temporal-invalid.sv", 1, 61, "">, sym_name = "s13.d"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_invalid.d", lifetime = 1 : i32, name = "d", node_id = 14 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 60, "combined-temporal-invalid.sv", 1, 61, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 61 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 1, 60, "combined-temporal-invalid.sv", 1, 61, "">, sym_name = "s14.d"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "combined_temporal_invalid", node_id = 15 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 3, "combined-temporal-invalid.sv", 3, 59, "">, procedure_kind = 2 : i32, source_end_column = 59 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 3, "combined-temporal-invalid.sv", 3, 59, "">, sym_name = "s15", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 16 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 3, "combined-temporal-invalid.sv", 3, 59, "">, source_end_column = 59 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 3, "combined-temporal-invalid.sv", 3, 59, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 17 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 20, "combined-temporal-invalid.sv", 3, 57, "">, source_end_column = 57 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 20, "combined-temporal-invalid.sv", 3, 57, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 18 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 22, "combined-temporal-invalid.sv", 2, 33, "">, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 22, "combined-temporal-invalid.sv", 2, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 19 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 30, "combined-temporal-invalid.sv", 2, 33, "">, referenced_path = "combined_temporal_invalid.clk", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 2, 30, "combined-temporal-invalid.sv", 2, 33, "">} {
                }
              }
              obelisk.sv.assertion.binary attributes {node_id = 20 : i64, operator_kind = 11 : i32, operator_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 14, "combined-temporal-invalid.sv", 3, 17, "">, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 5, "combined-temporal-invalid.sv", 3, 57, "">, source_end_column = 57 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 5, "combined-temporal-invalid.sv", 3, 57, "">} {
                obelisk.sv.assertion.binary attributes {node_id = 21 : i64, operator_kind = 1 : i32, operator_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 8, "combined-temporal-invalid.sv", 3, 10, "">, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 5, "combined-temporal-invalid.sv", 3, 13, "">, source_end_column = 13 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 5, "combined-temporal-invalid.sv", 3, 13, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 22 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 6, "combined-temporal-invalid.sv", 3, 7, "">, repetition_is_unbounded = false, source_end_column = 7 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 6, "combined-temporal-invalid.sv", 3, 7, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 6, "combined-temporal-invalid.sv", 3, 7, "">, referenced_path = "combined_temporal_invalid.a", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 7 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 6, "combined-temporal-invalid.sv", 3, 7, "">} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 24 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 11, "combined-temporal-invalid.sv", 3, 12, "">, repetition_is_unbounded = false, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 11, "combined-temporal-invalid.sv", 3, 12, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 25 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 11, "combined-temporal-invalid.sv", 3, 12, "">, referenced_path = "combined_temporal_invalid.b", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 11, "combined-temporal-invalid.sv", 3, 12, "">} {
                    }
                  }
                }
                obelisk.sv.assertion.binary attributes {node_id = 26 : i64, operator_kind = 1 : i32, operator_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 44, "combined-temporal-invalid.sv", 3, 46, "">, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 18, "combined-temporal-invalid.sv", 3, 57, "">, source_end_column = 57 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 18, "combined-temporal-invalid.sv", 3, 57, "">} {
                  obelisk.sv.assertion.first_match attributes {match_item_count = 0 : i64, node_id = 27 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 19, "combined-temporal-invalid.sv", 3, 43, "">, source_end_column = 43 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 19, "combined-temporal-invalid.sv", 3, 43, "">} {
                    obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 2 : i64, min = 1 : i64, source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 36, "combined-temporal-invalid.sv", 3, 39, "">}], node_id = 28 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 31, "combined-temporal-invalid.sv", 3, 42, "">, source_end_column = 42 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 31, "combined-temporal-invalid.sv", 3, 42, "">} {
                      obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 29 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 31, "combined-temporal-invalid.sv", 3, 32, "">, repetition_is_unbounded = false, source_end_column = 32 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 31, "combined-temporal-invalid.sv", 3, 32, "">} {
                        obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 30 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 31, "combined-temporal-invalid.sv", 3, 32, "">, referenced_path = "combined_temporal_invalid.c", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 32 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 31, "combined-temporal-invalid.sv", 3, 32, "">} {
                        }
                      }
                      obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 31 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 41, "combined-temporal-invalid.sv", 3, 42, "">, repetition_is_unbounded = false, source_end_column = 42 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 41, "combined-temporal-invalid.sv", 3, 42, "">} {
                        obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 32 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 41, "combined-temporal-invalid.sv", 3, 42, "">, referenced_path = "combined_temporal_invalid.d", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s14.d, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 42 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 41, "combined-temporal-invalid.sv", 3, 42, "">} {
                        }
                      }
                    }
                  }
                  obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 3 : i64, min = 3 : i64, source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 52, "combined-temporal-invalid.sv", 3, 53, "">}], node_id = 33 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 47, "combined-temporal-invalid.sv", 3, 56, "">, source_end_column = 56 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 47, "combined-temporal-invalid.sv", 3, 56, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 34 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 48, "combined-temporal-invalid.sv", 3, 49, "">, repetition_is_unbounded = false, source_end_column = 49 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 48, "combined-temporal-invalid.sv", 3, 49, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 35 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 48, "combined-temporal-invalid.sv", 3, 49, "">, referenced_path = "combined_temporal_invalid.c", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 49 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 48, "combined-temporal-invalid.sv", 3, 49, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 36 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 54, "combined-temporal-invalid.sv", 3, 55, "">, repetition_is_unbounded = false, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 54, "combined-temporal-invalid.sv", 3, 55, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 37 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 54, "combined-temporal-invalid.sv", 3, 55, "">, referenced_path = "combined_temporal_invalid.d", referenced_symbol = @s1.$root::@s3.combined_temporal_invalid::@s4.combined_temporal_invalid::@s14.d, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 54, "combined-temporal-invalid.sv", 3, 55, "">} {
                      }
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.empty attributes {node_id = 38 : i64, original_source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 58, "combined-temporal-invalid.sv", 3, 59, "">, source_end_column = 59 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-invalid.sv", source_range = !obelisk.source_range<"combined-temporal-invalid.sv", 3, 58, "combined-temporal-invalid.sv", 3, 59, "">} {
            }
          }
        }
      }
    }
  }
}
