// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: sed '/symbol.procedural_block/s/procedure_kind = 0/procedure_kind = 3/' %s | obelisk-opt '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s --check-prefix=SENS
// RUN: sed 's/virtual_interface_call_import, //g' %s | not obelisk-opt '--lower-obelisk-to-sim=opt-level=0' 2>&1 | FileCheck %s --check-prefix=MODPORT

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 1 : i32, hierarchical_name = "bus_if", name = "bus_if", node_id = 0 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, source_end_column = 13 : i64, source_end_line = 6 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, sym_name = "s0.bus_if"} {
  }
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 1 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 7, 1, "tmp_vif_call_probe.sv", 16, 10, "">, source_end_column = 10 : i64, source_end_line = 16 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 7, 1, "tmp_vif_call_probe.sv", 16, 10, "">, sym_name = "s1.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 2 : i64, sym_name = "s2.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 3 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 17, 1, "">, source_end_column = 1 : i64, source_end_line = 17 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 17, 1, "">, sym_name = "s3"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 7, 8, "tmp_vif_call_probe.sv", 7, 8, "">, referenced_path = "top", referenced_symbol = @s1.top, source_end_column = 8 : i64, source_end_line = 7 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 7, 8, "tmp_vif_call_probe.sv", 7, 8, "">, sym_name = "s4.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 5 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 7, 1, "tmp_vif_call_probe.sv", 16, 10, "">, source_end_column = 10 : i64, source_end_line = 16 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 7, 1, "tmp_vif_call_probe.sv", 16, 10, "">, sym_name = "s5.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.instance attributes {hierarchical_name = "top.a", is_uninstantiated = false, name = "a", node_id = 6 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 8, 10, "tmp_vif_call_probe.sv", 8, 13, "">, referenced_path = "bus_if", referenced_symbol = @s0.bus_if, source_end_column = 13 : i64, source_end_line = 8 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 8, 10, "tmp_vif_call_probe.sv", 8, 13, "">, sym_name = "s6.a"} {
          obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.a", name = "bus_if", node_id = 7 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, source_end_column = 13 : i64, source_end_line = 6 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, sym_name = "s7.bus_if", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64, virtual_interface_identity = @s2.$root::@s5.top::@s6.a} {
            obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a.x", lifetime = 1 : i32, name = "x", node_id = 8 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 2, 7, "tmp_vif_call_probe.sv", 2, 8, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 8 : i64, source_end_line = 2 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 2, 7, "tmp_vif_call_probe.sv", 2, 8, "">, sym_name = "s8.x"} {
            }
            obelisk.sv.symbol.subroutine attributes {default_lifetime = 1 : i32, hierarchical_name = "top.a.get", name = "get", node_id = 9 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 3, "tmp_vif_call_probe.sv", 3, 63, "">, return_variable_path = "top.a.get.get", return_variable_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s9.get::@s11.get, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>) -> !obelisk.integral<32, true, false, 31 : 0, int>, false>, source_end_column = 63 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 3, "tmp_vif_call_probe.sv", 3, 63, "">, subroutine_kind = 0 : i32, sym_name = "s9.get", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
              obelisk.sv.statement.return attributes {node_id = 10 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 36, "tmp_vif_call_probe.sv", 3, 51, "">, source_end_column = 51 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 36, "tmp_vif_call_probe.sv", 3, 51, "">} {
                obelisk.sv.expression.binary_op attributes {is_signed = true, node_id = 11 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 50, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 50 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 50, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 12 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 44, "">, referenced_path = "top.a.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s8.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 44 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 44, "">} {
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 13 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 47, "tmp_vif_call_probe.sv", 3, 50, "">, referenced_path = "top.a.get.add", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s9.get::@s10.add, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 50 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 47, "tmp_vif_call_probe.sv", 3, 50, "">} {
                  }
                }
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.a.get.add", lifetime = 1 : i32, name = "add", node_id = 14 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 33, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 33 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 33, "">, sym_name = "s10.add"} {
              }
              obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a.get.get", is_compiler_generated, name = "get", node_id = 15 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 16, "tmp_vif_call_probe.sv", 3, 16, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 16 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 16, "tmp_vif_call_probe.sv", 3, 16, "">, sym_name = "s11.get"} {
              }
            }
            obelisk.sv.symbol.subroutine attributes {default_lifetime = 1 : i32, hierarchical_name = "top.a.put", name = "put", node_id = 16 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 3, "tmp_vif_call_probe.sv", 4, 65, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.integral<32, true, false, 31 : 0, int>) -> (), true>, source_end_column = 65 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 3, "tmp_vif_call_probe.sv", 4, 65, "">, subroutine_kind = 1 : i32, sym_name = "s12.put", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
              obelisk.sv.statement.list attributes {node_id = 17 : i64} {
                obelisk.sv.statement.expression_statement attributes {node_id = 18 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 50, "">, source_end_column = 50 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 50, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 19 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 49, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 49, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 20 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 45, "">, referenced_path = "top.a.put.old", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s12.put::@s14.old, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 45 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 45, "">} {
                    }
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 21 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 48, "tmp_vif_call_probe.sv", 4, 49, "">, referenced_path = "top.a.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s8.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 48, "tmp_vif_call_probe.sv", 4, 49, "">} {
                    }
                  }
                }
                obelisk.sv.statement.expression_statement attributes {node_id = 22 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 57, "">, source_end_column = 57 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 57, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 23 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 56, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 56 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 56, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 24 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 52, "">, referenced_path = "top.a.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s8.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 52 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 52, "">} {
                    }
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 25 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 55, "tmp_vif_call_probe.sv", 4, 56, "">, referenced_path = "top.a.put.v", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s12.put::@s13.v, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 56 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 55, "tmp_vif_call_probe.sv", 4, 56, "">} {
                    }
                  }
                }
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.a.put.v", lifetime = 1 : i32, name = "v", node_id = 26 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 23, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 23 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 23, "">, sym_name = "s13.v"} {
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.a.put.old", lifetime = 1 : i32, name = "old", node_id = 27 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 39, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 39, "">, sym_name = "s14.old"} {
              }
            }
            obelisk.sv.symbol.modport attributes {hierarchical_name = "top.a.master", name = "master", node_id = 28 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 11, "tmp_vif_call_probe.sv", 5, 41, "">, source_end_column = 41 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 11, "tmp_vif_call_probe.sv", 5, 41, "">, sym_name = "s15.master"} {
              obelisk.sv.symbol.method_prototype attributes {extern_implementation_count = 0 : i64, extern_implementation_paths = [], extern_implementation_symbols = [], hierarchical_name = "top.a.master.get", is_modport_import, name = "get", node_id = 29 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 25, "tmp_vif_call_probe.sv", 5, 28, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>) -> !obelisk.integral<32, true, false, 31 : 0, int>, false>, source_end_column = 28 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 25, "tmp_vif_call_probe.sv", 5, 28, "">, subroutine_kind = 0 : i32, subroutine_path = "top.a.get", subroutine_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s9.get, sym_name = "s16.get"} {
                obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.a.master.get.add", lifetime = 1 : i32, name = "add", node_id = 30 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 30, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 30 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 30, "">, sym_name = "s17.add"} {
                }
              }
              obelisk.sv.symbol.method_prototype attributes {extern_implementation_count = 0 : i64, extern_implementation_paths = [], extern_implementation_symbols = [], hierarchical_name = "top.a.master.put", is_modport_import, name = "put", node_id = 31 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 37, "tmp_vif_call_probe.sv", 5, 40, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.integral<32, true, false, 31 : 0, int>) -> (), true>, source_end_column = 40 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 37, "tmp_vif_call_probe.sv", 5, 40, "">, subroutine_kind = 1 : i32, subroutine_path = "top.a.put", subroutine_symbol = @s2.$root::@s4.top::@s5.top::@s6.a::@s7.bus_if::@s12.put, sym_name = "s18.put"} {
                obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.a.master.put.v", lifetime = 1 : i32, name = "v", node_id = 32 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 22, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 22 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 22, "">, sym_name = "s19.v"} {
                }
                obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.a.master.put.old", lifetime = 1 : i32, name = "old", node_id = 33 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 36, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 36 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 36, "">, sym_name = "s20.old"} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.instance attributes {hierarchical_name = "top.b", is_uninstantiated = false, name = "b", node_id = 34 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 8, 15, "tmp_vif_call_probe.sv", 8, 18, "">, referenced_path = "bus_if", referenced_symbol = @s0.bus_if, source_end_column = 18 : i64, source_end_line = 8 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 8, 15, "tmp_vif_call_probe.sv", 8, 18, "">, sym_name = "s21.b"} {
          obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.b", name = "bus_if", node_id = 35 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, source_end_column = 13 : i64, source_end_line = 6 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, sym_name = "s22.bus_if", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64, virtual_interface_identity = @s2.$root::@s5.top::@s6.a} {
            obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b.x", lifetime = 1 : i32, name = "x", node_id = 36 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 2, 7, "tmp_vif_call_probe.sv", 2, 8, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 8 : i64, source_end_line = 2 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 2, 7, "tmp_vif_call_probe.sv", 2, 8, "">, sym_name = "s23.x"} {
            }
            obelisk.sv.symbol.subroutine attributes {default_lifetime = 1 : i32, hierarchical_name = "top.b.get", name = "get", node_id = 37 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 3, "tmp_vif_call_probe.sv", 3, 63, "">, return_variable_path = "top.b.get.get", return_variable_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s24.get::@s26.get, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>) -> !obelisk.integral<32, true, false, 31 : 0, int>, false>, source_end_column = 63 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 3, "tmp_vif_call_probe.sv", 3, 63, "">, subroutine_kind = 0 : i32, sym_name = "s24.get", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
              obelisk.sv.statement.return attributes {node_id = 38 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 36, "tmp_vif_call_probe.sv", 3, 51, "">, source_end_column = 51 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 36, "tmp_vif_call_probe.sv", 3, 51, "">} {
                obelisk.sv.expression.binary_op attributes {is_signed = true, node_id = 39 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 50, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 50 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 50, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 40 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 44, "">, referenced_path = "top.b.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s23.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 44 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 44, "">} {
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 41 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 47, "tmp_vif_call_probe.sv", 3, 50, "">, referenced_path = "top.b.get.add", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s24.get::@s25.add, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 50 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 47, "tmp_vif_call_probe.sv", 3, 50, "">} {
                  }
                }
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.b.get.add", lifetime = 1 : i32, name = "add", node_id = 42 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 33, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 33 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 33, "">, sym_name = "s25.add"} {
              }
              obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b.get.get", is_compiler_generated, name = "get", node_id = 43 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 16, "tmp_vif_call_probe.sv", 3, 16, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 16 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 16, "tmp_vif_call_probe.sv", 3, 16, "">, sym_name = "s26.get"} {
              }
            }
            obelisk.sv.symbol.subroutine attributes {default_lifetime = 1 : i32, hierarchical_name = "top.b.put", name = "put", node_id = 44 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 3, "tmp_vif_call_probe.sv", 4, 65, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.integral<32, true, false, 31 : 0, int>) -> (), true>, source_end_column = 65 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 3, "tmp_vif_call_probe.sv", 4, 65, "">, subroutine_kind = 1 : i32, sym_name = "s27.put", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
              obelisk.sv.statement.list attributes {node_id = 45 : i64} {
                obelisk.sv.statement.expression_statement attributes {node_id = 46 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 50, "">, source_end_column = 50 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 50, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 47 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 49, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 49, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 48 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 45, "">, referenced_path = "top.b.put.old", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s27.put::@s29.old, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 45 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 45, "">} {
                    }
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 49 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 48, "tmp_vif_call_probe.sv", 4, 49, "">, referenced_path = "top.b.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s23.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 48, "tmp_vif_call_probe.sv", 4, 49, "">} {
                    }
                  }
                }
                obelisk.sv.statement.expression_statement attributes {node_id = 50 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 57, "">, source_end_column = 57 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 57, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 51 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 56, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 56 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 56, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 52 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 52, "">, referenced_path = "top.b.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s23.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 52 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 52, "">} {
                    }
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 53 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 55, "tmp_vif_call_probe.sv", 4, 56, "">, referenced_path = "top.b.put.v", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s27.put::@s28.v, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 56 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 55, "tmp_vif_call_probe.sv", 4, 56, "">} {
                    }
                  }
                }
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.b.put.v", lifetime = 1 : i32, name = "v", node_id = 54 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 23, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 23 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 23, "">, sym_name = "s28.v"} {
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.b.put.old", lifetime = 1 : i32, name = "old", node_id = 55 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 39, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 39, "">, sym_name = "s29.old"} {
              }
            }
            obelisk.sv.symbol.modport attributes {hierarchical_name = "top.b.master", name = "master", node_id = 56 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 11, "tmp_vif_call_probe.sv", 5, 41, "">, source_end_column = 41 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 11, "tmp_vif_call_probe.sv", 5, 41, "">, sym_name = "s30.master"} {
              obelisk.sv.symbol.method_prototype attributes {extern_implementation_count = 0 : i64, extern_implementation_paths = [], extern_implementation_symbols = [], hierarchical_name = "top.b.master.get", is_modport_import, name = "get", node_id = 57 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 25, "tmp_vif_call_probe.sv", 5, 28, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>) -> !obelisk.integral<32, true, false, 31 : 0, int>, false>, source_end_column = 28 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 25, "tmp_vif_call_probe.sv", 5, 28, "">, subroutine_kind = 0 : i32, subroutine_path = "top.b.get", subroutine_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s24.get, sym_name = "s31.get"} {
                obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.b.master.get.add", lifetime = 1 : i32, name = "add", node_id = 58 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 30, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 30 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 30, "">, sym_name = "s32.add"} {
                }
              }
              obelisk.sv.symbol.method_prototype attributes {extern_implementation_count = 0 : i64, extern_implementation_paths = [], extern_implementation_symbols = [], hierarchical_name = "top.b.master.put", is_modport_import, name = "put", node_id = 59 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 37, "tmp_vif_call_probe.sv", 5, 40, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.integral<32, true, false, 31 : 0, int>) -> (), true>, source_end_column = 40 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 37, "tmp_vif_call_probe.sv", 5, 40, "">, subroutine_kind = 1 : i32, subroutine_path = "top.b.put", subroutine_symbol = @s2.$root::@s4.top::@s5.top::@s21.b::@s22.bus_if::@s27.put, sym_name = "s33.put"} {
                obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.b.master.put.v", lifetime = 1 : i32, name = "v", node_id = 60 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 22, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 22 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 22, "">, sym_name = "s34.v"} {
                }
                obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.b.master.put.old", lifetime = 1 : i32, name = "old", node_id = 61 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 36, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 36 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 36, "">, sym_name = "s35.old"} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.vif", lifetime = 1 : i32, name = "vif", node_id = 62 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 9, 25, "tmp_vif_call_probe.sv", 9, 28, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "master">, source_end_column = 28 : i64, source_end_line = 9 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 9, 25, "tmp_vif_call_probe.sv", 9, 28, "">, sym_name = "s36.vif"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.y", lifetime = 1 : i32, name = "y", node_id = 63 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 10, 7, "tmp_vif_call_probe.sv", 10, 8, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 8 : i64, source_end_line = 10 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 10, 7, "tmp_vif_call_probe.sv", 10, 8, "">, sym_name = "s37.y"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 64 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 11, 3, "tmp_vif_call_probe.sv", 15, 6, "">, procedure_kind = 0 : i32, source_end_column = 6 : i64, source_end_line = 15 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 11, 3, "tmp_vif_call_probe.sv", 15, 6, "">, sym_name = "s38", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {node_id = 65 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 11, 11, "tmp_vif_call_probe.sv", 15, 6, "">, source_end_column = 6 : i64, source_end_line = 15 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 11, 11, "tmp_vif_call_probe.sv", 15, 6, "">} {
            obelisk.sv.statement.list attributes {node_id = 66 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 11, 11, "tmp_vif_call_probe.sv", 15, 6, "">, source_end_column = 6 : i64, source_end_line = 15 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 11, 11, "tmp_vif_call_probe.sv", 15, 6, "">} {
              obelisk.sv.statement.expression_statement attributes {node_id = 67 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 5, "tmp_vif_call_probe.sv", 12, 13, "">, source_end_column = 13 : i64, source_end_line = 12 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 5, "tmp_vif_call_probe.sv", 12, 13, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 68 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 5, "tmp_vif_call_probe.sv", 12, 12, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "master">, source_end_column = 12 : i64, source_end_line = 12 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 5, "tmp_vif_call_probe.sv", 12, 12, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 69 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 5, "tmp_vif_call_probe.sv", 12, 8, "">, referenced_path = "top.vif", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s36.vif, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "master">, source_end_column = 8 : i64, source_end_line = 12 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 5, "tmp_vif_call_probe.sv", 12, 8, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 70 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 11, "tmp_vif_call_probe.sv", 12, 12, "">, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "master">, source_end_column = 12 : i64, source_end_line = 12 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 11, "tmp_vif_call_probe.sv", 12, 12, "">} {
                    obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 71 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 11, "tmp_vif_call_probe.sv", 12, 12, "">, referenced_path = "top.a", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.a, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "">, source_end_column = 12 : i64, source_end_line = 12 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 12, 11, "tmp_vif_call_probe.sv", 12, 12, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 72 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 5, "tmp_vif_call_probe.sv", 13, 20, "">, source_end_column = 20 : i64, source_end_line = 13 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 5, "tmp_vif_call_probe.sv", 13, 20, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 73 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 5, "tmp_vif_call_probe.sv", 13, 19, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 19 : i64, source_end_line = 13 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 5, "tmp_vif_call_probe.sv", 13, 19, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 74 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 5, "tmp_vif_call_probe.sv", 13, 6, "">, referenced_path = "top.y", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s37.y, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 6 : i64, source_end_line = 13 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 5, "tmp_vif_call_probe.sv", 13, 6, "">} {
                  }
                  obelisk.sv.expression.call attributes {virtual_interface_call_import, virtual_interface_call_modport = "master", argument_count = 1 : i64, callee_name = "get", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = true, is_signed = true, is_super_class = false, is_system_call = false, node_id = 75 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 9, "tmp_vif_call_probe.sv", 13, 19, "">, referenced_path = "top.bus_if.get", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s41.get, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 19 : i64, source_end_line = 13 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 9, "tmp_vif_call_probe.sv", 13, 19, "">, subroutine_kind = 0 : i32} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 76 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 9, "tmp_vif_call_probe.sv", 13, 12, "">, referenced_path = "top.vif", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s36.vif, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "master">, source_end_column = 12 : i64, source_end_line = 13 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 9, "tmp_vif_call_probe.sv", 13, 12, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, node_id = 77 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 17, "tmp_vif_call_probe.sv", 13, 18, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 18 : i64, source_end_line = 13 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 13, 17, "tmp_vif_call_probe.sv", 13, 18, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 78 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 5, "tmp_vif_call_probe.sv", 14, 19, "">, source_end_column = 19 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 5, "tmp_vif_call_probe.sv", 14, 19, "">} {
                obelisk.sv.expression.call attributes {virtual_interface_call_import, virtual_interface_call_modport = "master", argument_count = 2 : i64, callee_name = "put", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = true, has_this_class = true, is_signed = false, is_super_class = false, is_system_call = false, node_id = 79 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 5, "tmp_vif_call_probe.sv", 14, 18, "">, referenced_path = "top.bus_if.put", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s44.put, semantic_type = !obelisk.void, source_end_column = 18 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 5, "tmp_vif_call_probe.sv", 14, 18, "">, subroutine_kind = 1 : i32} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 80 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 5, "tmp_vif_call_probe.sv", 14, 8, "">, referenced_path = "top.vif", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s36.vif, semantic_type = !obelisk.virtual_interface<@s2.$root::@s5.top::@s6.a, "master">, source_end_column = 8 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 5, "tmp_vif_call_probe.sv", 14, 8, "">} {
                  }
                  obelisk.sv.expression.integer_literal attributes {constant_value = "4", is_declared_unsized = true, is_signed = true, node_id = 81 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 13, "tmp_vif_call_probe.sv", 14, 14, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 14 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 13, "tmp_vif_call_probe.sv", 14, 14, "">} {
                  }
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 82 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 16, "tmp_vif_call_probe.sv", 14, 17, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 17 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 16, "tmp_vif_call_probe.sv", 14, 17, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 83 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 16, "tmp_vif_call_probe.sv", 14, 17, "">, referenced_path = "top.y", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s37.y, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 17 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 16, "tmp_vif_call_probe.sv", 14, 17, "">} {
                    }
                    obelisk.sv.expression.empty_argument attributes {is_signed = true, node_id = 84 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 16, "tmp_vif_call_probe.sv", 14, 17, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 17 : i64, source_end_line = 14 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 14, 16, "tmp_vif_call_probe.sv", 14, 17, "">} {
                    }
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.bus_if", is_virtual_interface_type_instance = true, name = "bus_if", node_id = 85 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, source_end_column = 13 : i64, source_end_line = 6 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 1, 1, "tmp_vif_call_probe.sv", 6, 13, "">, sym_name = "s39.bus_if", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64, virtual_interface_identity = @s2.$root::@s5.top::@s6.a} {
          obelisk.sv.symbol.variable attributes {hierarchical_name = "top.bus_if.x", lifetime = 1 : i32, name = "x", node_id = 86 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 2, 7, "tmp_vif_call_probe.sv", 2, 8, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 8 : i64, source_end_line = 2 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 2, 7, "tmp_vif_call_probe.sv", 2, 8, "">, sym_name = "s40.x"} {
          }
          obelisk.sv.symbol.subroutine attributes {default_lifetime = 1 : i32, hierarchical_name = "top.bus_if.get", name = "get", node_id = 87 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 3, "tmp_vif_call_probe.sv", 3, 63, "">, return_variable_path = "top.bus_if.get.get", return_variable_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s41.get::@s43.get, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>) -> !obelisk.integral<32, true, false, 31 : 0, int>, false>, source_end_column = 63 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 3, "tmp_vif_call_probe.sv", 3, 63, "">, subroutine_kind = 0 : i32, sym_name = "s41.get", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
            obelisk.sv.statement.return attributes {node_id = 88 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 36, "tmp_vif_call_probe.sv", 3, 51, "">, source_end_column = 51 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 36, "tmp_vif_call_probe.sv", 3, 51, "">} {
              obelisk.sv.expression.binary_op attributes {is_signed = true, node_id = 89 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 50, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 50 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 50, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 90 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 44, "">, referenced_path = "top.bus_if.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s40.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 44 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 43, "tmp_vif_call_probe.sv", 3, 44, "">} {
                }
                obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 91 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 47, "tmp_vif_call_probe.sv", 3, 50, "">, referenced_path = "top.bus_if.get.add", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s41.get::@s42.add, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 50 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 47, "tmp_vif_call_probe.sv", 3, 50, "">} {
                }
              }
            }
            obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.bus_if.get.add", lifetime = 1 : i32, name = "add", node_id = 92 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 33, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 33 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 33, "">, sym_name = "s42.add"} {
            }
            obelisk.sv.symbol.variable attributes {hierarchical_name = "top.bus_if.get.get", is_compiler_generated, name = "get", node_id = 93 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 16, "tmp_vif_call_probe.sv", 3, 16, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 16 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 16, "tmp_vif_call_probe.sv", 3, 16, "">, sym_name = "s43.get"} {
            }
          }
          obelisk.sv.symbol.subroutine attributes {default_lifetime = 1 : i32, hierarchical_name = "top.bus_if.put", name = "put", node_id = 94 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 3, "tmp_vif_call_probe.sv", 4, 65, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.integral<32, true, false, 31 : 0, int>) -> (), true>, source_end_column = 65 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 3, "tmp_vif_call_probe.sv", 4, 65, "">, subroutine_kind = 1 : i32, sym_name = "s44.put", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
            obelisk.sv.statement.list attributes {node_id = 95 : i64} {
              obelisk.sv.statement.expression_statement attributes {node_id = 96 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 50, "">, source_end_column = 50 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 50, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 97 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 49, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 49, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 98 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 45, "">, referenced_path = "top.bus_if.put.old", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s44.put::@s46.old, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 45 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 42, "tmp_vif_call_probe.sv", 4, 45, "">} {
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 99 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 48, "tmp_vif_call_probe.sv", 4, 49, "">, referenced_path = "top.bus_if.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s40.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 49 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 48, "tmp_vif_call_probe.sv", 4, 49, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 100 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 57, "">, source_end_column = 57 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 57, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = true, node_id = 101 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 56, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 56 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 56, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 102 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 52, "">, referenced_path = "top.bus_if.x", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s40.x, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 52 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 51, "tmp_vif_call_probe.sv", 4, 52, "">} {
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 103 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 55, "tmp_vif_call_probe.sv", 4, 56, "">, referenced_path = "top.bus_if.put.v", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s44.put::@s45.v, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 56 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 55, "tmp_vif_call_probe.sv", 4, 56, "">} {
                  }
                }
              }
            }
            obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.bus_if.put.v", lifetime = 1 : i32, name = "v", node_id = 104 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 23, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 23 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 23, "">, sym_name = "s45.v"} {
            }
            obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.bus_if.put.old", lifetime = 1 : i32, name = "old", node_id = 105 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 39, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 39 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 39, "">, sym_name = "s46.old"} {
            }
          }
          obelisk.sv.symbol.modport attributes {hierarchical_name = "top.bus_if.master", name = "master", node_id = 106 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 11, "tmp_vif_call_probe.sv", 5, 41, "">, source_end_column = 41 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 11, "tmp_vif_call_probe.sv", 5, 41, "">, sym_name = "s47.master"} {
            obelisk.sv.symbol.method_prototype attributes {extern_implementation_count = 0 : i64, extern_implementation_paths = [], extern_implementation_symbols = [], hierarchical_name = "top.bus_if.master.get", is_modport_import, name = "get", node_id = 107 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 25, "tmp_vif_call_probe.sv", 5, 28, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>) -> !obelisk.integral<32, true, false, 31 : 0, int>, false>, source_end_column = 28 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 25, "tmp_vif_call_probe.sv", 5, 28, "">, subroutine_kind = 0 : i32, subroutine_path = "top.bus_if.get", subroutine_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s41.get, sym_name = "s48.get"} {
              obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.bus_if.master.get.add", lifetime = 1 : i32, name = "add", node_id = 108 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 30, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 30 : i64, source_end_line = 3 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 3, 30, "tmp_vif_call_probe.sv", 3, 30, "">, sym_name = "s49.add"} {
              }
            }
            obelisk.sv.symbol.method_prototype attributes {extern_implementation_count = 0 : i64, extern_implementation_paths = [], extern_implementation_symbols = [], hierarchical_name = "top.bus_if.master.put", is_modport_import, name = "put", node_id = 109 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 37, "tmp_vif_call_probe.sv", 5, 40, "">, semantic_type = !obelisk.subroutine<(!obelisk.integral<32, true, false, 31 : 0, int>, !obelisk.integral<32, true, false, 31 : 0, int>) -> (), true>, source_end_column = 40 : i64, source_end_line = 5 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 5, 37, "tmp_vif_call_probe.sv", 5, 40, "">, subroutine_kind = 1 : i32, subroutine_path = "top.bus_if.put", subroutine_symbol = @s2.$root::@s4.top::@s5.top::@s39.bus_if::@s44.put, sym_name = "s50.put"} {
              obelisk.sv.symbol.formal_argument attributes {direction = 0 : i32, hierarchical_name = "top.bus_if.master.put.v", lifetime = 1 : i32, name = "v", node_id = 110 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 22, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 22 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 22, "tmp_vif_call_probe.sv", 4, 22, "">, sym_name = "s51.v"} {
              }
              obelisk.sv.symbol.formal_argument attributes {direction = 1 : i32, hierarchical_name = "top.bus_if.master.put.old", lifetime = 1 : i32, name = "old", node_id = 111 : i64, original_source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 36, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 36 : i64, source_end_line = 4 : i64, source_file = "tmp_vif_call_probe.sv", source_range = !obelisk.source_range<"tmp_vif_call_probe.sv", 4, 36, "tmp_vif_call_probe.sv", 4, 36, "">, sym_name = "s52.old"} {
              }
            }
          }
        }
      }
    }
  }
}


// CHECK-DAG: obelisk_sim.scope.decl [[A:[0-9]+]] parent 1 hierarchy "top.a"
// CHECK-DAG: obelisk_sim.scope.decl [[B:[0-9]+]] parent 1 hierarchy "top.b"
// The outlined task copies its hidden output temporary back through the
// caller-provided output reference.
// CHECK-LABEL: obelisk_sim.func private @unit_1(
// CHECK: [[OUT_STORAGE:%.*]] = obelisk_sim.context.storage %arg0[4]
// CHECK: [[OUT:%.*]] = obelisk_sim.ref.load [[OUT_STORAGE]]
// CHECK: obelisk_sim.ref.store [[OUT]] to %arg3
// CHECK-LABEL: obelisk_sim.func private @unit_4(
// CHECK: obelisk_sim.virtual_interface.scope
// CHECK: arith.cmpi eq
// CHECK: obelisk_sim.call @unit_0
// CHECK: arith.cmpi eq
// CHECK: obelisk_sim.call @unit_2
// CHECK: virtual interface call used a null or invalid handle.
// CHECK: obelisk_sim.virtual_interface.scope
// CHECK: arith.cmpi eq
// CHECK: obelisk_sim.task.call @unit_1(%arg0, %{{.*}}, %{{.*}}, %arg8) {{.*}} to [[CONT:\^bb[0-9]+]]
// CHECK: arith.cmpi eq
// CHECK: obelisk_sim.task.call @unit_3(%arg0, %{{.*}}, %{{.*}}, %arg8) {{.*}} to [[CONT]]
// CHECK: virtual interface task call used a null or invalid handle.
// CHECK-NOT: obelisk.sv.
// Every possible instance capture read by a dynamically selected function is
// conservatively included in always_comb sensitivity.
// SENS: obelisk_sim.suspend.any {{.*}} edges [0, 0, 0, 0]
// MODPORT: virtual-interface method is not imported by the selected modport
