// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' '--encode-obelisk-sim-to-bytecode=vpi=off' -o /dev/null

// Generated from five assertions over one clock:
//   a |-> a[*2:$]
//   a |=> (b[->2:$] ##1 c)
//   a #-# (b[=1:3] ##1 c)
//   not (a #=# (b[*1:$] ##1 c))
//   disable iff (d) a |=> (b ##1 c[->1:2] ##1 d)

// Overlapped implication activates a consecutive DFA on the antecedent clock.
// The repeated use of `a` shares one sampled truth value. Pending states close
// through the weak assertion EOS result.
// CHECK-LABEL: obelisk_sim.func private @unit_0.$concurrent_eos_count.
// CHECK-COUNT-2: obelisk_sim.ref.load
// CHECK-NOT: obelisk_sim.ref.load
// CHECK: obelisk_sim.spawn @unit_0.fork.{{[0-9]+}}.0.0
// CHECK-LABEL: obelisk_sim.func private @unit_0(
// CHECK-SAME: obelisk_sim.persistent_repetition_implication
// CHECK-SAME: obelisk_sim.persistent_repetition_kind = "consecutive"
// CHECK-SAME: obelisk_sim.persistent_repetition_min = 2
// CHECK-SAME: obelisk_sim.persistent_repetition_states = 2
// CHECK-SAME: obelisk_sim.persistent_repetition_unbounded
// CHECK-NOT: obelisk_sim.persistent_repetition_nonoverlapped
// CHECK-NOT: obelisk_sim.persistent_implication_handoff
// CHECK: obelisk_sim.spawn @unit_0.$concurrent_eos_count.
// CHECK: obelisk_sim.assert.sampled_read
// CHECK-NOT: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_0.fork.{{[0-9]+}}.0.0
// CHECK: obelisk_sim.spawn @unit_0.fork.{{[0-9]+}}.0.0
// CHECK: obelisk_sim.spawn @unit_0.fork.{{[0-9]+}}.1.1
// CHECK-NOT: obelisk_sim.spawn @unit_0.fork

// Nonoverlapped implication adds one handoff bit to the four-state unbounded
// goto DFA. EOS counts all four DFA cells plus that pending activation.
// CHECK-LABEL: obelisk_sim.func private @unit_1.$concurrent_eos_count.
// CHECK-COUNT-5: obelisk_sim.ref.load
// CHECK-NOT: obelisk_sim.ref.load
// CHECK: obelisk_sim.spawn @unit_1.fork.{{[0-9]+}}.0.0
// CHECK-LABEL: obelisk_sim.func private @unit_1(
// CHECK-SAME: obelisk_sim.persistent_repetition_kind = "goto"
// CHECK-SAME: obelisk_sim.persistent_repetition_min = 2
// CHECK-SAME: obelisk_sim.persistent_repetition_nonoverlapped
// CHECK-SAME: obelisk_sim.persistent_repetition_states = 4
// CHECK-SAME: obelisk_sim.persistent_repetition_unbounded
// CHECK-COUNT-4: obelisk_sim.ref.alloc %{{.*}} : i64 -> !obelisk_sim.ref<i64>
// CHECK-NOT: obelisk_sim.ref.alloc %{{.*}} : i64 -> !obelisk_sim.ref<i64>
// CHECK: [[U1_HANDOFF:%.*]] = obelisk_sim.ref.alloc %{{.*}} {obelisk_sim.persistent_implication_handoff}
// CHECK: obelisk_sim.spawn @unit_1.$concurrent_eos_count.{{.*}}[[U1_HANDOFF]]
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_1.fork.{{[0-9]+}}.0.0
// CHECK: obelisk_sim.ref.load
// CHECK: obelisk_sim.ref.store
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.logic.compare case_eq
// CHECK: obelisk_sim.assert.sampled_read
// CHECK-NOT: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_1.fork.{{[0-9]+}}.0.0
// CHECK: obelisk_sim.spawn @unit_1.fork.{{[0-9]+}}.1.1
// CHECK-NOT: obelisk_sim.spawn @unit_1.fork

// Followed-by maps a false antecedent to failure while the finite
// nonconsecutive DFA preserves strict-false/X transitions and live outcomes.
// CHECK-LABEL: obelisk_sim.func private @unit_2.$concurrent_eos_count.
// CHECK-COUNT-4: obelisk_sim.ref.load
// CHECK-NOT: obelisk_sim.ref.load
// CHECK: obelisk_sim.spawn @unit_2.fork.{{[0-9]+}}.0.0
// CHECK-LABEL: obelisk_sim.func private @unit_2(
// CHECK-SAME: obelisk_sim.followed_by_monitor
// CHECK-SAME: obelisk_sim.persistent_repetition_kind = "nonconsecutive"
// CHECK-SAME: obelisk_sim.persistent_repetition_max = 3
// CHECK-SAME: obelisk_sim.persistent_repetition_min = 1
// CHECK-SAME: obelisk_sim.persistent_repetition_states = 4
// CHECK-NOT: obelisk_sim.persistent_repetition_nonoverlapped
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_2.fork.{{[0-9]+}}.1.1
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.logic.compare case_eq
// CHECK: obelisk_sim.assert.sampled_read
// CHECK-NOT: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_2.fork.{{[0-9]+}}.0.0
// CHECK: obelisk_sim.spawn @unit_2.fork.{{[0-9]+}}.1.1
// CHECK-NOT: obelisk_sim.spawn @unit_2.fork

// Temporal not turns the cover-default strong operand into a weak outer
// property. False followed-by activation, live failure, and strong EOS failure
// each become one cover hit; operand success remains action-silent.
// CHECK-LABEL: obelisk_sim.func private @unit_3.$concurrent_eos_count.
// CHECK-COUNT-3: obelisk_sim.ref.load
// CHECK-NOT: obelisk_sim.ref.load
// CHECK: obelisk_sim.spawn @unit_3.fork.{{[0-9]+}}.0.0
// CHECK-LABEL: obelisk_sim.func private @unit_3(
// CHECK-SAME: obelisk_sim.end_of_simulation_strength = "weak"
// CHECK-SAME: obelisk_sim.negated_operand_end_of_simulation_strength = "strong"
// CHECK-SAME: obelisk_sim.persistent_repetition_kind = "consecutive"
// CHECK-SAME: obelisk_sim.persistent_repetition_nonoverlapped
// CHECK-SAME: obelisk_sim.temporal_property_negation
// CHECK: [[U3_HANDOFF:%.*]] = obelisk_sim.ref.alloc %{{.*}} {obelisk_sim.persistent_implication_handoff}
// CHECK: obelisk_sim.spawn @unit_3.$concurrent_eos_count.{{.*}}[[U3_HANDOFF]]
// CHECK: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_3.fork.{{[0-9]+}}.0.0
// CHECK: obelisk_sim.ref.load
// CHECK: obelisk_sim.ref.store
// CHECK-COUNT-2: obelisk_sim.assert.sampled_read
// CHECK-NOT: obelisk_sim.assert.sampled_read
// CHECK: obelisk_sim.spawn @unit_3.fork.{{[0-9]+}}.0.0
// CHECK-NOT: obelisk_sim.spawn @unit_3.fork

// Disable clears four DFA counters, the bounded prefix bitset, and the
// nonoverlap handoff, then advances the report epoch. EOS observes those six
// cells plus the epoch used to invalidate stale callbacks.
// CHECK-LABEL: obelisk_sim.func private @unit_4.$concurrent_cancel.
// CHECK-COUNT-6: obelisk_sim.ref.store {{.*}} to %arg{{[4-9]}}
// CHECK: [[U4_EPOCH:%.*]] = obelisk_sim.ref.load %arg10
// CHECK: [[U4_NEXT_EPOCH:%.*]] = arith.addi [[U4_EPOCH]],
// CHECK: obelisk_sim.ref.store [[U4_NEXT_EPOCH]] to %arg10
// CHECK-LABEL: obelisk_sim.func private @unit_4.$concurrent_eos_count.
// CHECK-COUNT-7: obelisk_sim.ref.load
// CHECK-NOT: obelisk_sim.ref.load
// CHECK-LABEL: obelisk_sim.func private @unit_4(
// CHECK-SAME: obelisk_sim.persistent_repetition_kind = "goto"
// CHECK-SAME: obelisk_sim.persistent_repetition_max = 2
// CHECK-SAME: obelisk_sim.persistent_repetition_nonoverlapped
// CHECK-SAME: obelisk_sim.persistent_repetition_states = 4
// CHECK-COUNT-6: obelisk_sim.ref.alloc %{{.*}} : i64 -> !obelisk_sim.ref<i64>
// CHECK-NOT: obelisk_sim.ref.alloc %{{.*}} : i64 -> !obelisk_sim.ref<i64>
// CHECK: [[U4_HANDOFF:%.*]] = obelisk_sim.ref.alloc %{{.*}} {obelisk_sim.persistent_implication_handoff}
// CHECK: obelisk_sim.spawn @unit_4.$concurrent_cancel.{{.*}}[[U4_HANDOFF]]
// CHECK: obelisk_sim.spawn @unit_4.$concurrent_eos_count.{{.*}}[[U4_HANDOFF]]
// CHECK-COUNT-4: obelisk_sim.assert.sampled_read
// CHECK-NOT: obelisk_sim.assert.sampled_read

module attributes {llvm.data_layout = "e-m:e-p:64:64-i64:64-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 1, "../../../../tmp/sva_persistent_repetition_implication.sv", 17, 10, "">, source_end_column = 10 : i64, source_end_line = 17 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 1, "../../../../tmp/sva_persistent_repetition_implication.sv", 17, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 1, "../../../../tmp/sva_persistent_repetition_implication.sv", 18, 1, "">, source_end_column = 1 : i64, source_end_line = 18 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 1, "../../../../tmp/sva_persistent_repetition_implication.sv", 18, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 8, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 8, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 1, "../../../../tmp/sva_persistent_repetition_implication.sv", 17, 10, "">, source_end_column = 10 : i64, source_end_line = 17 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 1, "../../../../tmp/sva_persistent_repetition_implication.sv", 17, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 24, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 24, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 27, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 24, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 24, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 27, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.a", name = "a", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 30, "">, sym_name = "s7.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a", lifetime = 1 : i32, name = "a", node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 30, "">, sym_name = "s8.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.b", name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 32, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 32, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 33, "">, sym_name = "s9.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b", lifetime = 1 : i32, name = "b", node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 32, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 32, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 33, "">, sym_name = "s10.b"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.c", name = "c", node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 36, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 36, "">, sym_name = "s11.c"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.c", lifetime = 1 : i32, name = "c", node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 36, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 36, "">, sym_name = "s12.c"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.d", name = "d", node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 38, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 39, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 39 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 38, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 39, "">, sym_name = "s13.d"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.d", lifetime = 1 : i32, name = "d", node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 38, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 39, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 39 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 1, 38, "../../../../tmp/sva_persistent_repetition_implication.sv", 1, 39, "">, sym_name = "s14.d"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 45, "">, procedure_kind = 2 : i32, source_end_column = 45 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 45, "">, sym_name = "s15", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 16 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 45, "">, source_end_column = 45 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 45, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 17 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 48, "">, source_end_column = 48 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 48, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 33, "">, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 19 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 33, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 33, "">} {
                }
              }
              obelisk.sv.assertion.binary attributes {node_id = 20 : i64, operator_kind = 11 : i32, operator_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 37, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 40, "">, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 48, "">, source_end_column = 48 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 48, "">} {
                obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 21 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 36, "">, repetition_is_unbounded = false, source_end_column = 36 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 36, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 22 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 36, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 36, "">} {
                  }
                }
                obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 48, "">, repetition_is_unbounded = true, repetition_kind = 0 : i32, repetition_min = 2 : i64, source_end_column = 48 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 48, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 24 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 42, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 42 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 2, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 2, 42, "">} {
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 25 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 22, "">, source_end_column = 22 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 22, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 26 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 21, "">, semantic_type = !obelisk.void, source_end_column = 21 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 21, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u0-pass", is_signed = false, node_id = 27 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 20, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 20 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 20, "">} {
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 28 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 45, "">, source_end_column = 45 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 45, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 29 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 44, "">, semantic_type = !obelisk.void, source_end_column = 44 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 44, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u0-fail", is_signed = false, node_id = 30 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 43, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 43 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 3, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 3, 43, "">} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 31 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 45, "">, procedure_kind = 2 : i32, source_end_column = 45 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 45, "">, sym_name = "s16", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 32 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 45, "">, source_end_column = 45 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 45, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 33 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 57, "">, source_end_column = 57 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 57, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 34 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 33, "">, source_end_column = 33 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 35 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 33, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 33, "">} {
                }
              }
              obelisk.sv.assertion.binary attributes {node_id = 36 : i64, operator_kind = 12 : i32, operator_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 37, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 40, "">, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 57, "">, source_end_column = 57 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 57, "">} {
                obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 37 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 36, "">, repetition_is_unbounded = false, source_end_column = 36 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 36, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 38 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 36, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 36, "">} {
                  }
                }
                obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 53, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 54, "">}], node_id = 39 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 57, "">, source_end_column = 57 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 57, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 40 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 50, "">, repetition_is_unbounded = true, repetition_kind = 2 : i32, repetition_min = 2 : i64, source_end_column = 50 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 50, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 41 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 43, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 43 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 43, "">} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 42 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 55, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 56, "">, repetition_is_unbounded = false, source_end_column = 56 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 55, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 56, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 43 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 55, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 56, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 56 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 5, 55, "../../../../tmp/sva_persistent_repetition_implication.sv", 5, 56, "">} {
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 44 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 22, "">, source_end_column = 22 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 22, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 45 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 21, "">, semantic_type = !obelisk.void, source_end_column = 21 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 21, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u1-pass", is_signed = false, node_id = 46 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 20, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 20 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 20, "">} {
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 47 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 45, "">, source_end_column = 45 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 45, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 48 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 44, "">, semantic_type = !obelisk.void, source_end_column = 44 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 44, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u1-fail", is_signed = false, node_id = 49 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 43, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 43 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 6, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 6, 43, "">} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 50 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 45, "">, procedure_kind = 2 : i32, source_end_column = 45 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 45, "">, sym_name = "s17", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 51 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 45, "">, source_end_column = 45 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 45, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 52 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 56, "">, source_end_column = 56 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 56, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 53 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 33, "">, source_end_column = 33 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 54 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 33, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 33, "">} {
                }
              }
              obelisk.sv.assertion.binary attributes {node_id = 55 : i64, operator_kind = 13 : i32, operator_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 37, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 40, "">, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 56, "">, source_end_column = 56 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 56, "">} {
                obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 56 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 36, "">, repetition_is_unbounded = false, source_end_column = 36 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 36, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 57 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 36, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 35, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 36, "">} {
                  }
                }
                obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 52, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 53, "">}], node_id = 58 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 56, "">, source_end_column = 56 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 56, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 59 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 49, "">, repetition_is_unbounded = false, repetition_kind = 1 : i32, repetition_max = 3 : i64, repetition_min = 1 : i64, source_end_column = 49 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 49, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 60 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 43, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 43 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 42, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 43, "">} {
                    }
                  }
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 61 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 54, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 55, "">, repetition_is_unbounded = false, source_end_column = 55 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 54, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 55, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 62 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 54, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 55, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 55 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 8, 54, "../../../../tmp/sva_persistent_repetition_implication.sv", 8, 55, "">} {
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 63 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 22, "">, source_end_column = 22 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 22, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 64 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 21, "">, semantic_type = !obelisk.void, source_end_column = 21 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 21, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u2-pass", is_signed = false, node_id = 65 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 20, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 20 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 20, "">} {
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 66 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 45, "">, source_end_column = 45 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 45, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 67 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 44, "">, semantic_type = !obelisk.void, source_end_column = 44 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 44, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u2-fail", is_signed = false, node_id = 68 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 43, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 43 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 9, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 9, 43, "">} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 69 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 21, "">, procedure_kind = 2 : i32, source_end_column = 21 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 21, "">, sym_name = "s18", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 2 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 70 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 21, "">, source_end_column = 21 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 21, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 71 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 19, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 61, "">, source_end_column = 61 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 19, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 61, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 72 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 21, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 32, "">, source_end_column = 32 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 21, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 32, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 73 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 32, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 32 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 32, "">} {
                }
              }
              obelisk.sv.assertion.unary attributes {has_range = false, node_id = 74 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 61, "">, range_is_unbounded = false, source_end_column = 61 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 61, "">} {
                obelisk.sv.assertion.binary attributes {node_id = 75 : i64, operator_kind = 14 : i32, operator_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 41, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 44, "">, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 38, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 61, "">, source_end_column = 61 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 38, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 61, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 76 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 39, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 40, "">, repetition_is_unbounded = false, source_end_column = 40 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 39, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 40, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 77 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 39, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 40, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 40 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 39, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 40, "">} {
                    }
                  }
                  obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 56, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 57, "">}], node_id = 78 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 45, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 60, "">, source_end_column = 60 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 45, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 60, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 79 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 46, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 53, "">, repetition_is_unbounded = true, repetition_kind = 0 : i32, repetition_min = 1 : i64, source_end_column = 53 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 46, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 53, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 80 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 46, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 47, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 47 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 46, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 47, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 81 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 58, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 59, "">, repetition_is_unbounded = false, source_end_column = 59 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 58, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 59, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 82 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 58, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 59, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 59 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 11, 58, "../../../../tmp/sva_persistent_repetition_implication.sv", 11, 59, "">} {
                      }
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 83 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 12, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 21, "">, source_end_column = 21 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 12, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 21, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 84 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 12, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 20, "">, semantic_type = !obelisk.void, source_end_column = 20 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 12, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 20, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u3-hit", is_signed = false, node_id = 85 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 12, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 19, "">, semantic_type = !obelisk.ranged_packed_array<47 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 19 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 12, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 12, 19, "">} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 86 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 45, "">, procedure_kind = 2 : i32, source_end_column = 45 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 45, "">, sym_name = "s19", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 87 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 45, "">, source_end_column = 45 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 3, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 45, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 88 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 51, "">, source_end_column = 51 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 51, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 89 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 14, 33, "">, source_end_column = 33 : i64, source_end_line = 14 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 22, "../../../../tmp/sva_persistent_repetition_implication.sv", 14, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 90 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 14, 33, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 14 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 14, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 14, 33, "">} {
                }
              }
              obelisk.sv.assertion.disable_iff attributes {node_id = 91 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 7, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 22, "">, source_end_column = 22 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 7, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 22, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 92 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 21, "">, referenced_path = "top.d", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s14.d, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 21 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 20, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 21, "">} {
                }
                obelisk.sv.assertion.binary attributes {node_id = 93 : i64, operator_kind = 12 : i32, operator_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 25, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 28, "">, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 23, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 51, "">, source_end_column = 51 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 23, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 51, "">} {
                  obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 94 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 23, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 24, "">, repetition_is_unbounded = false, source_end_column = 24 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 23, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 24, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 95 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 23, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 24, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 24 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 23, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 24, "">} {
                    }
                  }
                  obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 35, "">}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 47, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 48, "">}], node_id = 96 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 51, "">, source_end_column = 51 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 29, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 51, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 97 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 31, "">, repetition_is_unbounded = false, source_end_column = 31 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 31, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 98 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 31, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 31 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 30, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 31, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 99 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 36, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 44, "">, repetition_is_unbounded = false, repetition_kind = 2 : i32, repetition_max = 2 : i64, repetition_min = 1 : i64, source_end_column = 44 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 36, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 44, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 100 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 36, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 37, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 36, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 37, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 101 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 49, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 50, "">, repetition_is_unbounded = false, source_end_column = 50 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 49, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 50, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 102 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 49, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 50, "">, referenced_path = "top.d", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s14.d, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 50 : i64, source_end_line = 15 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 15, 49, "../../../../tmp/sva_persistent_repetition_implication.sv", 15, 50, "">} {
                      }
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 103 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 22, "">, source_end_column = 22 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 22, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 104 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 21, "">, semantic_type = !obelisk.void, source_end_column = 21 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 5, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 21, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u4-pass", is_signed = false, node_id = 105 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 20, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 20 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 11, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 20, "">} {
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 106 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 45, "">, source_end_column = 45 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 45, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$info", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 107 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 44, "">, semantic_type = !obelisk.void, source_end_column = 44 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 28, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 44, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s1.$root::@s3.top::@s4.top} {
                obelisk.sv.expression.string_literal attributes {constant_value = "u4-fail", is_signed = false, node_id = 108 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 43, "">, semantic_type = !obelisk.ranged_packed_array<55 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 43 : i64, source_end_line = 16 : i64, source_file = "../../../../tmp/sva_persistent_repetition_implication.sv", source_range = !obelisk.source_range<"../../../../tmp/sva_persistent_repetition_implication.sv", 16, 34, "../../../../tmp/sva_persistent_repetition_implication.sv", 16, 43, "">} {
                }
              }
            }
          }
        }
      }
    }
  }
}
