// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' -o /dev/null
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' '--encode-obelisk-sim-to-bytecode=vpi=off' -o /dev/null
// REQUIRES: z3

// Temporal negation and disable iff compose with all four temporal pair words.
// Disable clears matched history plus every pair and advances the report epoch;
// negation turns each strong pending consequent failure into one cover hit.

module attributes {llvm.data_layout = "e-m:e-p:64:64-i64:64-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu"} {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "combined_temporal_not_disable", name = "combined_temporal_not_disable", node_id = 0 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 1, "combined-temporal-not-disable.sv", 5, 10, "">, source_end_column = 10 : i64, source_end_line = 5 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 1, "combined-temporal-not-disable.sv", 5, 10, "">, sym_name = "s0.combined_temporal_not_disable"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 1, "combined-temporal-not-disable.sv", 6, 1, "">, source_end_column = 1 : i64, source_end_line = 6 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 1, "combined-temporal-not-disable.sv", 6, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "combined_temporal_not_disable", is_uninstantiated = false, name = "combined_temporal_not_disable", node_id = 3 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 8, "combined-temporal-not-disable.sv", 1, 8, "">, referenced_path = "combined_temporal_not_disable", referenced_symbol = @s0.combined_temporal_not_disable, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 8, "combined-temporal-not-disable.sv", 1, 8, "">, sym_name = "s3.combined_temporal_not_disable"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "combined_temporal_not_disable", name = "combined_temporal_not_disable", node_id = 4 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 1, "combined-temporal-not-disable.sv", 5, 10, "">, source_end_column = 10 : i64, source_end_line = 5 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 1, "combined-temporal-not-disable.sv", 5, 10, "">, sym_name = "s4.combined_temporal_not_disable", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 50, "combined-temporal-not-disable.sv", 1, 53, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 53 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 50, "combined-temporal-not-disable.sv", 1, 53, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 50, "combined-temporal-not-disable.sv", 1, 53, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 53 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 50, "combined-temporal-not-disable.sv", 1, 53, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.reset", name = "reset", node_id = 7 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 55, "combined-temporal-not-disable.sv", 1, 60, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 60 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 55, "combined-temporal-not-disable.sv", 1, 60, "">, sym_name = "s7.reset"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.reset", lifetime = 1 : i32, name = "reset", node_id = 8 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 55, "combined-temporal-not-disable.sv", 1, 60, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 60 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 55, "combined-temporal-not-disable.sv", 1, 60, "">, sym_name = "s8.reset"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.a", name = "a", node_id = 9 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 62, "combined-temporal-not-disable.sv", 1, 63, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 63 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 62, "combined-temporal-not-disable.sv", 1, 63, "">, sym_name = "s9.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.a", lifetime = 1 : i32, name = "a", node_id = 10 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 62, "combined-temporal-not-disable.sv", 1, 63, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 63 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 62, "combined-temporal-not-disable.sv", 1, 63, "">, sym_name = "s10.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.b", name = "b", node_id = 11 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 65, "combined-temporal-not-disable.sv", 1, 66, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 66 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 65, "combined-temporal-not-disable.sv", 1, 66, "">, sym_name = "s11.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.b", lifetime = 1 : i32, name = "b", node_id = 12 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 65, "combined-temporal-not-disable.sv", 1, 66, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 66 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 65, "combined-temporal-not-disable.sv", 1, 66, "">, sym_name = "s12.b"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.c", name = "c", node_id = 13 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 68, "combined-temporal-not-disable.sv", 1, 69, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 69 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 68, "combined-temporal-not-disable.sv", 1, 69, "">, sym_name = "s13.c"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.c", lifetime = 1 : i32, name = "c", node_id = 14 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 68, "combined-temporal-not-disable.sv", 1, 69, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 69 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 68, "combined-temporal-not-disable.sv", 1, 69, "">, sym_name = "s14.c"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.d", name = "d", node_id = 15 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 71, "combined-temporal-not-disable.sv", 1, 72, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 72 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 71, "combined-temporal-not-disable.sv", 1, 72, "">, sym_name = "s15.d"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.d", lifetime = 1 : i32, name = "d", node_id = 16 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 71, "combined-temporal-not-disable.sv", 1, 72, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 72 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 71, "combined-temporal-not-disable.sv", 1, 72, "">, sym_name = "s16.d"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "combined_temporal_not_disable.e", name = "e", node_id = 17 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 74, "combined-temporal-not-disable.sv", 1, 75, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 75 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 74, "combined-temporal-not-disable.sv", 1, 75, "">, sym_name = "s17.e"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "combined_temporal_not_disable.e", lifetime = 1 : i32, name = "e", node_id = 18 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 74, "combined-temporal-not-disable.sv", 1, 75, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 75 : i64, source_end_line = 1 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 1, 74, "combined-temporal-not-disable.sv", 1, 75, "">, sym_name = "s18.e"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "combined_temporal_not_disable", node_id = 19 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 3, "combined-temporal-not-disable.sv", 4, 21, "">, procedure_kind = 2 : i32, source_end_column = 21 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 3, "combined-temporal-not-disable.sv", 4, 21, "">, sym_name = "s19", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 2 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 20 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 3, "combined-temporal-not-disable.sv", 4, 21, "">, source_end_column = 21 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 3, "combined-temporal-not-disable.sv", 4, 21, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 21 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 19, "combined-temporal-not-disable.sv", 3, 48, "">, source_end_column = 48 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 19, "combined-temporal-not-disable.sv", 3, 48, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 22 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 21, "combined-temporal-not-disable.sv", 2, 32, "">, source_end_column = 32 : i64, source_end_line = 2 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 21, "combined-temporal-not-disable.sv", 2, 32, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 29, "combined-temporal-not-disable.sv", 2, 32, "">, referenced_path = "combined_temporal_not_disable.clk", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 32 : i64, source_end_line = 2 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 29, "combined-temporal-not-disable.sv", 2, 32, "">} {
                }
              }
              obelisk.sv.assertion.disable_iff attributes {node_id = 24 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 34, "combined-temporal-not-disable.sv", 2, 53, "">, source_end_column = 53 : i64, source_end_line = 2 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 34, "combined-temporal-not-disable.sv", 2, 53, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 25 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 47, "combined-temporal-not-disable.sv", 2, 52, "">, referenced_path = "combined_temporal_not_disable.reset", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s8.reset, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 52 : i64, source_end_line = 2 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 2, 47, "combined-temporal-not-disable.sv", 2, 52, "">} {
                }
                obelisk.sv.assertion.unary attributes {has_range = false, node_id = 26 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 5, "combined-temporal-not-disable.sv", 3, 48, "">, range_is_unbounded = false, source_end_column = 48 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 5, "combined-temporal-not-disable.sv", 3, 48, "">} {
                  obelisk.sv.assertion.binary attributes {node_id = 27 : i64, operator_kind = 11 : i32, operator_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 19, "combined-temporal-not-disable.sv", 3, 22, "">, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 9, "combined-temporal-not-disable.sv", 3, 48, "">, source_end_column = 48 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 9, "combined-temporal-not-disable.sv", 3, 48, "">} {
                    obelisk.sv.assertion.binary attributes {node_id = 28 : i64, operator_kind = 1 : i32, operator_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 13, "combined-temporal-not-disable.sv", 3, 15, "">, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 10, "combined-temporal-not-disable.sv", 3, 18, "">, source_end_column = 18 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 10, "combined-temporal-not-disable.sv", 3, 18, "">} {
                      obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 29 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 11, "combined-temporal-not-disable.sv", 3, 12, "">, repetition_is_unbounded = false, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 11, "combined-temporal-not-disable.sv", 3, 12, "">} {
                        obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 30 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 11, "combined-temporal-not-disable.sv", 3, 12, "">, referenced_path = "combined_temporal_not_disable.a", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s10.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 12 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 11, "combined-temporal-not-disable.sv", 3, 12, "">} {
                        }
                      }
                      obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 31 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 16, "combined-temporal-not-disable.sv", 3, 17, "">, repetition_is_unbounded = false, source_end_column = 17 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 16, "combined-temporal-not-disable.sv", 3, 17, "">} {
                        obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 32 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 16, "combined-temporal-not-disable.sv", 3, 17, "">, referenced_path = "combined_temporal_not_disable.b", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s12.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 17 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 16, "combined-temporal-not-disable.sv", 3, 17, "">} {
                        }
                      }
                    }
                    obelisk.sv.assertion.binary attributes {node_id = 33 : i64, operator_kind = 1 : i32, operator_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 34, "combined-temporal-not-disable.sv", 3, 36, "">, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 23, "combined-temporal-not-disable.sv", 3, 47, "">, source_end_column = 47 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 23, "combined-temporal-not-disable.sv", 3, 47, "">} {
                      obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 29, "combined-temporal-not-disable.sv", 3, 30, "">}], node_id = 34 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 24, "combined-temporal-not-disable.sv", 3, 33, "">, source_end_column = 33 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 24, "combined-temporal-not-disable.sv", 3, 33, "">} {
                        obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 35 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 25, "combined-temporal-not-disable.sv", 3, 26, "">, repetition_is_unbounded = false, source_end_column = 26 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 25, "combined-temporal-not-disable.sv", 3, 26, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 36 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 25, "combined-temporal-not-disable.sv", 3, 26, "">, referenced_path = "combined_temporal_not_disable.c", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s14.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 26 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 25, "combined-temporal-not-disable.sv", 3, 26, "">} {
                          }
                        }
                        obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 37 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 31, "combined-temporal-not-disable.sv", 3, 32, "">, repetition_is_unbounded = false, source_end_column = 32 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 31, "combined-temporal-not-disable.sv", 3, 32, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 38 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 31, "combined-temporal-not-disable.sv", 3, 32, "">, referenced_path = "combined_temporal_not_disable.d", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s16.d, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 32 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 31, "combined-temporal-not-disable.sv", 3, 32, "">} {
                          }
                        }
                      }
                      obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 2 : i64, min = 2 : i64, source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 42, "combined-temporal-not-disable.sv", 3, 43, "">}], node_id = 39 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 37, "combined-temporal-not-disable.sv", 3, 46, "">, source_end_column = 46 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 37, "combined-temporal-not-disable.sv", 3, 46, "">} {
                        obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 40 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 38, "combined-temporal-not-disable.sv", 3, 39, "">, repetition_is_unbounded = false, source_end_column = 39 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 38, "combined-temporal-not-disable.sv", 3, 39, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 41 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 38, "combined-temporal-not-disable.sv", 3, 39, "">, referenced_path = "combined_temporal_not_disable.c", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s14.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 39 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 38, "combined-temporal-not-disable.sv", 3, 39, "">} {
                          }
                        }
                        obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 42 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 44, "combined-temporal-not-disable.sv", 3, 45, "">, repetition_is_unbounded = false, source_end_column = 45 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 44, "combined-temporal-not-disable.sv", 3, 45, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 43 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 44, "combined-temporal-not-disable.sv", 3, 45, "">, referenced_path = "combined_temporal_not_disable.e", referenced_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable::@s18.e, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 45 : i64, source_end_line = 3 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 3, 44, "combined-temporal-not-disable.sv", 3, 45, "">} {
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 44 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 4, 5, "combined-temporal-not-disable.sv", 4, 21, "">, source_end_column = 21 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 4, 5, "combined-temporal-not-disable.sv", 4, 21, "">} {
              obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 45 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 4, 5, "combined-temporal-not-disable.sv", 4, 20, "">, semantic_type = !obelisk.void, source_end_column = 20 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 4, 5, "combined-temporal-not-disable.sv", 4, 20, "">, subroutine_kind = 1 : i32, system_library_cell = "work.combined_temporal_not_disable", system_scope_path = "combined_temporal_not_disable", system_scope_symbol = @s1.$root::@s3.combined_temporal_not_disable::@s4.combined_temporal_not_disable} {
                obelisk.sv.expression.string_literal attributes {constant_value = "hit", is_signed = false, node_id = 46 : i64, original_source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 4, 14, "combined-temporal-not-disable.sv", 4, 19, "">, semantic_type = !obelisk.ranged_packed_array<23 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 19 : i64, source_end_line = 4 : i64, source_file = "combined-temporal-not-disable.sv", source_range = !obelisk.source_range<"combined-temporal-not-disable.sv", 4, 14, "combined-temporal-not-disable.sv", 4, 19, "">} {
                }
              }
            }
          }
        }
      }
    }
  }
}

// CHECK-LABEL: obelisk_sim.func private @unit_0.$concurrent_cancel.
// CHECK-SAME: %arg9: !obelisk_sim.ref<i64>
// CHECK-SAME: ) attributes
// CHECK-SAME: obelisk_sim.concurrent_cancel
// CHECK-COUNT-5: obelisk_sim.ref.store
// CHECK: obelisk_sim.ref.load %arg9
// CHECK: obelisk_sim.ref.store {{.*}} to %arg9
// CHECK-NOT: obelisk_sim.ref.store

// CHECK-LABEL: obelisk_sim.func private @unit_0.$concurrent_eos_branch.
// CHECK-SAME: %arg6: !obelisk_sim.ref<i64>
// CHECK-SAME: ) attributes
// CHECK-SAME: obelisk_sim.branching_antecedent_eos_coalescer
// CHECK: obelisk_sim.spawn @unit_0.$concurrent_eos_branch_report.{{.*}}.pass{{.*}}obelisk_sim.branching_antecedent_eos_source_age = 2 : i64
// CHECK: obelisk_sim.spawn @unit_0.$concurrent_eos_branch_report.{{.*}}.pass{{.*}}obelisk_sim.branching_antecedent_eos_source_age = 1 : i64
// CHECK-NOT: obelisk_sim.spawn @unit_0.$concurrent_eos_branch_report.

// CHECK-LABEL: obelisk_sim.func private @unit_0(
// CHECK-SAME: obelisk_sim.branching_antecedent_consequent_eos_strength = "strong"
// CHECK-SAME: obelisk_sim.branching_antecedent_result_horizon = 3 : i64
// CHECK-SAME: obelisk_sim.branching_consequent_alternatives = 2 : i64
// CHECK-SAME: obelisk_sim.combined_bounded_branching_pairs = 4 : i64
// CHECK-SAME: obelisk_sim.temporal_property_negation
// CHECK-COUNT-6: obelisk_sim.ref.alloc
// CHECK-NOT: obelisk_sim.ref.alloc
// CHECK: obelisk_sim.spawn @unit_0.$concurrent_cancel.
// CHECK: obelisk_sim.spawn @unit_0.$concurrent_eos_branch.
// CHECK: obelisk_sim.suspend.edge posedge
// CHECK-COUNT-5: obelisk_sim.ref.store
// CHECK: obelisk_sim.ref.load
// CHECK: obelisk_sim.ref.store
// CHECK: obelisk_sim.branching_antecedent_universal_failure
// CHECK: obelisk_sim.branching_antecedent_universal_success
