// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' | FileCheck %s
// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=3' --emit-bytecode -o /dev/null
module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 0 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-not.sv", 11, 10, "">, source_end_column = 10 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-not.sv", 11, 10, "">, sym_name = "s0.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-not.sv", 12, 1, "">, source_end_column = 1 : i64, source_end_line = 12 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-not.sv", 12, 1, "">, sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 3 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 8, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 8, "">, referenced_path = "top", referenced_symbol = @s0.top, source_end_column = 8 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 8, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 8, "">, sym_name = "s3.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-not.sv", 11, 10, "">, source_end_column = 10 : i64, source_end_line = 11 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 1, "../../../../tmp/obelisk-mixed-empty-not.sv", 11, 10, "">, sym_name = "s4.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.clk", name = "clk", node_id = 5 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 27, "">, sym_name = "s5.clk"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.clk", lifetime = 1 : i32, name = "clk", node_id = 6 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 27, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 27 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 27, "">, sym_name = "s6.clk"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.a", name = "a", node_id = 7 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 30, "">, sym_name = "s7.a"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.a", lifetime = 1 : i32, name = "a", node_id = 8 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 30, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 30 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 29, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 30, "">, sym_name = "s8.a"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.b", name = "b", node_id = 9 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 33, "">, sym_name = "s9.b"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.b", lifetime = 1 : i32, name = "b", node_id = 10 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 33, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 33 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 32, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 33, "">, sym_name = "s10.b"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.c", name = "c", node_id = 11 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 36, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 36, "">, sym_name = "s11.c"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.c", lifetime = 1 : i32, name = "c", node_id = 12 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 36, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 36, "">, sym_name = "s12.c"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.d", name = "d", node_id = 13 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 38, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 39, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 39 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 38, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 39, "">, sym_name = "s13.d"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.d", lifetime = 1 : i32, name = "d", node_id = 14 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 38, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 39, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 39 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 38, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 39, "">, sym_name = "s14.d"} {
        }
        obelisk.sv.symbol.port attributes {direction = 0 : i32, hierarchical_name = "top.dis", name = "dis", node_id = 15 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 41, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 44, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 44 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 41, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 44, "">, sym_name = "s15.dis"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.dis", lifetime = 1 : i32, name = "dis", node_id = 16 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 41, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 44, "">, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 44 : i64, source_end_line = 1 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 1, 41, "../../../../tmp/obelisk-mixed-empty-not.sv", 1, 44, "">, sym_name = "s16.dis"} {
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.a0", name = "a0", node_id = 17 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, sym_name = "s17.a0"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 18 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, procedure_kind = 2 : i32, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, sym_name = "s18", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.a0", block_symbol = @s1.$root::@s3.top::@s4.top::@s17.a0, node_id = 19 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 20 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 21 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 58, "">, source_end_column = 58 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 58, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 22 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 26, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 37, "">, source_end_column = 37 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 26, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 37, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 34, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 37, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 34, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 37, "">} {
                  }
                }
                obelisk.sv.assertion.unary attributes {has_range = false, node_id = 24 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 58, "">, range_is_unbounded = false, source_end_column = 58 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 58, "">} {
                  obelisk.sv.assertion.binary attributes {node_id = 25 : i64, operator_kind = 12 : i32, operator_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 52, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 55, "">, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 58, "">, source_end_column = 58 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 58, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 26 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 51, "">, repetition_is_unbounded = false, repetition_kind = 0 : i32, repetition_max = 1 : i64, repetition_min = 0 : i64, source_end_column = 51 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 51, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 27 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 45, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 45 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 45, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 28 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 57, "">, repetition_is_unbounded = false, source_end_column = 57 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 57, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 29 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 57, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 57 : i64, source_end_line = 2 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 2, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 2, 57, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 30 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 27, "">, source_end_column = 27 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 27, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 31 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 26, "">, semantic_type = !obelisk.void, source_end_column = 26 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 26, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a0", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s17.a0} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "impl-pass", is_signed = false, node_id = 32 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 25, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 25 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 25, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 33 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">, source_end_column = 55 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 55, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 34 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 54, "">, semantic_type = !obelisk.void, source_end_column = 54 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 54, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a0", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s17.a0} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "impl-fail", is_signed = false, node_id = 35 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 42, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 53, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 53 : i64, source_end_line = 3 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 3, 42, "../../../../tmp/obelisk-mixed-empty-not.sv", 3, 53, "">} {
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.a1", name = "a1", node_id = 36 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, source_end_column = 59 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, sym_name = "s19.a1"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 37 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, procedure_kind = 2 : i32, source_end_column = 59 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, sym_name = "s20", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.a1", block_symbol = @s1.$root::@s3.top::@s4.top::@s19.a1, node_id = 38 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, source_end_column = 59 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 39 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, source_end_column = 59 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 40 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 58, "">, source_end_column = 58 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 58, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 41 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 26, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 37, "">, source_end_column = 37 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 26, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 37, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 42 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 34, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 37, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 34, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 37, "">} {
                  }
                }
                obelisk.sv.assertion.unary attributes {has_range = false, node_id = 43 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 58, "">, range_is_unbounded = false, source_end_column = 58 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 58, "">} {
                  obelisk.sv.assertion.binary attributes {node_id = 44 : i64, operator_kind = 14 : i32, operator_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 52, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 55, "">, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 58, "">, source_end_column = 58 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 58, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 45 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 51, "">, repetition_is_unbounded = false, repetition_kind = 0 : i32, repetition_max = 1 : i64, repetition_min = 0 : i64, source_end_column = 51 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 51, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 46 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 45, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 45 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 45, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 47 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 57, "">, repetition_is_unbounded = false, source_end_column = 57 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 57, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 48 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 57, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 57 : i64, source_end_line = 4 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 4, 56, "../../../../tmp/obelisk-mixed-empty-not.sv", 4, 57, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 49 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 29, "">, source_end_column = 29 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 29, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 50 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 28, "">, semantic_type = !obelisk.void, source_end_column = 28 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 28, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a1", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s19.a1} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "follow-pass", is_signed = false, node_id = 51 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 27, "">, semantic_type = !obelisk.ranged_packed_array<87 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 27 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 27, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 52 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">, source_end_column = 59 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 59, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 53 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 58, "">, semantic_type = !obelisk.void, source_end_column = 58 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 35, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 58, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a1", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s19.a1} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "follow-fail", is_signed = false, node_id = 54 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 57, "">, semantic_type = !obelisk.ranged_packed_array<87 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 57 : i64, source_end_line = 5 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 5, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 5, 57, "">} {
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.a2", name = "a2", node_id = 55 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, source_end_column = 27 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, sym_name = "s21.a2"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 56 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, procedure_kind = 2 : i32, source_end_column = 27 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, sym_name = "s22", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.a2", block_symbol = @s1.$root::@s3.top::@s4.top::@s21.a2, node_id = 57 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, source_end_column = 27 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 2 : i32, has_default_disable = false, has_fail_action = false, has_pass_action = true, node_id = 58 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, source_end_column = 27 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 59 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 23, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 57, "">, source_end_column = 57 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 23, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 57, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 60 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 25, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 36, "">, source_end_column = 36 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 25, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 36, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 61 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 36, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 36 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 36, "">} {
                  }
                }
                obelisk.sv.assertion.unary attributes {has_range = false, node_id = 62 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 38, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 57, "">, range_is_unbounded = false, source_end_column = 57 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 38, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 57, "">} {
                  obelisk.sv.assertion.binary attributes {node_id = 63 : i64, operator_kind = 14 : i32, operator_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 51, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 54, "">, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 42, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 57, "">, source_end_column = 57 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 42, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 57, "">} {
                    obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 64 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 50, "">, repetition_is_unbounded = false, repetition_kind = 0 : i32, repetition_max = 1 : i64, repetition_min = 0 : i64, source_end_column = 50 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 50, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 65 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 44, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 44 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 43, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 44, "">} {
                      }
                    }
                    obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 66 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 56, "">, repetition_is_unbounded = false, source_end_column = 56 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 56, "">} {
                      obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 67 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 56, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 56 : i64, source_end_line = 6 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 6, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 6, 56, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 68 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 7, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">, source_end_column = 27 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 7, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 27, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 69 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 7, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 26, "">, semantic_type = !obelisk.void, source_end_column = 26 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 7, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 26, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a2", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s21.a2} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "cover-hit", is_signed = false, node_id = 70 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 7, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 25, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 25 : i64, source_end_line = 7 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 7, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 7, 25, "">} {
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.statement_block attributes {block_kind = 0 : i32, hierarchical_name = "top.a3", name = "a3", node_id = 71 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, source_end_column = 55 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, sym_name = "s23.a3"} {
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 72 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, procedure_kind = 2 : i32, source_end_column = 55 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, sym_name = "s24", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {block_path = "top.a3", block_symbol = @s1.$root::@s3.top::@s4.top::@s23.a3, node_id = 73 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, source_end_column = 55 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">} {
            obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 74 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, source_end_column = 55 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 3, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">} {
              obelisk.sv.assertion.clocking attributes {node_id = 75 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 64, "">, source_end_column = 64 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 64, "">} {
                obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 76 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 26, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 37, "">, source_end_column = 37 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 26, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 37, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 77 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 34, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 37, "">, referenced_path = "top.clk", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s6.clk, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 37 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 34, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 37, "">} {
                  }
                }
                obelisk.sv.assertion.disable_iff attributes {node_id = 78 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 56, "">, source_end_column = 56 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 56, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 79 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 52, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 55, "">, referenced_path = "top.dis", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s16.dis, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 55 : i64, source_end_line = 8 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 8, 52, "../../../../tmp/obelisk-mixed-empty-not.sv", 8, 55, "">} {
                  }
                  obelisk.sv.assertion.unary attributes {has_range = false, node_id = 80 : i64, operator_kind = 0 : i32, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 64, "">, range_is_unbounded = false, source_end_column = 64 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 24, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 64, "">} {
                    obelisk.sv.assertion.binary attributes {node_id = 81 : i64, operator_kind = 12 : i32, operator_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 50, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 53, "">, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 28, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 64, "">, source_end_column = 64 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 28, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 64, "">} {
                      obelisk.sv.assertion.binary attributes {node_id = 82 : i64, operator_kind = 1 : i32, operator_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 36, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 38, "">, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 29, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 49, "">, source_end_column = 49 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 29, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 49, "">} {
                        obelisk.sv.assertion.simple attributes {has_repetition = true, is_null = false, node_id = 83 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 30, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 35, "">, repetition_is_unbounded = false, repetition_kind = 0 : i32, repetition_max = 0 : i64, repetition_min = 0 : i64, source_end_column = 35 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 30, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 35, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 84 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 30, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 31, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 31 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 30, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 31, "">} {
                          }
                        }
                        obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 44, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 45, "">}], node_id = 85 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 48, "">, source_end_column = 48 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 39, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 48, "">} {
                          obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 86 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 40, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 41, "">, repetition_is_unbounded = false, source_end_column = 41 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 40, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 41, "">} {
                            obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 87 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 40, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 41, "">, referenced_path = "top.a", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s8.a, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 41 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 40, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 41, "">} {
                            }
                          }
                          obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 88 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 46, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 47, "">, repetition_is_unbounded = false, source_end_column = 47 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 46, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 47, "">} {
                            obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 89 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 46, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 47, "">, referenced_path = "top.b", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s10.b, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 47 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 46, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 47, "">} {
                            }
                          }
                        }
                      }
                      obelisk.sv.assertion.sequence_concat attributes {delays = [{is_unbounded = false, max = 0 : i64, min = 0 : i64}, {is_unbounded = false, max = 1 : i64, min = 1 : i64, source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 59, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 60, "">}], node_id = 90 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 54, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 63, "">, source_end_column = 63 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 54, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 63, "">} {
                        obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 91 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 56, "">, repetition_is_unbounded = false, source_end_column = 56 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 56, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 92 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 56, "">, referenced_path = "top.c", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s12.c, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 56 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 55, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 56, "">} {
                          }
                        }
                        obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 93 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 61, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 62, "">, repetition_is_unbounded = false, source_end_column = 62 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 61, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 62, "">} {
                          obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 94 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 61, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 62, "">, referenced_path = "top.d", referenced_symbol = @s1.$root::@s3.top::@s4.top::@s14.d, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_end_column = 62 : i64, source_end_line = 9 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 9, 61, "../../../../tmp/obelisk-mixed-empty-not.sv", 9, 62, "">} {
                          }
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 95 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 27, "">, source_end_column = 27 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 27, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 96 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 26, "">, semantic_type = !obelisk.void, source_end_column = 26 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 5, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 26, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a3", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s23.a3} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "long-pass", is_signed = false, node_id = 97 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 25, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 25 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 14, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 25, "">} {
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 98 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">, source_end_column = 55 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 55, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 99 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 54, "">, semantic_type = !obelisk.void, source_end_column = 54 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 33, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 54, "">, subroutine_kind = 1 : i32, system_library_cell = "work.top", system_scope_path = "top.a3", system_scope_symbol = @s1.$root::@s3.top::@s4.top::@s23.a3} {
                  obelisk.sv.expression.string_literal attributes {constant_value = "long-fail", is_signed = false, node_id = 100 : i64, original_source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 42, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 53, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 53 : i64, source_end_line = 10 : i64, source_file = "../../../../tmp/obelisk-mixed-empty-not.sv", source_range = !obelisk.source_range<"../../../../tmp/obelisk-mixed-empty-not.sv", 10, 42, "../../../../tmp/obelisk-mixed-empty-not.sv", 10, 53, "">} {
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

// Temporal negation retains the mixed current/handoff source-age coalescer.
// Live implication failure selects the outer pass action and live implication
// success selects the outer fail action. A weak pending implication succeeds
// at EOS, so its negation emits only the outer failure callback.
// CHECK-NOT: @unit_0.$concurrent_eos_branch_report.20.pass
// CHECK-LABEL: obelisk_sim.func private @unit_0.$concurrent_eos_branch_report.20.fail
// CHECK: obelisk_sim.bytes.constant "impl-fail"
// CHECK-NOT: @unit_0.$concurrent_eos_branch_report.20.pass
// CHECK-LABEL: obelisk_sim.func private @unit_0.$concurrent_eos_branch.20
// CHECK: obelisk_sim.branching_antecedent_eos_result = "fail"
// CHECK-LABEL: obelisk_sim.func private @unit_0(
// CHECK-SAME: obelisk_sim.branching_antecedent_consequent_eos_strength = "weak"
// CHECK-SAME: obelisk_sim.branching_antecedent_result_horizon = 2 : i64
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_current_tick_channels = 1 : i64
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_handoff_channels = 1 : i64
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_nonoverlap
// CHECK-SAME: obelisk_sim.temporal_property_negation
// CHECK: obelisk_sim.branching_antecedent_universal_failure
// CHECK: obelisk_sim.branching_antecedent_universal_success
// CHECK: obelisk_sim.spawn @unit_0.fork.20.0.0
// CHECK: obelisk_sim.spawn @unit_0.fork.20.1.1
// CHECK: obelisk_sim.spawn @unit_0.fork.20.0.0
// CHECK: obelisk_sim.spawn @unit_0.fork.20.1.1
// CHECK-NOT: obelisk_sim.spawn @unit_0.fork.20

// Followed-by retains its existential result before the one final property
// inversion. Its weak pending handoff is an operand success and outer failure.
// CHECK-NOT: @unit_1.$concurrent_eos_branch_report.39.pass
// CHECK-LABEL: obelisk_sim.func private @unit_1.$concurrent_eos_branch_report.39.fail
// CHECK: obelisk_sim.bytes.constant "follow-fail"
// CHECK-NOT: @unit_1.$concurrent_eos_branch_report.39.pass
// CHECK-LABEL: obelisk_sim.func private @unit_1.$concurrent_eos_branch.39
// CHECK: obelisk_sim.branching_antecedent_eos_result = "fail"
// CHECK-LABEL: obelisk_sim.func private @unit_1(
// CHECK-SAME: obelisk_sim.branching_antecedent_consequent_eos_strength = "weak"
// CHECK-SAME: obelisk_sim.followed_by_monitor
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_nonoverlap
// CHECK-SAME: obelisk_sim.temporal_property_negation
// CHECK: obelisk_sim.branching_antecedent_existential_success
// CHECK: obelisk_sim.branching_antecedent_existential_failure
// CHECK: obelisk_sim.spawn @unit_1.fork.39.0.0
// CHECK: obelisk_sim.spawn @unit_1.fork.39.1.1
// CHECK: obelisk_sim.spawn @unit_1.fork.39.0.0
// CHECK: obelisk_sim.spawn @unit_1.fork.39.1.1
// CHECK-NOT: obelisk_sim.spawn @unit_1.fork.39

// Cover-property gives the operand a strong pending completion. Negation
// turns that failure into the one observable cover pass, including at EOS.
// CHECK-NOT: @unit_2.$concurrent_eos_branch_report.58.fail
// CHECK-LABEL: obelisk_sim.func private @unit_2.$concurrent_eos_branch_report.58.pass
// CHECK: obelisk_sim.bytes.constant "cover-hit"
// CHECK-NOT: @unit_2.$concurrent_eos_branch_report.58.fail
// CHECK-LABEL: obelisk_sim.func private @unit_2.$concurrent_eos_branch.58
// CHECK: obelisk_sim.branching_antecedent_eos_result = "pass"
// CHECK-LABEL: obelisk_sim.func private @unit_2(
// CHECK-SAME: obelisk_sim.branching_antecedent_consequent_eos_strength = "strong"
// CHECK-SAME: obelisk_sim.followed_by_monitor
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_nonoverlap
// CHECK-SAME: obelisk_sim.temporal_property_negation
// CHECK: obelisk_sim.branching_antecedent_existential_failure
// CHECK: obelisk_sim.spawn @unit_2.fork.58.0.0
// CHECK: obelisk_sim.spawn @unit_2.fork.58.0.0
// CHECK-NOT: obelisk_sim.spawn @unit_2.fork.58.0.0

// A multi-age mixed antecedent and multi-age consequent retain every state
// cell under disable. EOS selects only the negated weak failure action and
// reloads the captured epoch before dispatch.
// CHECK-LABEL: obelisk_sim.func private @unit_3.$concurrent_cancel.74
// CHECK-COUNT-4: obelisk_sim.ref.store {{.*}} : i64, !obelisk_sim.ref<i64>
// CHECK-NOT: obelisk_sim.ref.store
// CHECK: obelisk_sim.ref.load
// CHECK: arith.addi
// CHECK: obelisk_sim.ref.store
// CHECK-NOT: obelisk_sim.ref.store
// CHECK-NOT: @unit_3.$concurrent_eos_branch_report.74.pass
// CHECK-LABEL: obelisk_sim.func private @unit_3.$concurrent_eos_branch_report.74.fail
// CHECK: obelisk_sim.ref.load
// CHECK: arith.cmpi eq
// CHECK-LABEL: obelisk_sim.func private @unit_3.$concurrent_eos_branch.74
// CHECK: obelisk_sim.branching_antecedent_eos_result = "fail"
// CHECK: obelisk_sim.branching_antecedent_eos_source_age = 3 : i64
// CHECK: obelisk_sim.branching_antecedent_eos_source_age = 2 : i64
// CHECK: obelisk_sim.branching_antecedent_eos_source_age = 1 : i64
// CHECK-LABEL: obelisk_sim.func private @unit_3(
// CHECK-SAME: obelisk_sim.branching_antecedent_result_horizon = 4 : i64
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_current_tick_channels = 1 : i64
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_handoff_channels = 1 : i64
// CHECK-SAME: obelisk_sim.mixed_empty_antecedent_nonoverlap
// CHECK-SAME: obelisk_sim.temporal_property_negation
