// RUN: obelisk-opt %s --lower-obelisk-to-sim=opt-level=0 -o %t.sim.mlir
// RUN: FileCheck %s --check-prefix=SNAPSHOT < %t.sim.mlir

// Runtime behavior is checked in ../Runtime/obelisk-to-simulation-history-defaults.test.

// LRM 16.5.1 and 16.9.3: before-history values come from declaration defaults
// and recursive expression evaluation. A two-state expression can default to
// one; a four-state expression with X operands can still default to zero.
// Gated depth-two history and a distinct alternate clock track actual samples.
// A side-effecting initializer executes once per declaration, never on history
// underflow. Only the declaration whose history is used receives a snapshot.
// This fixture uses semantic MLIR and does not require a SystemVerilog frontend.
// SNAPSHOT-COUNT-2: debug "__obelisk_sample_default"
// SNAPSHOT-NOT: debug "__obelisk_sample_default"

module attributes {llvm.data_layout = "e-m:e-p:64:64-i64:64-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu", obelisk.coverage.language_version = 2023 : i32} {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "history_default_matrix", name = "history_default_matrix", node_id = 0 : i64, sym_name = "s0.history_default_matrix"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 1 : i64, sym_name = "s1.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 2 : i64, obelisk_sim.vpi_definition_name = "$unit", sym_name = "s2"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "history_default_matrix", is_uninstantiated = false, name = "history_default_matrix", node_id = 3 : i64, referenced_path = "history_default_matrix", referenced_symbol = @s0.history_default_matrix, sym_name = "s3.history_default_matrix"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "history_default_matrix", name = "history_default_matrix", node_id = 4 : i64, obelisk_sim.vpi_automatic = false, obelisk_sim.vpi_cell_instance = false, obelisk_sim.vpi_definition_name = "history_default_matrix", obelisk_sim.vpi_top = true, sym_name = "s4.history_default_matrix", time_precision_fs = 1000 : i64, time_unit_fs = 1000000 : i64, vpi_scope_kind = 32 : i32} {
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.clk", lifetime = 1 : i32, name = "clk", node_id = 5 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, sym_name = "s5.clk"} {
          obelisk.sv.expression.conversion attributes {folded_constant = "1'b0", is_implicit = true, is_signed = false, node_id = 6 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 2, 13, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 2, 14, "">} {
            obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 7 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 2, 13, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 2, 14, "">} {
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.zero", lifetime = 1 : i32, name = "zero", node_id = 8 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, sym_name = "s6.zero"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.initialized", lifetime = 1 : i32, name = "initialized", node_id = 9 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, sym_name = "s7.initialized"} {
          obelisk.sv.expression.conversion attributes {folded_constant = "4'b101", is_implicit = true, is_signed = false, node_id = 10 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 4, 29, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 4, 30, "">} {
            obelisk.sv.expression.conversion attributes {folded_constant = "5", is_implicit = true, is_signed = true, node_id = 11 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 4, 29, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 4, 30, "">} {
              obelisk.sv.expression.integer_literal attributes {constant_value = "5", is_declared_unsized = true, is_signed = true, node_id = 12 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 4, 29, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 4, 30, "">} {
              }
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.flag", lifetime = 1 : i32, name = "flag", node_id = 13 : i64, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, sym_name = "s8.flag"} {
          obelisk.sv.expression.conversion attributes {folded_constant = "1'b1", is_implicit = true, is_signed = false, node_id = 14 : i64, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 5, 16, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 5, 17, "">} {
            obelisk.sv.expression.conversion attributes {folded_constant = "1", is_implicit = true, is_signed = true, node_id = 15 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 5, 16, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 5, 17, "">} {
              obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 16 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 5, 16, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 5, 17, "">} {
              }
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.gate", lifetime = 1 : i32, name = "gate", node_id = 17 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, sym_name = "s9.gate"} {
          obelisk.sv.expression.conversion attributes {folded_constant = "1'b1", is_implicit = true, is_signed = false, node_id = 18 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 6, 14, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 6, 15, "">} {
            obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 19 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 6, 14, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 6, 15, "">} {
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.calls", lifetime = 1 : i32, name = "calls", node_id = 20 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, sym_name = "s10.calls"} {
          obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 21 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 7, 15, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 7, 16, "">} {
          }
        }
        obelisk.sv.symbol.subroutine attributes {hierarchical_name = "history_default_matrix.initialize", name = "initialize", node_id = 22 : i64, return_variable_path = "history_default_matrix.initialize.initialize", return_variable_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s11.initialize::@s12.initialize, semantic_type = !obelisk.subroutine<() -> !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, false>, subroutine_kind = 0 : i32, sym_name = "s11.initialize", time_precision_fs = 1000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.list attributes {node_id = 23 : i64} {
            obelisk.sv.statement.expression_statement attributes {node_id = 24 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 9, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 9, 13, "">} {
              obelisk.sv.expression.unary_op attributes {is_signed = true, node_id = 25 : i64, operator_kind = 12 : i32, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 9, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 9, 12, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 26 : i64, referenced_path = "history_default_matrix.calls", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s10.calls, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 9, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 9, 10, "">} {
                }
              }
            }
            obelisk.sv.statement.return attributes {node_id = 27 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 14, "">} {
              obelisk.sv.expression.conversion attributes {folded_constant = "4'b1001", is_implicit = true, is_signed = false, node_id = 28 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 12, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 13, "">} {
                obelisk.sv.expression.conversion attributes {folded_constant = "9", is_implicit = true, is_signed = true, node_id = 29 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 12, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 13, "">} {
                  obelisk.sv.expression.integer_literal attributes {constant_value = "9", is_declared_unsized = true, is_signed = true, node_id = 30 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 12, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 10, 13, "">} {
                  }
                }
              }
            }
          }
          obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.initialize.initialize", is_compiler_generated, name = "initialize", node_id = 31 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, sym_name = "s12.initialize"} {
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.dynamic_value", lifetime = 1 : i32, name = "dynamic_value", node_id = 32 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, sym_name = "s13.dynamic_value"} {
          obelisk.sv.expression.call attributes {argument_count = 0 : i64, callee_name = "initialize", constraint_restrictions = [], defaulted_arguments = array<i64>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = false, node_id = 33 : i64, referenced_path = "history_default_matrix.initialize", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s11.initialize, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32} {
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.unused_value", lifetime = 1 : i32, name = "unused_value", node_id = 34 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, sym_name = "s14.unused_value"} {
          obelisk.sv.expression.call attributes {argument_count = 0 : i64, callee_name = "initialize", constraint_restrictions = [], defaulted_arguments = array<i64>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = false, node_id = 35 : i64, referenced_path = "history_default_matrix.initialize", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s11.initialize, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32} {
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.expected", lifetime = 1 : i32, name = "expected", node_id = 36 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, sym_name = "s15.expected"} {
          obelisk.sv.expression.conversion attributes {folded_constant = "4'b101", is_implicit = true, is_signed = false, node_id = 37 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 14, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 14, 27, "">} {
            obelisk.sv.expression.conversion attributes {folded_constant = "5", is_implicit = true, is_signed = true, node_id = 38 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 14, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 14, 27, "">} {
              obelisk.sv.expression.integer_literal attributes {constant_value = "5", is_declared_unsized = true, is_signed = true, node_id = 39 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 14, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 14, 27, "">} {
              }
            }
          }
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "history_default_matrix.lanes", lifetime = 1 : i32, name = "lanes", node_id = 40 : i64, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>, sym_name = "s16.lanes"} {
          obelisk.sv.expression.simple_assignment_pattern attributes {is_signed = false, node_id = 41 : i64, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 39, "">} {
            obelisk.sv.expression.conversion attributes {folded_constant = "4'b1001", is_implicit = true, is_signed = false, node_id = 42 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 28, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 32, "">} {
              obelisk.sv.expression.integer_literal attributes {constant_value = "4'b1001", is_signed = false, node_id = 43 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 28, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 32, "">} {
              }
            }
            obelisk.sv.expression.integer_literal attributes {constant_value = "4'bxxxx", is_signed = false, node_id = 44 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 34, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 15, 38, "">} {
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "history_default_matrix", node_id = 45 : i64, procedure_kind = 2 : i32, sym_name = "s17", time_precision_fs = 1000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.timed attributes {node_id = 46 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 10, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 24, "">} {
            obelisk.sv.timing.delay attributes {node_id = 47 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 10, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 12, "">} {
              obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 48 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 11, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 12, "">} {
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 49 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 13, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 24, "">} {
              obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 50 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 13, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 23, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 51 : i64, referenced_path = "history_default_matrix.clk", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s5.clk, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 13, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 16, "">} {
                }
                obelisk.sv.expression.unary_op attributes {is_signed = false, node_id = 52 : i64, operator_kind = 2 : i32, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 23, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 53 : i64, referenced_path = "history_default_matrix.clk", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s5.clk, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 20, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 16, 23, "">} {
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "history_default_matrix", node_id = 54 : i64, procedure_kind = 2 : i32, sym_name = "s18", time_precision_fs = 1000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.timed attributes {node_id = 55 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 17, 10, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 71, "">} {
            obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 56 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 17, 12, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 17, 23, "">} {
              obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 57 : i64, referenced_path = "history_default_matrix.clk", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s5.clk, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 17, 20, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 17, 23, "">} {
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 58 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 18, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 71, "">} {
              obelisk.sv.expression.call attributes {argument_count = 9 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0, 0, 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 59 : i64, semantic_type = !obelisk.void, subroutine_kind = 1 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                obelisk.sv.expression.string_literal attributes {constant_value = "defaults %h %h %h calls=%0d gate=%h nested=%b masked=%h lane=%h", is_signed = false, node_id = 60 : i64, semantic_type = !obelisk.ranged_packed_array<503 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 18, 14, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 18, 79, "">} {
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 61 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.binary_op attributes {is_signed = false, node_id = 62 : i64, operator_kind = 0 : i32, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 20, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 31, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 63 : i64, referenced_path = "history_default_matrix.zero", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s6.zero, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 20, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 24, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "4'b1", is_signed = false, node_id = 64 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 27, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 31, "">} {
                    }
                  }
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 65 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 66 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 40, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 51, "">} {
                  }
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 67 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 68 : i64, referenced_path = "history_default_matrix.dynamic_value", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s13.dynamic_value, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 60, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 19, 73, "">} {
                  }
                }
                obelisk.sv.expression.named_value attributes {is_signed = true, node_id = 69 : i64, referenced_path = "history_default_matrix.calls", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s10.calls, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 14, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 19, "">} {
                }
                obelisk.sv.expression.call attributes {argument_count = 3 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 70 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 71 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 27, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 38, "">} {
                  }
                  obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 72 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 40, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 41, "">} {
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 73 : i64, referenced_path = "history_default_matrix.gate", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s9.gate, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 43, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 20, 47, "">} {
                  }
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$fell", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 74 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 75 : i64, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 76 : i64, referenced_path = "history_default_matrix.flag", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s8.flag, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 30, "">} {
                    }
                  }
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 77 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.binary_op attributes {is_signed = false, node_id = 78 : i64, operator_kind = 5 : i32, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 40, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 51, "">} {
                    obelisk.sv.expression.integer_literal attributes {constant_value = "4'bxxxx", is_signed = false, node_id = 79 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 40, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 44, "">} {
                    }
                    obelisk.sv.expression.conversion attributes {folded_constant = "4'b0", is_implicit = true, is_signed = false, node_id = 80 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 47, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 51, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "4'b0", is_signed = false, node_id = 81 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 47, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 51, "">} {
                      }
                    }
                  }
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 82 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 83 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 60, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 68, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 84 : i64, referenced_path = "history_default_matrix.lanes", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s16.lanes, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 60, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 65, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 85 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 66, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 21, 67, "">} {
                    }
                  }
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "history_default_matrix", node_id = 86 : i64, procedure_kind = 2 : i32, sym_name = "s19", time_precision_fs = 1000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.concurrent_assertion attributes {assertion_kind = 0 : i32, has_default_disable = false, has_fail_action = true, has_pass_action = true, node_id = 87 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 22, 3, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 48, "">} {
            obelisk.sv.assertion.clocking attributes {node_id = 88 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 22, 20, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 59, "">} {
              obelisk.sv.timing.signal_event attributes {edge_kind = 1 : i32, has_iff = false, node_id = 89 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 22, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 22, 33, "">} {
                obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 90 : i64, referenced_path = "history_default_matrix.clk", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s5.clk, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 22, 30, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 22, 33, "">} {
                }
              }
              obelisk.sv.assertion.simple attributes {has_repetition = false, is_null = false, node_id = 91 : i64, repetition_is_unbounded = false, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 7, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 59, "">} {
                obelisk.sv.expression.binary_op attributes {is_signed = false, node_id = 92 : i64, operator_kind = 11 : i32, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 7, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 59, "">} {
                  obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$past", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 93 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 94 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 13, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 24, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 95 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 27, "">} {
                    }
                    obelisk.sv.expression.empty_argument attributes {is_signed = false, node_id = 96 : i64, semantic_type = !obelisk.void, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 29, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 29, "">} {
                    }
                    obelisk.sv.expression.clocking_event attributes {is_signed = false, node_id = 97 : i64, semantic_type = !obelisk.void, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 31, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 45, "">} {
                      obelisk.sv.timing.signal_event attributes {edge_kind = 2 : i32, has_iff = false, node_id = 98 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 33, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 44, "">} {
                        obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 99 : i64, referenced_path = "history_default_matrix.clk", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s5.clk, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 41, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 44, "">} {
                        }
                      }
                    }
                  }
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 100 : i64, referenced_path = "history_default_matrix.expected", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s15.expected, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 51, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 23, 59, "">} {
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 101 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 24, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 24, 50, "">} {
              obelisk.sv.expression.call attributes {argument_count = 2 : i64, callee_name = "$display", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 102 : i64, semantic_type = !obelisk.void, subroutine_kind = 1 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                obelisk.sv.expression.string_literal attributes {constant_value = "alternate %h", is_signed = false, node_id = 103 : i64, semantic_type = !obelisk.ranged_packed_array<95 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 24, 14, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 24, 28, "">} {
                }
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$sampled", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 104 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 105 : i64, referenced_path = "history_default_matrix.expected", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s15.expected, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 24, 39, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 24, 47, "">} {
                  }
                }
              }
            }
            obelisk.sv.statement.expression_statement attributes {node_id = 106 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 48, "">} {
              obelisk.sv.expression.call attributes {argument_count = 2 : i64, callee_name = "$fatal", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 107 : i64, semantic_type = !obelisk.void, subroutine_kind = 0 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 108 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 15, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 16, "">} {
                }
                obelisk.sv.expression.string_literal attributes {constant_value = "alternate default mismatch", is_signed = false, node_id = 109 : i64, semantic_type = !obelisk.ranged_packed_array<207 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 18, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 25, 46, "">} {
                }
              }
            }
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "history_default_matrix", node_id = 110 : i64, procedure_kind = 0 : i32, sym_name = "s20", time_precision_fs = 1000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {node_id = 111 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 26, 11, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 33, 6, "">} {
            obelisk.sv.statement.list attributes {node_id = 112 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 26, 11, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 33, 6, "">} {
              obelisk.sv.statement.expression_statement attributes {node_id = 113 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 21, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 114 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 20, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 115 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 16, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "4'b111", is_implicit = true, is_signed = false, node_id = 116 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 20, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "7", is_implicit = true, is_signed = true, node_id = 117 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 20, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "7", is_declared_unsized = true, is_signed = true, node_id = 118 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 20, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 119 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 40, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 120 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 39, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 121 : i64, referenced_path = "history_default_matrix.dynamic_value", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s13.dynamic_value, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 35, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "4'b11", is_implicit = true, is_signed = false, node_id = 122 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 38, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 39, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "3", is_implicit = true, is_signed = true, node_id = 123 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 38, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 39, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, node_id = 124 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 38, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 39, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 125 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 41, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 50, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 126 : i64, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 41, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 49, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 127 : i64, referenced_path = "history_default_matrix.flag", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s8.flag, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 41, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 45, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b0", is_implicit = true, is_signed = false, node_id = 128 : i64, semantic_type = !obelisk.integral<1, false, true, 0 : 0, logic>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 48, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 49, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "0", is_implicit = true, is_signed = true, node_id = 129 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 48, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 49, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 130 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 48, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 27, 49, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 131 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 18, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 132 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 17, "">} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 133 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 13, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 134 : i64, referenced_path = "history_default_matrix.lanes", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s16.lanes, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 10, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 135 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 11, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 12, "">} {
                    }
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "4'b11", is_implicit = true, is_signed = false, node_id = 136 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 16, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 17, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "3", is_implicit = true, is_signed = true, node_id = 137 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 16, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 17, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, node_id = 138 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 16, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 17, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 139 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 32, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 140 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 31, "">} {
                  obelisk.sv.expression.element_select attributes {is_signed = false, node_id = 141 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 27, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 142 : i64, referenced_path = "history_default_matrix.lanes", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s16.lanes, semantic_type = !obelisk.ranged_unpacked_array<0 : 1 x !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 19, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 24, "">} {
                    }
                    obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 143 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 26, "">} {
                    }
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "4'b100", is_implicit = true, is_signed = false, node_id = 144 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 30, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 31, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "4", is_implicit = true, is_signed = true, node_id = 145 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 30, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 31, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "4", is_declared_unsized = true, is_signed = true, node_id = 146 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 30, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 28, 31, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.timed attributes {node_id = 147 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 24, "">} {
                obelisk.sv.timing.delay attributes {node_id = 148 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 7, "">} {
                  obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 149 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 6, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 7, "">} {
                  }
                }
                obelisk.sv.statement.expression_statement attributes {node_id = 150 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 24, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 151 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 23, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 152 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 19, "">} {
                    }
                    obelisk.sv.expression.conversion attributes {folded_constant = "4'b1000", is_implicit = true, is_signed = false, node_id = 153 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 23, "">} {
                      obelisk.sv.expression.conversion attributes {folded_constant = "8", is_implicit = true, is_signed = true, node_id = 154 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 23, "">} {
                        obelisk.sv.expression.integer_literal attributes {constant_value = "8", is_declared_unsized = true, is_signed = true, node_id = 155 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 23, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 156 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 34, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 157 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 33, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 158 : i64, referenced_path = "history_default_matrix.gate", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s9.gate, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 29, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b0", is_implicit = true, is_signed = false, node_id = 159 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 32, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 33, "">} {
                    obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, node_id = 160 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 32, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 33, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 161 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 35, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 54, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 162 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 35, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 53, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 163 : i64, referenced_path = "history_default_matrix.dynamic_value", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s13.dynamic_value, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 35, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 48, "">} {
                  }
                  obelisk.sv.expression.unbased_unsized_integer_literal attributes {constant_value = "4'bxxxx", is_signed = false, node_id = 164 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 51, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 29, 53, "">} {
                  }
                }
              }
              obelisk.sv.statement.timed attributes {node_id = 165 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 24, "">} {
                obelisk.sv.timing.delay attributes {node_id = 166 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 7, "">} {
                  obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 167 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 6, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 7, "">} {
                  }
                }
                obelisk.sv.statement.expression_statement attributes {node_id = 168 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 24, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 169 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 23, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 170 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 19, "">} {
                    }
                    obelisk.sv.expression.conversion attributes {folded_constant = "4'b1001", is_implicit = true, is_signed = false, node_id = 171 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 23, "">} {
                      obelisk.sv.expression.conversion attributes {folded_constant = "9", is_implicit = true, is_signed = true, node_id = 172 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 23, "">} {
                        obelisk.sv.expression.integer_literal attributes {constant_value = "9", is_declared_unsized = true, is_signed = true, node_id = 173 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 23, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 174 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 34, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 175 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 33, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 176 : i64, referenced_path = "history_default_matrix.gate", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s9.gate, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 25, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 29, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "1'b1", is_implicit = true, is_signed = false, node_id = 177 : i64, semantic_type = !obelisk.integral<1, false, false, 0 : 0, bit>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 32, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 33, "">} {
                    obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, node_id = 178 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 32, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 33, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 179 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 35, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 48, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 180 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 35, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 47, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 181 : i64, referenced_path = "history_default_matrix.expected", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s15.expected, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 35, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 43, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "4'b111", is_implicit = true, is_signed = false, node_id = 182 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 46, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 47, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "7", is_implicit = true, is_signed = true, node_id = 183 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 46, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 47, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "7", is_declared_unsized = true, is_signed = true, node_id = 184 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 46, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 47, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 185 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 49, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 68, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 186 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 49, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 67, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 187 : i64, referenced_path = "history_default_matrix.dynamic_value", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s13.dynamic_value, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 49, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 62, "">} {
                  }
                  obelisk.sv.expression.unbased_unsized_integer_literal attributes {constant_value = "4'bzzzz", is_signed = false, node_id = 188 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 65, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 30, 67, "">} {
                  }
                }
              }
              obelisk.sv.statement.timed attributes {node_id = 189 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 25, "">} {
                obelisk.sv.timing.delay attributes {node_id = 190 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 7, "">} {
                  obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 191 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 6, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 7, "">} {
                  }
                }
                obelisk.sv.statement.expression_statement attributes {node_id = 192 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 25, "">} {
                  obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 193 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 24, "">} {
                    obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 194 : i64, referenced_path = "history_default_matrix.initialized", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s7.initialized, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 19, "">} {
                    }
                    obelisk.sv.expression.conversion attributes {folded_constant = "4'b1010", is_implicit = true, is_signed = false, node_id = 195 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 24, "">} {
                      obelisk.sv.expression.conversion attributes {folded_constant = "10", is_implicit = true, is_signed = true, node_id = 196 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 24, "">} {
                        obelisk.sv.expression.integer_literal attributes {constant_value = "10", is_declared_unsized = true, is_signed = true, node_id = 197 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 22, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 24, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 198 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 39, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 199 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 38, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 200 : i64, referenced_path = "history_default_matrix.expected", referenced_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix::@s15.expected, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 26, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 34, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {folded_constant = "4'b1000", is_implicit = true, is_signed = false, node_id = 201 : i64, semantic_type = !obelisk.ranged_packed_array<3 : 0 x !obelisk.integral<1, false, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 37, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 38, "">} {
                    obelisk.sv.expression.conversion attributes {folded_constant = "8", is_implicit = true, is_signed = true, node_id = 202 : i64, semantic_type = !obelisk.ranged_packed_array<31 : 0 x !obelisk.integral<1, true, true, 0 : 0, logic>>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 37, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 38, "">} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "8", is_declared_unsized = true, is_signed = true, node_id = 203 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 37, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 31, 38, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.timed attributes {node_id = 204 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 16, "">} {
                obelisk.sv.timing.delay attributes {node_id = 205 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 5, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 7, "">} {
                  obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, node_id = 206 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 6, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 7, "">} {
                  }
                }
                obelisk.sv.statement.expression_statement attributes {node_id = 207 : i64, source_range = !obelisk.source_range<"tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 8, "tmp/bench/unified-loop/cores/scr1/history-default-matrix.sv", 32, 16, "">} {
                  obelisk.sv.expression.call attributes {argument_count = 0 : i64, callee_name = "$finish", constraint_restrictions = [], defaulted_arguments = array<i64>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 208 : i64, semantic_type = !obelisk.void, subroutine_kind = 1 : i32, system_library_cell = "work.history_default_matrix", system_scope_path = "history_default_matrix", system_scope_symbol = @s1.$root::@s3.history_default_matrix::@s4.history_default_matrix} {
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
