// RUN: obelisk-opt %s '--lower-obelisk-to-sim=opt-level=0' | FileCheck %s

module {
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "DUT", name = "DUT", node_id = 0 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 19, 10, "">, source_end_column = 10 : i64, source_end_line = 19 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 19, 10, "">, sym_name = "s0.DUT"} {
  }
  obelisk.sv.symbol.definition attributes {definition_kind = 0 : i32, hierarchical_name = "top", name = "top", node_id = 1 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 41, 10, "">, source_end_column = 10 : i64, source_end_line = 41 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 41, 10, "">, sym_name = "s1.top"} {
  }
  obelisk.sv.symbol.root attributes {hierarchical_name = "\\$root ", name = "$root", node_id = 2 : i64, sym_name = "s2.$root"} {
    obelisk.sv.symbol.compilation_unit attributes {hierarchical_name = "$unit", node_id = 3 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 42, 1, "">, source_end_column = 1 : i64, source_end_line = 42 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 42, 1, "">, sym_name = "s3"} {
    }
    obelisk.sv.symbol.instance attributes {hierarchical_name = "top", is_uninstantiated = false, name = "top", node_id = 4 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 8, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 8, "">, referenced_path = "top", referenced_symbol = @s1.top, source_end_column = 8 : i64, source_end_line = 21 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 8, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 8, "">, sym_name = "s4.top"} {
      obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top", name = "top", node_id = 5 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 41, 10, "">, source_end_column = 10 : i64, source_end_line = 41 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 21, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 41, 10, "">, sym_name = "s5.top", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.i", lifetime = 1 : i32, name = "i", node_id = 6 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 22, 18, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 22, 19, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 19 : i64, source_end_line = 22 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 22, 18, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 22, 19, "">, sym_name = "s6.i"} {
        }
        obelisk.sv.symbol.variable attributes {hierarchical_name = "top.r", lifetime = 1 : i32, name = "r", node_id = 7 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 23, 10, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 23, 11, "">, semantic_type = !obelisk.real, source_end_column = 11 : i64, source_end_line = 23 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 23, 10, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 23, 11, "">, sym_name = "s7.r"} {
        }
        obelisk.sv.symbol.instance attributes {hierarchical_name = "top.unit1", is_uninstantiated = false, name = "unit1", node_id = 8 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 24, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 24, 16, "">, referenced_path = "DUT", referenced_symbol = @s0.DUT, source_end_column = 16 : i64, source_end_line = 24 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 24, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 24, 16, "">, sym_name = "s8.unit1"} {
          obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.unit1", name = "DUT", node_id = 9 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 19, 10, "">, source_end_column = 10 : i64, source_end_line = 19 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 19, 10, "">, sym_name = "s9.DUT", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          }
        }
        obelisk.sv.symbol.instance attributes {hierarchical_name = "top.unit2", is_uninstantiated = false, name = "unit2", node_id = 10 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 25, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 25, 16, "">, referenced_path = "DUT", referenced_symbol = @s0.DUT, source_end_column = 16 : i64, source_end_line = 25 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 25, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 25, 16, "">, sym_name = "s10.unit2"} {
          obelisk.sv.symbol.instance_body attributes {hierarchical_name = "top.unit2", name = "DUT", node_id = 11 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 19, 10, "">, source_end_column = 10 : i64, source_end_line = 19 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 18, 1, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 19, 10, "">, sym_name = "s11.DUT", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          }
        }
        obelisk.sv.symbol.procedural_block attributes {hierarchical_name = "top", node_id = 12 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 27, 5, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 40, 8, "">, procedure_kind = 0 : i32, source_end_column = 8 : i64, source_end_line = 40 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 27, 5, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 40, 8, "">, sym_name = "s12", time_precision_fs = 1000000 : i64, time_unit_fs = 1000000 : i64} {
          obelisk.sv.statement.block attributes {node_id = 13 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 27, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 40, 8, "">, source_end_column = 8 : i64, source_end_line = 40 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 27, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 40, 8, "">} {
            obelisk.sv.statement.list attributes {node_id = 14 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 27, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 40, 8, "">, source_end_column = 8 : i64, source_end_line = 40 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 27, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 40, 8, "">} {
              obelisk.sv.statement.expression_statement attributes {node_id = 15 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 83, "">, source_end_column = 83 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 83, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 16 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 82, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 82 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 82, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 17 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 18 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 82, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 82 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 82, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$coverage_control", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 19 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 82, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 82 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 82, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "3", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 44, "">, name = "SV_COV_CHECK"}], macro_name = "SV_COV_CHECK", node_id = 20 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 31, "SV_COV_CHECK">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "23", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 60, "">, name = "SV_COV_TOGGLE"}], macro_name = "SV_COV_TOGGLE", node_id = 21 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 46, "SV_COV_TOGGLE">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "11", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 74, "">, name = "SV_COV_HIER"}], macro_name = "SV_COV_HIER", node_id = 22 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 62 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 62, "SV_COV_HIER">} {
                      }
                      obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 23 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 81, "">, referenced_path = "\\$root ", referenced_symbol = @s2.$root, semantic_type = !obelisk.void, source_end_column = 81 : i64, source_end_line = 28 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 28, 81, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 24 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 85, "">, source_end_column = 85 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 85, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 25 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 84, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 84 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 84, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 26 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 27 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 84, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 84 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 84, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$coverage_control", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 28 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 84, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 84 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 84, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 44, "">, name = "SV_COV_RESET"}], macro_name = "SV_COV_RESET", node_id = 29 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 31, "SV_COV_RESET">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "23", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 60, "">, name = "SV_COV_TOGGLE"}], macro_name = "SV_COV_TOGGLE", node_id = 30 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 46, "SV_COV_TOGGLE">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "10", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 76, "">, name = "SV_COV_MODULE"}], macro_name = "SV_COV_MODULE", node_id = 31 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 62 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 62, "SV_COV_MODULE">} {
                      }
                      obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 32 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 78, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 83, "">, semantic_type = !obelisk.string, source_end_column = 83 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 78, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 83, "">} {
                        obelisk.sv.expression.string_literal attributes {constant_value = "DUT", is_signed = false, node_id = 33 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 78, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 83, "">, semantic_type = !obelisk.ranged_packed_array<23 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 83 : i64, source_end_line = 29 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 78, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 29, 83, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 34 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 95, "">, source_end_column = 95 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 95, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 35 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 94, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 94 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 94, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 36 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 37 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 94, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 94 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 94, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$coverage_control", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 38 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 94, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 94 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 94, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "2", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 44, "">, name = "SV_COV_RESET"}], macro_name = "SV_COV_RESET", node_id = 39 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 31, "SV_COV_RESET">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "23", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 60, "">, name = "SV_COV_TOGGLE"}], macro_name = "SV_COV_TOGGLE", node_id = 40 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 46, "SV_COV_TOGGLE">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "10", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 76, "">, name = "SV_COV_MODULE"}], macro_name = "SV_COV_MODULE", node_id = 41 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 62 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 62, "SV_COV_MODULE">} {
                      }
                      obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 42 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 78, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 93, "">, referenced_path = "top.unit1", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s8.unit1, semantic_type = !obelisk.void, source_end_column = 93 : i64, source_end_line = 30 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 78, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 30, 93, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 43 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 93, "">, source_end_column = 93 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 93, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 44 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 92, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 92 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 92, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 45 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 46 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 92, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 92 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 92, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$coverage_control", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 47 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 92, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 92 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 92, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "1", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 43, "">, name = "SV_COV_STOP"}], macro_name = "SV_COV_STOP", node_id = 48 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 31, "SV_COV_STOP">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "23", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 60, "">, name = "SV_COV_TOGGLE"}], macro_name = "SV_COV_TOGGLE", node_id = 49 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 46, "SV_COV_TOGGLE">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "11", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 74, "">, name = "SV_COV_HIER"}], macro_name = "SV_COV_HIER", node_id = 50 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 62 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 62, "SV_COV_HIER">} {
                      }
                      obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 51 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 91, "">, referenced_path = "top.unit2", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s10.unit2, semantic_type = !obelisk.void, source_end_column = 91 : i64, source_end_line = 31 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 31, 91, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 52 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 83, "">, source_end_column = 83 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 83, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 53 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 82, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 82 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 82, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 54 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 55 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 82, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 82 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 82, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 4 : i64, callee_name = "$coverage_control", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 56 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 82, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 82 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 82, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "0", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 44, "">, name = "SV_COV_START"}], macro_name = "SV_COV_START", node_id = 57 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 31, "SV_COV_START">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "23", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 60, "">, name = "SV_COV_TOGGLE"}], macro_name = "SV_COV_TOGGLE", node_id = 58 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 46, "SV_COV_TOGGLE">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "11", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 74, "">, name = "SV_COV_HIER"}], macro_name = "SV_COV_HIER", node_id = 59 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 62 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 62, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 62, "SV_COV_HIER">} {
                      }
                      obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 60 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 81, "">, semantic_type = !obelisk.string, source_end_column = 81 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 81, "">} {
                        obelisk.sv.expression.string_literal attributes {constant_value = "DUT", is_signed = false, node_id = 61 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 81, "">, semantic_type = !obelisk.ranged_packed_array<23 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 81 : i64, source_end_line = 32 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 76, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 32, 81, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 62 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 68, "">, source_end_column = 68 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 68, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 63 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 67, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 67 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 67, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 64 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 65 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 67, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 67 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 67, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 3 : i64, callee_name = "$coverage_get_max", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 66 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 67, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 67 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 67, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "23", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 45, "">, name = "SV_COV_TOGGLE"}], macro_name = "SV_COV_TOGGLE", node_id = 67 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 31 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 31, "SV_COV_TOGGLE">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "11", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 47, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 59, "">, name = "SV_COV_HIER"}], macro_name = "SV_COV_HIER", node_id = 68 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 47 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 47, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 47, "SV_COV_HIER">} {
                      }
                      obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 69 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 61, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 66, "">, semantic_type = !obelisk.string, source_end_column = 66 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 61, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 66, "">} {
                        obelisk.sv.expression.string_literal attributes {constant_value = "DUT", is_signed = false, node_id = 70 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 61, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 66, "">, semantic_type = !obelisk.ranged_packed_array<23 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 66 : i64, source_end_line = 33 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 61, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 33, 66, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 71 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 77, "">, source_end_column = 77 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 77, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 72 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 76, "">, semantic_type = !obelisk.real, source_end_column = 76 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 76, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 73 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 10, "">, referenced_path = "top.r", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s7.r, semantic_type = !obelisk.real, source_end_column = 10 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 74 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 76, "">, semantic_type = !obelisk.real, source_end_column = 76 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 76, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 3 : i64, callee_name = "$coverage_get", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 75 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 76, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 76 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 76, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "22", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 27, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 44, "">, name = "SV_COV_STATEMENT"}], macro_name = "SV_COV_STATEMENT", node_id = 76 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 27 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 27, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 27, "SV_COV_STATEMENT">} {
                      }
                      obelisk.sv.expression.integer_literal attributes {constant_value = "11", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 58, "">, name = "SV_COV_HIER"}], macro_name = "SV_COV_HIER", node_id = 77 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 46 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 46, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 46, "SV_COV_HIER">} {
                      }
                      obelisk.sv.expression.arbitrary_symbol attributes {is_signed = false, node_id = 78 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 60, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 75, "">, referenced_path = "top.unit1", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s8.unit1, semantic_type = !obelisk.void, source_end_column = 75 : i64, source_end_line = 34 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 60, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 34, 75, "">} {
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 79 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 61, "">, source_end_column = 61 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 61, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 80 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 60, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 60 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 60, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 81 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 82 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 60, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 60 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 60, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 2 : i64, callee_name = "$coverage_merge", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 83 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 60, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 60 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 60, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "20", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 29, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 46, "">, name = "SV_COV_ASSERTION"}], macro_name = "SV_COV_ASSERTION", node_id = 84 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 29 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 29, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 29, "SV_COV_ASSERTION">} {
                      }
                      obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 85 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 48, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 59, "">, semantic_type = !obelisk.string, source_end_column = 59 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 48, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 59, "">} {
                        obelisk.sv.expression.string_literal attributes {constant_value = "some_name", is_signed = false, node_id = 86 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 48, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 59, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 59 : i64, source_end_line = 35 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 48, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 35, 59, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 87 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 60, "">, source_end_column = 60 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 60, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 88 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 59, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 59 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 59, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 89 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 10, "">, referenced_path = "top.i", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s6.i, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 10 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 10, "">} {
                  }
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 90 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 59, "">, semantic_type = !obelisk.integral<32, false, false, 31 : 0, int>, source_end_column = 59 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 59, "">} {
                    obelisk.sv.expression.call attributes {argument_count = 2 : i64, callee_name = "$coverage_save", constraint_restrictions = [], defaulted_arguments = array<i64: 0, 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = true, is_super_class = false, is_system_call = true, node_id = 91 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 59, "">, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 59 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 59, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                      obelisk.sv.expression.integer_literal attributes {constant_value = "21", is_declared_unsized = true, is_signed = true, macro_expansion_stack = [{invocation = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 28, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 45, "">, name = "SV_COV_FSM_STATE"}], macro_name = "SV_COV_FSM_STATE", node_id = 92 : i64, semantic_type = !obelisk.integral<32, true, false, 31 : 0, int>, source_end_column = 28 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 28, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 28, "SV_COV_FSM_STATE">} {
                      }
                      obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 93 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 47, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 58, "">, semantic_type = !obelisk.string, source_end_column = 58 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 47, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 58, "">} {
                        obelisk.sv.expression.string_literal attributes {constant_value = "some_name", is_signed = false, node_id = 94 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 47, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 58, "">, semantic_type = !obelisk.ranged_packed_array<71 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 58 : i64, source_end_line = 36 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 47, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 36, 58, "">} {
                        }
                      }
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 95 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 46, "">, source_end_column = 46 : i64, source_end_line = 37 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 46, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$set_coverage_db_name", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 96 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 45, "">, semantic_type = !obelisk.void, source_end_column = 45 : i64, source_end_line = 37 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 45, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 97 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 44, "">, semantic_type = !obelisk.string, source_end_column = 44 : i64, source_end_line = 37 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 44, "">} {
                    obelisk.sv.expression.string_literal attributes {constant_value = "coverage.db", is_signed = false, node_id = 98 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 44, "">, semantic_type = !obelisk.ranged_packed_array<87 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 44 : i64, source_end_line = 37 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 31, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 37, 44, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 99 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 42, "">, source_end_column = 42 : i64, source_end_line = 38 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 42, "">} {
                obelisk.sv.expression.call attributes {argument_count = 1 : i64, callee_name = "$load_coverage_db", constraint_restrictions = [], defaulted_arguments = array<i64: 0>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 100 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 41, "">, semantic_type = !obelisk.void, source_end_column = 41 : i64, source_end_line = 38 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 41, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                  obelisk.sv.expression.conversion attributes {is_signed = false, node_id = 101 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 27, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 40, "">, semantic_type = !obelisk.string, source_end_column = 40 : i64, source_end_line = 38 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 27, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 40, "">} {
                    obelisk.sv.expression.string_literal attributes {constant_value = "coverage.db", is_signed = false, node_id = 102 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 27, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 40, "">, semantic_type = !obelisk.ranged_packed_array<87 : 0 x !obelisk.integral<1, false, false, 0 : 0, bit>>, source_end_column = 40 : i64, source_end_line = 38 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 27, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 38, 40, "">} {
                    }
                  }
                }
              }
              obelisk.sv.statement.expression_statement attributes {node_id = 103 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 29, "">, source_end_column = 29 : i64, source_end_line = 39 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 29, "">} {
                obelisk.sv.expression.assignment attributes {assignment_kind = 0 : i32, is_signed = false, node_id = 104 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 28, "">, semantic_type = !obelisk.real, source_end_column = 28 : i64, source_end_line = 39 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 28, "">} {
                  obelisk.sv.expression.named_value attributes {is_signed = false, node_id = 105 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 10, "">, referenced_path = "top.r", referenced_symbol = @s2.$root::@s4.top::@s5.top::@s7.r, semantic_type = !obelisk.real, source_end_column = 10 : i64, source_end_line = 39 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 9, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 10, "">} {
                  }
                  obelisk.sv.expression.call attributes {argument_count = 0 : i64, callee_name = "$get_coverage", constraint_restrictions = [], defaulted_arguments = array<i64>, has_inline_constraints = false, has_iterator_expression = false, has_output_arguments = false, has_this_class = false, is_signed = false, is_super_class = false, is_system_call = true, node_id = 106 : i64, original_source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 28, "">, semantic_type = !obelisk.real, source_end_column = 28 : i64, source_end_line = 39 : i64, source_file = "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", source_range = !obelisk.source_range<"benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 13, "benchmark/cache/svtests/tests/chapter-20/20.14--coverage.sv", 39, 28, "">, subroutine_kind = 0 : i32, system_library_cell = "work.top", system_scope_path = "top", system_scope_symbol = @s2.$root::@s4.top::@s5.top} {
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

// IEEE 1800-2017 40.3.2 status values for a simulator without code-coverage
// instrumentation. String module names are validated against elaborated
// definitions; hierarchical scope operands are selection syntax, not values.
// CHECK-LABEL: obelisk_sim.func private @{{unit_[0-9]+}}
// CHECK-DAG: %[[ZERO:.*]] = arith.constant 0 : i32
// CHECK-DAG: %[[ONE:.*]] = arith.constant 1 : i32
// CHECK-DAG: %[[ERROR:.*]] = arith.constant -1 : i32
// CHECK-DAG: %[[COVERAGE_ZERO:.*]] = arith.constant 0.000000e+00 : f64
// CHECK: obelisk_sim.ref.store %[[ZERO]]
// CHECK: %[[DUT_INPUT:.*]] = obelisk_sim.string.literal "DUT"
// CHECK: %[[DUT_NAME:.*]] = obelisk_sim.string.literal "DUT"
// CHECK: %[[DUT_CMP:.*]] = obelisk_sim.string.compare %[[DUT_INPUT]], %[[DUT_NAME]] case_insensitive = false
// CHECK: %[[DUT_VALID:.*]] = arith.cmpi eq, %[[DUT_CMP]], %[[ZERO]] : i32
// CHECK: %[[RESET_STATUS:.*]] = arith.select {{.*}}, %[[ONE]], %[[ERROR]] : i32
// CHECK: obelisk_sim.ref.store %[[RESET_STATUS]]
// CHECK: obelisk_sim.ref.store %[[ONE]]
// CHECK: obelisk_sim.ref.store %[[ONE]]
// CHECK: obelisk_sim.ref.store
// CHECK: obelisk_sim.ref.store
// CHECK: obelisk_sim.real.from_integer %[[ZERO]] signed = true : i32 -> f64
// CHECK: obelisk_sim.ref.store %[[ERROR]]
// CHECK: obelisk_sim.ref.store %[[ZERO]]
// CHECK: obelisk_sim.ref.store %[[COVERAGE_ZERO]]
